CREATE TABLE app.kitchen_sink (
  c_int2        smallint,
  c_int4        integer,
  c_int8        bigint,
  c_serial      serial,
  c_numeric     numeric(10,2),
  c_float4      real,
  c_float8      double precision,
  c_bool        boolean,
  c_text        text,
  c_varchar     varchar(50),
  c_char        char(10),
  c_uuid        uuid,
  c_bytea       bytea,
  c_jsonb       jsonb,
  c_json        json,
  c_inet        inet,
  c_date        date,
  c_time        time,
  c_timestamp   timestamp,
  c_timestamptz timestamptz,
  c_interval    interval,
  c_int_array   integer[],
  c_text_array  text[],
  c_status      app.user_status,
  c_address     app.address,
  c_email       app.email,
  c_generated   integer GENERATED ALWAYS AS (c_int4 * 2) STORED,
  c_identity    integer GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE audit.log (
  id         bigserial PRIMARY KEY,
  table_name text NOT NULL,
  changed_at timestamptz NOT NULL DEFAULT now()
);
