// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: sqld/v1/config/config.proto

package configv1

import (
	ir "github.com/yaroher/sqld/pkg/proto/sqld/v1/ir"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SqlKind int32

const (
	SqlKind_SQL_KIND_UNSPECIFIED SqlKind = 0
	SqlKind_SQL_KIND_SCHEMA      SqlKind = 1 // DDL -> Catalog
	SqlKind_SQL_KIND_QUERY       SqlKind = 2 // named DML queries -> Query
)

// Enum value maps for SqlKind.
var (
	SqlKind_name = map[int32]string{
		0: "SQL_KIND_UNSPECIFIED",
		1: "SQL_KIND_SCHEMA",
		2: "SQL_KIND_QUERY",
	}
	SqlKind_value = map[string]int32{
		"SQL_KIND_UNSPECIFIED": 0,
		"SQL_KIND_SCHEMA":      1,
		"SQL_KIND_QUERY":       2,
	}
)

func (x SqlKind) Enum() *SqlKind {
	p := new(SqlKind)
	*p = x
	return p
}

func (x SqlKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SqlKind) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_config_config_proto_enumTypes[0].Descriptor()
}

func (SqlKind) Type() protoreflect.EnumType {
	return &file_sqld_v1_config_config_proto_enumTypes[0]
}

func (x SqlKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SqlKind.Descriptor instead.
func (SqlKind) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_config_config_proto_rawDescGZIP(), []int{0}
}

// Config is the root of a generation run.
type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                       // config schema version, e.g. "1"
	Engine        ir.Engine              `protobuf:"varint,2,opt,name=engine,proto3,enum=sqld.v1.ir.Engine" json:"engine,omitempty"` // dialect; ENGINE_POSTGRESQL
	Sql           []*SqlSource           `protobuf:"bytes,3,rep,name=sql,proto3" json:"sql,omitempty"`                               // schema (DDL) and/or query (DML) sources
	Migrations    []*MigrationSource     `protobuf:"bytes,4,rep,name=migrations,proto3" json:"migrations,omitempty"`
	Plugins       []*PluginConfig        `protobuf:"bytes,5,rep,name=plugins,proto3" json:"plugins,omitempty"`
	Options       *GlobalOptions         `protobuf:"bytes,6,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_sqld_v1_config_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_config_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_sqld_v1_config_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Config) GetEngine() ir.Engine {
	if x != nil {
		return x.Engine
	}
	return ir.Engine(0)
}

func (x *Config) GetSql() []*SqlSource {
	if x != nil {
		return x.Sql
	}
	return nil
}

func (x *Config) GetMigrations() []*MigrationSource {
	if x != nil {
		return x.Migrations
	}
	return nil
}

func (x *Config) GetPlugins() []*PluginConfig {
	if x != nil {
		return x.Plugins
	}
	return nil
}

func (x *Config) GetOptions() *GlobalOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// SqlSource points at SQL input: a single file, a directory, or inline text.
type SqlSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*SqlSource_File
	//	*SqlSource_Dir
	//	*SqlSource_Inline
	Source        isSqlSource_Source `protobuf_oneof:"source"`
	Glob          string             `protobuf:"bytes,4,opt,name=glob,proto3" json:"glob,omitempty"`                              // pattern within `dir`; default "*.sql"
	Recursive     bool               `protobuf:"varint,5,opt,name=recursive,proto3" json:"recursive,omitempty"`                   // descend into subdirectories of `dir`
	Kind          SqlKind            `protobuf:"varint,6,opt,name=kind,proto3,enum=sqld.v1.config.SqlKind" json:"kind,omitempty"` // schema vs query
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SqlSource) Reset() {
	*x = SqlSource{}
	mi := &file_sqld_v1_config_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SqlSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqlSource) ProtoMessage() {}

func (x *SqlSource) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_config_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqlSource.ProtoReflect.Descriptor instead.
func (*SqlSource) Descriptor() ([]byte, []int) {
	return file_sqld_v1_config_config_proto_rawDescGZIP(), []int{1}
}

func (x *SqlSource) GetSource() isSqlSource_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *SqlSource) GetFile() string {
	if x != nil {
		if x, ok := x.Source.(*SqlSource_File); ok {
			return x.File
		}
	}
	return ""
}

func (x *SqlSource) GetDir() string {
	if x != nil {
		if x, ok := x.Source.(*SqlSource_Dir); ok {
			return x.Dir
		}
	}
	return ""
}

func (x *SqlSource) GetInline() string {
	if x != nil {
		if x, ok := x.Source.(*SqlSource_Inline); ok {
			return x.Inline
		}
	}
	return ""
}

func (x *SqlSource) GetGlob() string {
	if x != nil {
		return x.Glob
	}
	return ""
}

func (x *SqlSource) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *SqlSource) GetKind() SqlKind {
	if x != nil {
		return x.Kind
	}
	return SqlKind_SQL_KIND_UNSPECIFIED
}

type isSqlSource_Source interface {
	isSqlSource_Source()
}

type SqlSource_File struct {
	File string `protobuf:"bytes,1,opt,name=file,proto3,oneof"` // path to one .sql file
}

type SqlSource_Dir struct {
	Dir string `protobuf:"bytes,2,opt,name=dir,proto3,oneof"` // directory of .sql files
}

type SqlSource_Inline struct {
	Inline string `protobuf:"bytes,3,opt,name=inline,proto3,oneof"` // literal SQL
}

func (*SqlSource_File) isSqlSource_Source() {}

func (*SqlSource_Dir) isSqlSource_Source() {}

func (*SqlSource_Inline) isSqlSource_Source() {}

// MigrationSource points at a migrations directory. Always a folder; only the
// native (our own) migration format is supported for now. Third-party formats
// (goose, golang-migrate, dbmate, atlas, ...) come later.
type MigrationSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`   // migrations directory
	Glob          string                 `protobuf:"bytes,2,opt,name=glob,proto3" json:"glob,omitempty"` // default "*.sql"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationSource) Reset() {
	*x = MigrationSource{}
	mi := &file_sqld_v1_config_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationSource) ProtoMessage() {}

func (x *MigrationSource) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_config_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationSource.ProtoReflect.Descriptor instead.
func (*MigrationSource) Descriptor() ([]byte, []int) {
	return file_sqld_v1_config_config_proto_rawDescGZIP(), []int{2}
}

func (x *MigrationSource) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *MigrationSource) GetGlob() string {
	if x != nil {
		return x.Glob
	}
	return ""
}

// PluginSource locates the plugin implementation. Exactly one of wasm/binary/
// command is set.
type PluginSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Location:
	//
	//	*PluginSource_Wasm
	//	*PluginSource_Binary
	//	*PluginSource_Command
	Location      isPluginSource_Location `protobuf_oneof:"location"`
	Sha256        string                  `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"` // optional integrity check of the artifact
	Args          []string                `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`     // extra args passed to binary/command
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginSource) Reset() {
	*x = PluginSource{}
	mi := &file_sqld_v1_config_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginSource) ProtoMessage() {}

func (x *PluginSource) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_config_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginSource.ProtoReflect.Descriptor instead.
func (*PluginSource) Descriptor() ([]byte, []int) {
	return file_sqld_v1_config_config_proto_rawDescGZIP(), []int{3}
}

func (x *PluginSource) GetLocation() isPluginSource_Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *PluginSource) GetWasm() string {
	if x != nil {
		if x, ok := x.Location.(*PluginSource_Wasm); ok {
			return x.Wasm
		}
	}
	return ""
}

func (x *PluginSource) GetBinary() string {
	if x != nil {
		if x, ok := x.Location.(*PluginSource_Binary); ok {
			return x.Binary
		}
	}
	return ""
}

func (x *PluginSource) GetCommand() string {
	if x != nil {
		if x, ok := x.Location.(*PluginSource_Command); ok {
			return x.Command
		}
	}
	return ""
}

func (x *PluginSource) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *PluginSource) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type isPluginSource_Location interface {
	isPluginSource_Location()
}

type PluginSource_Wasm struct {
	Wasm string `protobuf:"bytes,1,opt,name=wasm,proto3,oneof"` // path to a .wasm module (host instantiates)
}

type PluginSource_Binary struct {
	Binary string `protobuf:"bytes,2,opt,name=binary,proto3,oneof"` // path to an executable (gRPC over stdio)
}

type PluginSource_Command struct {
	Command string `protobuf:"bytes,3,opt,name=command,proto3,oneof"` // command resolved via PATH (gRPC over stdio)
}

func (*PluginSource_Wasm) isPluginSource_Location() {}

func (*PluginSource_Binary) isPluginSource_Location() {}

func (*PluginSource_Command) isPluginSource_Location() {}

// PluginConfig declares one generator plugin and its settings for this run.
type PluginConfig struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // logical name, used in diagnostics
	Source *PluginSource          `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Out    string                 `protobuf:"bytes,3,opt,name=out,proto3" json:"out,omitempty"` // output directory (relative to config file)
	// Plugin-specific settings. Opaque to the host: the plugin decodes these
	// bytes into its own options message (e.g. a serialized proto or raw JSON).
	Options       []byte            `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	Enabled       bool              `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`                                                                  // default true; set false to skip
	Env           map[string]string `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // env vars for process (binary/command) plugins
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginConfig) Reset() {
	*x = PluginConfig{}
	mi := &file_sqld_v1_config_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginConfig) ProtoMessage() {}

func (x *PluginConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_config_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginConfig.ProtoReflect.Descriptor instead.
func (*PluginConfig) Descriptor() ([]byte, []int) {
	return file_sqld_v1_config_config_proto_rawDescGZIP(), []int{4}
}

func (x *PluginConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginConfig) GetSource() *PluginSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *PluginConfig) GetOut() string {
	if x != nil {
		return x.Out
	}
	return ""
}

func (x *PluginConfig) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *PluginConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PluginConfig) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

// GlobalOptions are host-level settings applied before plugins run.
type GlobalOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefaultSchema string                 `protobuf:"bytes,1,opt,name=default_schema,json=defaultSchema,proto3" json:"default_schema,omitempty"` // usually "public"
	SearchPath    []string               `protobuf:"bytes,2,rep,name=search_path,json=searchPath,proto3" json:"search_path,omitempty"`
	// Global type overrides, e.g. "public.users.id" -> a canonical type name,
	// consumed by the host when building the Catalog.
	TypeOverrides map[string]string `protobuf:"bytes,3,rep,name=type_overrides,json=typeOverrides,proto3" json:"type_overrides,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Strict        bool              `protobuf:"varint,4,opt,name=strict,proto3" json:"strict,omitempty"` // fail the run on any parse/resolve warning
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalOptions) Reset() {
	*x = GlobalOptions{}
	mi := &file_sqld_v1_config_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalOptions) ProtoMessage() {}

func (x *GlobalOptions) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_config_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalOptions.ProtoReflect.Descriptor instead.
func (*GlobalOptions) Descriptor() ([]byte, []int) {
	return file_sqld_v1_config_config_proto_rawDescGZIP(), []int{5}
}

func (x *GlobalOptions) GetDefaultSchema() string {
	if x != nil {
		return x.DefaultSchema
	}
	return ""
}

func (x *GlobalOptions) GetSearchPath() []string {
	if x != nil {
		return x.SearchPath
	}
	return nil
}

func (x *GlobalOptions) GetTypeOverrides() map[string]string {
	if x != nil {
		return x.TypeOverrides
	}
	return nil
}

func (x *GlobalOptions) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

var File_sqld_v1_config_config_proto protoreflect.FileDescriptor

const file_sqld_v1_config_config_proto_rawDesc = "" +
	"\n" +
	"\x1bsqld/v1/config/config.proto\x12\x0esqld.v1.config\x1a\x17sqld/v1/ir/common.proto\"\xad\x02\n" +
	"\x06Config\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12*\n" +
	"\x06engine\x18\x02 \x01(\x0e2\x12.sqld.v1.ir.EngineR\x06engine\x12+\n" +
	"\x03sql\x18\x03 \x03(\v2\x19.sqld.v1.config.SqlSourceR\x03sql\x12?\n" +
	"\n" +
	"migrations\x18\x04 \x03(\v2\x1f.sqld.v1.config.MigrationSourceR\n" +
	"migrations\x126\n" +
	"\aplugins\x18\x05 \x03(\v2\x1c.sqld.v1.config.PluginConfigR\aplugins\x127\n" +
	"\aoptions\x18\x06 \x01(\v2\x1d.sqld.v1.config.GlobalOptionsR\aoptions\"\xb8\x01\n" +
	"\tSqlSource\x12\x14\n" +
	"\x04file\x18\x01 \x01(\tH\x00R\x04file\x12\x12\n" +
	"\x03dir\x18\x02 \x01(\tH\x00R\x03dir\x12\x18\n" +
	"\x06inline\x18\x03 \x01(\tH\x00R\x06inline\x12\x12\n" +
	"\x04glob\x18\x04 \x01(\tR\x04glob\x12\x1c\n" +
	"\trecursive\x18\x05 \x01(\bR\trecursive\x12+\n" +
	"\x04kind\x18\x06 \x01(\x0e2\x17.sqld.v1.config.SqlKindR\x04kindB\b\n" +
	"\x06source\"7\n" +
	"\x0fMigrationSource\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dir\x12\x12\n" +
	"\x04glob\x18\x02 \x01(\tR\x04glob\"\x92\x01\n" +
	"\fPluginSource\x12\x14\n" +
	"\x04wasm\x18\x01 \x01(\tH\x00R\x04wasm\x12\x18\n" +
	"\x06binary\x18\x02 \x01(\tH\x00R\x06binary\x12\x1a\n" +
	"\acommand\x18\x03 \x01(\tH\x00R\acommand\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04argsB\n" +
	"\n" +
	"\blocation\"\x8f\x02\n" +
	"\fPluginConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x06source\x18\x02 \x01(\v2\x1c.sqld.v1.config.PluginSourceR\x06source\x12\x10\n" +
	"\x03out\x18\x03 \x01(\tR\x03out\x12\x18\n" +
	"\aoptions\x18\x04 \x01(\fR\aoptions\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x127\n" +
	"\x03env\x18\x06 \x03(\v2%.sqld.v1.config.PluginConfig.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\x02\n" +
	"\rGlobalOptions\x12%\n" +
	"\x0edefault_schema\x18\x01 \x01(\tR\rdefaultSchema\x12\x1f\n" +
	"\vsearch_path\x18\x02 \x03(\tR\n" +
	"searchPath\x12W\n" +
	"\x0etype_overrides\x18\x03 \x03(\v20.sqld.v1.config.GlobalOptions.TypeOverridesEntryR\rtypeOverrides\x12\x16\n" +
	"\x06strict\x18\x04 \x01(\bR\x06strict\x1a@\n" +
	"\x12TypeOverridesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*L\n" +
	"\aSqlKind\x12\x18\n" +
	"\x14SQL_KIND_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSQL_KIND_SCHEMA\x10\x01\x12\x12\n" +
	"\x0eSQL_KIND_QUERY\x10\x02B;Z9github.com/yaroher/sqld/pkg/proto/sqld/v1/config;configv1b\x06proto3"

var (
	file_sqld_v1_config_config_proto_rawDescOnce sync.Once
	file_sqld_v1_config_config_proto_rawDescData []byte
)

func file_sqld_v1_config_config_proto_rawDescGZIP() []byte {
	file_sqld_v1_config_config_proto_rawDescOnce.Do(func() {
		file_sqld_v1_config_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sqld_v1_config_config_proto_rawDesc), len(file_sqld_v1_config_config_proto_rawDesc)))
	})
	return file_sqld_v1_config_config_proto_rawDescData
}

var file_sqld_v1_config_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sqld_v1_config_config_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sqld_v1_config_config_proto_goTypes = []any{
	(SqlKind)(0),            // 0: sqld.v1.config.SqlKind
	(*Config)(nil),          // 1: sqld.v1.config.Config
	(*SqlSource)(nil),       // 2: sqld.v1.config.SqlSource
	(*MigrationSource)(nil), // 3: sqld.v1.config.MigrationSource
	(*PluginSource)(nil),    // 4: sqld.v1.config.PluginSource
	(*PluginConfig)(nil),    // 5: sqld.v1.config.PluginConfig
	(*GlobalOptions)(nil),   // 6: sqld.v1.config.GlobalOptions
	nil,                     // 7: sqld.v1.config.PluginConfig.EnvEntry
	nil,                     // 8: sqld.v1.config.GlobalOptions.TypeOverridesEntry
	(ir.Engine)(0),          // 9: sqld.v1.ir.Engine
}
var file_sqld_v1_config_config_proto_depIdxs = []int32{
	9, // 0: sqld.v1.config.Config.engine:type_name -> sqld.v1.ir.Engine
	2, // 1: sqld.v1.config.Config.sql:type_name -> sqld.v1.config.SqlSource
	3, // 2: sqld.v1.config.Config.migrations:type_name -> sqld.v1.config.MigrationSource
	5, // 3: sqld.v1.config.Config.plugins:type_name -> sqld.v1.config.PluginConfig
	6, // 4: sqld.v1.config.Config.options:type_name -> sqld.v1.config.GlobalOptions
	0, // 5: sqld.v1.config.SqlSource.kind:type_name -> sqld.v1.config.SqlKind
	4, // 6: sqld.v1.config.PluginConfig.source:type_name -> sqld.v1.config.PluginSource
	7, // 7: sqld.v1.config.PluginConfig.env:type_name -> sqld.v1.config.PluginConfig.EnvEntry
	8, // 8: sqld.v1.config.GlobalOptions.type_overrides:type_name -> sqld.v1.config.GlobalOptions.TypeOverridesEntry
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_sqld_v1_config_config_proto_init() }
func file_sqld_v1_config_config_proto_init() {
	if File_sqld_v1_config_config_proto != nil {
		return
	}
	file_sqld_v1_config_config_proto_msgTypes[1].OneofWrappers = []any{
		(*SqlSource_File)(nil),
		(*SqlSource_Dir)(nil),
		(*SqlSource_Inline)(nil),
	}
	file_sqld_v1_config_config_proto_msgTypes[3].OneofWrappers = []any{
		(*PluginSource_Wasm)(nil),
		(*PluginSource_Binary)(nil),
		(*PluginSource_Command)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sqld_v1_config_config_proto_rawDesc), len(file_sqld_v1_config_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sqld_v1_config_config_proto_goTypes,
		DependencyIndexes: file_sqld_v1_config_config_proto_depIdxs,
		EnumInfos:         file_sqld_v1_config_config_proto_enumTypes,
		MessageInfos:      file_sqld_v1_config_config_proto_msgTypes,
	}.Build()
	File_sqld_v1_config_config_proto = out.File
	file_sqld_v1_config_config_proto_goTypes = nil
	file_sqld_v1_config_config_proto_depIdxs = nil
}
