// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: sqld/v1/plugin/annotation.proto

package pluginv1

import (
	ir "github.com/gopherex/sqld/pkg/proto/sqld/v1/ir"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AnnotationForm is the shape of an annotation's value part.
type AnnotationForm int32

const (
	AnnotationForm_ANNOTATION_FORM_UNSPECIFIED AnnotationForm = 0
	AnnotationForm_ANNOTATION_FORM_FLAG        AnnotationForm = 1 // presence only: `@deprecated`
	AnnotationForm_ANNOTATION_FORM_SCALAR      AnnotationForm = 2 // one typed value: `@name GetUser`, `@ttl 30s`
	AnnotationForm_ANNOTATION_FORM_POSITIONAL  AnnotationForm = 3 // ordered fields: `@fk users id`
	AnnotationForm_ANNOTATION_FORM_KEYED       AnnotationForm = 4 // key=value pairs: `@cache ttl=30s region=eu`
	AnnotationForm_ANNOTATION_FORM_LIST        AnnotationForm = 5 // delimited list: `@index a,b,c`
	AnnotationForm_ANNOTATION_FORM_FREEFORM    AnnotationForm = 6 // remainder captured raw: `@doc any text`
)

// Enum value maps for AnnotationForm.
var (
	AnnotationForm_name = map[int32]string{
		0: "ANNOTATION_FORM_UNSPECIFIED",
		1: "ANNOTATION_FORM_FLAG",
		2: "ANNOTATION_FORM_SCALAR",
		3: "ANNOTATION_FORM_POSITIONAL",
		4: "ANNOTATION_FORM_KEYED",
		5: "ANNOTATION_FORM_LIST",
		6: "ANNOTATION_FORM_FREEFORM",
	}
	AnnotationForm_value = map[string]int32{
		"ANNOTATION_FORM_UNSPECIFIED": 0,
		"ANNOTATION_FORM_FLAG":        1,
		"ANNOTATION_FORM_SCALAR":      2,
		"ANNOTATION_FORM_POSITIONAL":  3,
		"ANNOTATION_FORM_KEYED":       4,
		"ANNOTATION_FORM_LIST":        5,
		"ANNOTATION_FORM_FREEFORM":    6,
	}
)

func (x AnnotationForm) Enum() *AnnotationForm {
	p := new(AnnotationForm)
	*p = x
	return p
}

func (x AnnotationForm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnnotationForm) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_plugin_annotation_proto_enumTypes[0].Descriptor()
}

func (AnnotationForm) Type() protoreflect.EnumType {
	return &file_sqld_v1_plugin_annotation_proto_enumTypes[0]
}

func (x AnnotationForm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnnotationForm.Descriptor instead.
func (AnnotationForm) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_plugin_annotation_proto_rawDescGZIP(), []int{0}
}

type AnnotationCardinality int32

const (
	AnnotationCardinality_ANNOTATION_CARDINALITY_UNSPECIFIED AnnotationCardinality = 0
	AnnotationCardinality_ANNOTATION_CARDINALITY_SINGLE      AnnotationCardinality = 1 // at most one per target
	AnnotationCardinality_ANNOTATION_CARDINALITY_REPEATED    AnnotationCardinality = 2 // may appear multiple times
)

// Enum value maps for AnnotationCardinality.
var (
	AnnotationCardinality_name = map[int32]string{
		0: "ANNOTATION_CARDINALITY_UNSPECIFIED",
		1: "ANNOTATION_CARDINALITY_SINGLE",
		2: "ANNOTATION_CARDINALITY_REPEATED",
	}
	AnnotationCardinality_value = map[string]int32{
		"ANNOTATION_CARDINALITY_UNSPECIFIED": 0,
		"ANNOTATION_CARDINALITY_SINGLE":      1,
		"ANNOTATION_CARDINALITY_REPEATED":    2,
	}
)

func (x AnnotationCardinality) Enum() *AnnotationCardinality {
	p := new(AnnotationCardinality)
	*p = x
	return p
}

func (x AnnotationCardinality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnnotationCardinality) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_plugin_annotation_proto_enumTypes[1].Descriptor()
}

func (AnnotationCardinality) Type() protoreflect.EnumType {
	return &file_sqld_v1_plugin_annotation_proto_enumTypes[1]
}

func (x AnnotationCardinality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnnotationCardinality.Descriptor instead.
func (AnnotationCardinality) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_plugin_annotation_proto_rawDescGZIP(), []int{1}
}

// CommentPlacement constrains where the annotation may appear.
type CommentPlacement int32

const (
	CommentPlacement_COMMENT_PLACEMENT_UNSPECIFIED CommentPlacement = 0
	CommentPlacement_COMMENT_PLACEMENT_LEADING     CommentPlacement = 1 // comment block immediately before object
	CommentPlacement_COMMENT_PLACEMENT_TRAILING    CommentPlacement = 2 // inline/trailing comment (e.g. on a column)
	CommentPlacement_COMMENT_PLACEMENT_COMMENT_ON  CommentPlacement = 3 // inside COMMENT ON ... IS '...'
	CommentPlacement_COMMENT_PLACEMENT_ANY         CommentPlacement = 4
)

// Enum value maps for CommentPlacement.
var (
	CommentPlacement_name = map[int32]string{
		0: "COMMENT_PLACEMENT_UNSPECIFIED",
		1: "COMMENT_PLACEMENT_LEADING",
		2: "COMMENT_PLACEMENT_TRAILING",
		3: "COMMENT_PLACEMENT_COMMENT_ON",
		4: "COMMENT_PLACEMENT_ANY",
	}
	CommentPlacement_value = map[string]int32{
		"COMMENT_PLACEMENT_UNSPECIFIED": 0,
		"COMMENT_PLACEMENT_LEADING":     1,
		"COMMENT_PLACEMENT_TRAILING":    2,
		"COMMENT_PLACEMENT_COMMENT_ON":  3,
		"COMMENT_PLACEMENT_ANY":         4,
	}
)

func (x CommentPlacement) Enum() *CommentPlacement {
	p := new(CommentPlacement)
	*p = x
	return p
}

func (x CommentPlacement) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommentPlacement) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_plugin_annotation_proto_enumTypes[2].Descriptor()
}

func (CommentPlacement) Type() protoreflect.EnumType {
	return &file_sqld_v1_plugin_annotation_proto_enumTypes[2]
}

func (x CommentPlacement) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommentPlacement.Descriptor instead.
func (CommentPlacement) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_plugin_annotation_proto_rawDescGZIP(), []int{2}
}

// FieldSpec describes one field the host should extract (a positional slot or a
// named key).
type FieldSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                    // key name / positional label
	Type          ir.AnnotationArgType   `protobuf:"varint,2,opt,name=type,proto3,enum=sqld.v1.ir.AnnotationArgType" json:"type,omitempty"` // how to coerce the token
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	EnumValues    []string               `protobuf:"bytes,4,rep,name=enum_values,json=enumValues,proto3" json:"enum_values,omitempty"` // allowed values when type == ENUM
	Default       string                 `protobuf:"bytes,5,opt,name=default,proto3" json:"default,omitempty"`                         // raw default when omitted
	Variadic      bool                   `protobuf:"varint,6,opt,name=variadic,proto3" json:"variadic,omitempty"`                      // last positional captures remainder
	Doc           string                 `protobuf:"bytes,7,opt,name=doc,proto3" json:"doc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldSpec) Reset() {
	*x = FieldSpec{}
	mi := &file_sqld_v1_plugin_annotation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldSpec) ProtoMessage() {}

func (x *FieldSpec) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_plugin_annotation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldSpec.ProtoReflect.Descriptor instead.
func (*FieldSpec) Descriptor() ([]byte, []int) {
	return file_sqld_v1_plugin_annotation_proto_rawDescGZIP(), []int{0}
}

func (x *FieldSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldSpec) GetType() ir.AnnotationArgType {
	if x != nil {
		return x.Type
	}
	return ir.AnnotationArgType(0)
}

func (x *FieldSpec) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *FieldSpec) GetEnumValues() []string {
	if x != nil {
		return x.EnumValues
	}
	return nil
}

func (x *FieldSpec) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *FieldSpec) GetVariadic() bool {
	if x != nil {
		return x.Variadic
	}
	return false
}

func (x *FieldSpec) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

// AnnotationValueSpec tells the host how to parse the value part of an
// annotation into sqld.v1.ir.AnnotationArg values.
type AnnotationValueSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Form  AnnotationForm         `protobuf:"varint,1,opt,name=form,proto3,enum=sqld.v1.plugin.AnnotationForm" json:"form,omitempty"`
	// POSITIONAL / KEYED: the expected fields. For KEYED, `name` is the key; for
	// POSITIONAL, order matters and `name` labels the produced arg.
	Fields []*FieldSpec `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	// SCALAR: the single value's type.
	ScalarType ir.AnnotationArgType `protobuf:"varint,3,opt,name=scalar_type,json=scalarType,proto3,enum=sqld.v1.ir.AnnotationArgType" json:"scalar_type,omitempty"`
	// LIST: the element type (its `name` is ignored).
	Element *FieldSpec `protobuf:"bytes,4,opt,name=element,proto3" json:"element,omitempty"`
	// Separators (sensible defaults applied by the host when empty).
	ItemSeparator string `protobuf:"bytes,5,opt,name=item_separator,json=itemSeparator,proto3" json:"item_separator,omitempty"` // LIST items; default ","
	PairSeparator string `protobuf:"bytes,6,opt,name=pair_separator,json=pairSeparator,proto3" json:"pair_separator,omitempty"` // KEYED pairs; default whitespace
	KvSeparator   string `protobuf:"bytes,7,opt,name=kv_separator,json=kvSeparator,proto3" json:"kv_separator,omitempty"`       // KEYED key/value; default "="
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotationValueSpec) Reset() {
	*x = AnnotationValueSpec{}
	mi := &file_sqld_v1_plugin_annotation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotationValueSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotationValueSpec) ProtoMessage() {}

func (x *AnnotationValueSpec) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_plugin_annotation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotationValueSpec.ProtoReflect.Descriptor instead.
func (*AnnotationValueSpec) Descriptor() ([]byte, []int) {
	return file_sqld_v1_plugin_annotation_proto_rawDescGZIP(), []int{1}
}

func (x *AnnotationValueSpec) GetForm() AnnotationForm {
	if x != nil {
		return x.Form
	}
	return AnnotationForm_ANNOTATION_FORM_UNSPECIFIED
}

func (x *AnnotationValueSpec) GetFields() []*FieldSpec {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *AnnotationValueSpec) GetScalarType() ir.AnnotationArgType {
	if x != nil {
		return x.ScalarType
	}
	return ir.AnnotationArgType(0)
}

func (x *AnnotationValueSpec) GetElement() *FieldSpec {
	if x != nil {
		return x.Element
	}
	return nil
}

func (x *AnnotationValueSpec) GetItemSeparator() string {
	if x != nil {
		return x.ItemSeparator
	}
	return ""
}

func (x *AnnotationValueSpec) GetPairSeparator() string {
	if x != nil {
		return x.PairSeparator
	}
	return ""
}

func (x *AnnotationValueSpec) GetKvSeparator() string {
	if x != nil {
		return x.KvSeparator
	}
	return ""
}

// AnnotationDef declares one annotation the plugin understands.
type AnnotationDef struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Name          string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // e.g. "name", "cache"
	Aliases       []string                  `protobuf:"bytes,2,rep,name=aliases,proto3" json:"aliases,omitempty"` // alternate spellings
	Doc           string                    `protobuf:"bytes,3,opt,name=doc,proto3" json:"doc,omitempty"`
	Targets       []ir.AnnotationTargetKind `protobuf:"varint,4,rep,packed,name=targets,proto3,enum=sqld.v1.ir.AnnotationTargetKind" json:"targets,omitempty"` // where it may attach
	Cardinality   AnnotationCardinality     `protobuf:"varint,5,opt,name=cardinality,proto3,enum=sqld.v1.plugin.AnnotationCardinality" json:"cardinality,omitempty"`
	Placement     CommentPlacement          `protobuf:"varint,6,opt,name=placement,proto3,enum=sqld.v1.plugin.CommentPlacement" json:"placement,omitempty"`
	Required      bool                      `protobuf:"varint,7,opt,name=required,proto3" json:"required,omitempty"` // must be present on target
	Value         *AnnotationValueSpec      `protobuf:"bytes,8,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotationDef) Reset() {
	*x = AnnotationDef{}
	mi := &file_sqld_v1_plugin_annotation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotationDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotationDef) ProtoMessage() {}

func (x *AnnotationDef) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_plugin_annotation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotationDef.ProtoReflect.Descriptor instead.
func (*AnnotationDef) Descriptor() ([]byte, []int) {
	return file_sqld_v1_plugin_annotation_proto_rawDescGZIP(), []int{2}
}

func (x *AnnotationDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnnotationDef) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *AnnotationDef) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

func (x *AnnotationDef) GetTargets() []ir.AnnotationTargetKind {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *AnnotationDef) GetCardinality() AnnotationCardinality {
	if x != nil {
		return x.Cardinality
	}
	return AnnotationCardinality_ANNOTATION_CARDINALITY_UNSPECIFIED
}

func (x *AnnotationDef) GetPlacement() CommentPlacement {
	if x != nil {
		return x.Placement
	}
	return CommentPlacement_COMMENT_PLACEMENT_UNSPECIFIED
}

func (x *AnnotationDef) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *AnnotationDef) GetValue() *AnnotationValueSpec {
	if x != nil {
		return x.Value
	}
	return nil
}

// AnnotationSchema is the complete grammar a plugin declares. Returned in
// GetInfoResponse so the host can parse comments before calling Generate.
type AnnotationSchema struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Sigil           string                 `protobuf:"bytes,1,opt,name=sigil,proto3" json:"sigil,omitempty"`                                             // marker before the name, e.g. "@"; empty = bare key
	CaseInsensitive bool                   `protobuf:"varint,2,opt,name=case_insensitive,json=caseInsensitive,proto3" json:"case_insensitive,omitempty"` // match names ignoring case
	CommentStyles   []string               `protobuf:"bytes,3,rep,name=comment_styles,json=commentStyles,proto3" json:"comment_styles,omitempty"`        // comment syntaxes to scan: "--", "/* */", "#"
	Annotations     []*AnnotationDef       `protobuf:"bytes,4,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnnotationSchema) Reset() {
	*x = AnnotationSchema{}
	mi := &file_sqld_v1_plugin_annotation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotationSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotationSchema) ProtoMessage() {}

func (x *AnnotationSchema) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_plugin_annotation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotationSchema.ProtoReflect.Descriptor instead.
func (*AnnotationSchema) Descriptor() ([]byte, []int) {
	return file_sqld_v1_plugin_annotation_proto_rawDescGZIP(), []int{3}
}

func (x *AnnotationSchema) GetSigil() string {
	if x != nil {
		return x.Sigil
	}
	return ""
}

func (x *AnnotationSchema) GetCaseInsensitive() bool {
	if x != nil {
		return x.CaseInsensitive
	}
	return false
}

func (x *AnnotationSchema) GetCommentStyles() []string {
	if x != nil {
		return x.CommentStyles
	}
	return nil
}

func (x *AnnotationSchema) GetAnnotations() []*AnnotationDef {
	if x != nil {
		return x.Annotations
	}
	return nil
}

var File_sqld_v1_plugin_annotation_proto protoreflect.FileDescriptor

const file_sqld_v1_plugin_annotation_proto_rawDesc = "" +
	"\n" +
	"\x1fsqld/v1/plugin/annotation.proto\x12\x0esqld.v1.plugin\x1a\x17sqld/v1/ir/common.proto\"\xd7\x01\n" +
	"\tFieldSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.sqld.v1.ir.AnnotationArgTypeR\x04type\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12\x1f\n" +
	"\venum_values\x18\x04 \x03(\tR\n" +
	"enumValues\x12\x18\n" +
	"\adefault\x18\x05 \x01(\tR\adefault\x12\x1a\n" +
	"\bvariadic\x18\x06 \x01(\bR\bvariadic\x12\x10\n" +
	"\x03doc\x18\a \x01(\tR\x03doc\"\xe2\x02\n" +
	"\x13AnnotationValueSpec\x122\n" +
	"\x04form\x18\x01 \x01(\x0e2\x1e.sqld.v1.plugin.AnnotationFormR\x04form\x121\n" +
	"\x06fields\x18\x02 \x03(\v2\x19.sqld.v1.plugin.FieldSpecR\x06fields\x12>\n" +
	"\vscalar_type\x18\x03 \x01(\x0e2\x1d.sqld.v1.ir.AnnotationArgTypeR\n" +
	"scalarType\x123\n" +
	"\aelement\x18\x04 \x01(\v2\x19.sqld.v1.plugin.FieldSpecR\aelement\x12%\n" +
	"\x0eitem_separator\x18\x05 \x01(\tR\ritemSeparator\x12%\n" +
	"\x0epair_separator\x18\x06 \x01(\tR\rpairSeparator\x12!\n" +
	"\fkv_separator\x18\a \x01(\tR\vkvSeparator\"\xeb\x02\n" +
	"\rAnnotationDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaliases\x18\x02 \x03(\tR\aaliases\x12\x10\n" +
	"\x03doc\x18\x03 \x01(\tR\x03doc\x12:\n" +
	"\atargets\x18\x04 \x03(\x0e2 .sqld.v1.ir.AnnotationTargetKindR\atargets\x12G\n" +
	"\vcardinality\x18\x05 \x01(\x0e2%.sqld.v1.plugin.AnnotationCardinalityR\vcardinality\x12>\n" +
	"\tplacement\x18\x06 \x01(\x0e2 .sqld.v1.plugin.CommentPlacementR\tplacement\x12\x1a\n" +
	"\brequired\x18\a \x01(\bR\brequired\x129\n" +
	"\x05value\x18\b \x01(\v2#.sqld.v1.plugin.AnnotationValueSpecR\x05value\"\xbb\x01\n" +
	"\x10AnnotationSchema\x12\x14\n" +
	"\x05sigil\x18\x01 \x01(\tR\x05sigil\x12)\n" +
	"\x10case_insensitive\x18\x02 \x01(\bR\x0fcaseInsensitive\x12%\n" +
	"\x0ecomment_styles\x18\x03 \x03(\tR\rcommentStyles\x12?\n" +
	"\vannotations\x18\x04 \x03(\v2\x1d.sqld.v1.plugin.AnnotationDefR\vannotations*\xda\x01\n" +
	"\x0eAnnotationForm\x12\x1f\n" +
	"\x1bANNOTATION_FORM_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ANNOTATION_FORM_FLAG\x10\x01\x12\x1a\n" +
	"\x16ANNOTATION_FORM_SCALAR\x10\x02\x12\x1e\n" +
	"\x1aANNOTATION_FORM_POSITIONAL\x10\x03\x12\x19\n" +
	"\x15ANNOTATION_FORM_KEYED\x10\x04\x12\x18\n" +
	"\x14ANNOTATION_FORM_LIST\x10\x05\x12\x1c\n" +
	"\x18ANNOTATION_FORM_FREEFORM\x10\x06*\x87\x01\n" +
	"\x15AnnotationCardinality\x12&\n" +
	"\"ANNOTATION_CARDINALITY_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dANNOTATION_CARDINALITY_SINGLE\x10\x01\x12#\n" +
	"\x1fANNOTATION_CARDINALITY_REPEATED\x10\x02*\xb1\x01\n" +
	"\x10CommentPlacement\x12!\n" +
	"\x1dCOMMENT_PLACEMENT_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19COMMENT_PLACEMENT_LEADING\x10\x01\x12\x1e\n" +
	"\x1aCOMMENT_PLACEMENT_TRAILING\x10\x02\x12 \n" +
	"\x1cCOMMENT_PLACEMENT_COMMENT_ON\x10\x03\x12\x19\n" +
	"\x15COMMENT_PLACEMENT_ANY\x10\x04B<Z:github.com/gopherex/sqld/pkg/proto/sqld/v1/plugin;pluginv1b\x06proto3"

var (
	file_sqld_v1_plugin_annotation_proto_rawDescOnce sync.Once
	file_sqld_v1_plugin_annotation_proto_rawDescData []byte
)

func file_sqld_v1_plugin_annotation_proto_rawDescGZIP() []byte {
	file_sqld_v1_plugin_annotation_proto_rawDescOnce.Do(func() {
		file_sqld_v1_plugin_annotation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sqld_v1_plugin_annotation_proto_rawDesc), len(file_sqld_v1_plugin_annotation_proto_rawDesc)))
	})
	return file_sqld_v1_plugin_annotation_proto_rawDescData
}

var file_sqld_v1_plugin_annotation_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_sqld_v1_plugin_annotation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sqld_v1_plugin_annotation_proto_goTypes = []any{
	(AnnotationForm)(0),          // 0: sqld.v1.plugin.AnnotationForm
	(AnnotationCardinality)(0),   // 1: sqld.v1.plugin.AnnotationCardinality
	(CommentPlacement)(0),        // 2: sqld.v1.plugin.CommentPlacement
	(*FieldSpec)(nil),            // 3: sqld.v1.plugin.FieldSpec
	(*AnnotationValueSpec)(nil),  // 4: sqld.v1.plugin.AnnotationValueSpec
	(*AnnotationDef)(nil),        // 5: sqld.v1.plugin.AnnotationDef
	(*AnnotationSchema)(nil),     // 6: sqld.v1.plugin.AnnotationSchema
	(ir.AnnotationArgType)(0),    // 7: sqld.v1.ir.AnnotationArgType
	(ir.AnnotationTargetKind)(0), // 8: sqld.v1.ir.AnnotationTargetKind
}
var file_sqld_v1_plugin_annotation_proto_depIdxs = []int32{
	7,  // 0: sqld.v1.plugin.FieldSpec.type:type_name -> sqld.v1.ir.AnnotationArgType
	0,  // 1: sqld.v1.plugin.AnnotationValueSpec.form:type_name -> sqld.v1.plugin.AnnotationForm
	3,  // 2: sqld.v1.plugin.AnnotationValueSpec.fields:type_name -> sqld.v1.plugin.FieldSpec
	7,  // 3: sqld.v1.plugin.AnnotationValueSpec.scalar_type:type_name -> sqld.v1.ir.AnnotationArgType
	3,  // 4: sqld.v1.plugin.AnnotationValueSpec.element:type_name -> sqld.v1.plugin.FieldSpec
	8,  // 5: sqld.v1.plugin.AnnotationDef.targets:type_name -> sqld.v1.ir.AnnotationTargetKind
	1,  // 6: sqld.v1.plugin.AnnotationDef.cardinality:type_name -> sqld.v1.plugin.AnnotationCardinality
	2,  // 7: sqld.v1.plugin.AnnotationDef.placement:type_name -> sqld.v1.plugin.CommentPlacement
	4,  // 8: sqld.v1.plugin.AnnotationDef.value:type_name -> sqld.v1.plugin.AnnotationValueSpec
	5,  // 9: sqld.v1.plugin.AnnotationSchema.annotations:type_name -> sqld.v1.plugin.AnnotationDef
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_sqld_v1_plugin_annotation_proto_init() }
func file_sqld_v1_plugin_annotation_proto_init() {
	if File_sqld_v1_plugin_annotation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sqld_v1_plugin_annotation_proto_rawDesc), len(file_sqld_v1_plugin_annotation_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sqld_v1_plugin_annotation_proto_goTypes,
		DependencyIndexes: file_sqld_v1_plugin_annotation_proto_depIdxs,
		EnumInfos:         file_sqld_v1_plugin_annotation_proto_enumTypes,
		MessageInfos:      file_sqld_v1_plugin_annotation_proto_msgTypes,
	}.Build()
	File_sqld_v1_plugin_annotation_proto = out.File
	file_sqld_v1_plugin_annotation_proto_goTypes = nil
	file_sqld_v1_plugin_annotation_proto_depIdxs = nil
}
