// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: sqld/v1/plugin/plugin.proto

package pluginv1

import (
	ir "github.com/gopherex/sqld/pkg/proto/sqld/v1/ir"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiagnosticSeverity int32

const (
	DiagnosticSeverity_DIAGNOSTIC_SEVERITY_UNSPECIFIED DiagnosticSeverity = 0
	DiagnosticSeverity_DIAGNOSTIC_SEVERITY_INFO        DiagnosticSeverity = 1
	DiagnosticSeverity_DIAGNOSTIC_SEVERITY_WARNING     DiagnosticSeverity = 2
	DiagnosticSeverity_DIAGNOSTIC_SEVERITY_ERROR       DiagnosticSeverity = 3 // a single ERROR fails the run
)

// Enum value maps for DiagnosticSeverity.
var (
	DiagnosticSeverity_name = map[int32]string{
		0: "DIAGNOSTIC_SEVERITY_UNSPECIFIED",
		1: "DIAGNOSTIC_SEVERITY_INFO",
		2: "DIAGNOSTIC_SEVERITY_WARNING",
		3: "DIAGNOSTIC_SEVERITY_ERROR",
	}
	DiagnosticSeverity_value = map[string]int32{
		"DIAGNOSTIC_SEVERITY_UNSPECIFIED": 0,
		"DIAGNOSTIC_SEVERITY_INFO":        1,
		"DIAGNOSTIC_SEVERITY_WARNING":     2,
		"DIAGNOSTIC_SEVERITY_ERROR":       3,
	}
)

func (x DiagnosticSeverity) Enum() *DiagnosticSeverity {
	p := new(DiagnosticSeverity)
	*p = x
	return p
}

func (x DiagnosticSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiagnosticSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_plugin_plugin_proto_enumTypes[0].Descriptor()
}

func (DiagnosticSeverity) Type() protoreflect.EnumType {
	return &file_sqld_v1_plugin_plugin_proto_enumTypes[0]
}

func (x DiagnosticSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiagnosticSeverity.Descriptor instead.
func (DiagnosticSeverity) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_plugin_plugin_proto_rawDescGZIP(), []int{0}
}

// QueryCommand is the result-shape annotation (sqlc-style `:one`, `:many`...).
type QueryCommand int32

const (
	QueryCommand_QUERY_COMMAND_UNSPECIFIED QueryCommand = 0
	QueryCommand_QUERY_COMMAND_ONE         QueryCommand = 1 // :one
	QueryCommand_QUERY_COMMAND_MANY        QueryCommand = 2 // :many
	QueryCommand_QUERY_COMMAND_EXEC        QueryCommand = 3 // :exec
	QueryCommand_QUERY_COMMAND_EXEC_ROWS   QueryCommand = 4 // :execrows (affected row count)
	QueryCommand_QUERY_COMMAND_EXEC_RESULT QueryCommand = 5 // :execresult
	QueryCommand_QUERY_COMMAND_EXEC_LASTID QueryCommand = 6 // :execlastid
	QueryCommand_QUERY_COMMAND_BATCH_EXEC  QueryCommand = 7 // :batchexec
	QueryCommand_QUERY_COMMAND_COPY_FROM   QueryCommand = 8 // :copyfrom
)

// Enum value maps for QueryCommand.
var (
	QueryCommand_name = map[int32]string{
		0: "QUERY_COMMAND_UNSPECIFIED",
		1: "QUERY_COMMAND_ONE",
		2: "QUERY_COMMAND_MANY",
		3: "QUERY_COMMAND_EXEC",
		4: "QUERY_COMMAND_EXEC_ROWS",
		5: "QUERY_COMMAND_EXEC_RESULT",
		6: "QUERY_COMMAND_EXEC_LASTID",
		7: "QUERY_COMMAND_BATCH_EXEC",
		8: "QUERY_COMMAND_COPY_FROM",
	}
	QueryCommand_value = map[string]int32{
		"QUERY_COMMAND_UNSPECIFIED": 0,
		"QUERY_COMMAND_ONE":         1,
		"QUERY_COMMAND_MANY":        2,
		"QUERY_COMMAND_EXEC":        3,
		"QUERY_COMMAND_EXEC_ROWS":   4,
		"QUERY_COMMAND_EXEC_RESULT": 5,
		"QUERY_COMMAND_EXEC_LASTID": 6,
		"QUERY_COMMAND_BATCH_EXEC":  7,
		"QUERY_COMMAND_COPY_FROM":   8,
	}
)

func (x QueryCommand) Enum() *QueryCommand {
	p := new(QueryCommand)
	*p = x
	return p
}

func (x QueryCommand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryCommand) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_plugin_plugin_proto_enumTypes[1].Descriptor()
}

func (QueryCommand) Type() protoreflect.EnumType {
	return &file_sqld_v1_plugin_plugin_proto_enumTypes[1]
}

func (x QueryCommand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryCommand.Descriptor instead.
func (QueryCommand) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_plugin_plugin_proto_rawDescGZIP(), []int{1}
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_sqld_v1_plugin_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_plugin_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_sqld_v1_plugin_plugin_proto_rawDescGZIP(), []int{0}
}

type GetInfoResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	SupportedEngines []ir.Engine            `protobuf:"varint,3,rep,packed,name=supported_engines,json=supportedEngines,proto3,enum=sqld.v1.ir.Engine" json:"supported_engines,omitempty"`
	// Human/tooling-readable description of accepted options (e.g. a JSON schema
	// or a proto descriptor name). Informational; options on the wire are bytes.
	OptionsSchema string   `protobuf:"bytes,4,opt,name=options_schema,json=optionsSchema,proto3" json:"options_schema,omitempty"`
	Capabilities  []string `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"` // free-form feature flags
	// Grammar of the SQL-comment annotations this plugin understands. The host
	// parses comments against this and returns sqld.v1.ir.AnnotationValue results.
	AnnotationSchema *AnnotationSchema `protobuf:"bytes,6,opt,name=annotation_schema,json=annotationSchema,proto3" json:"annotation_schema,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_sqld_v1_plugin_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_plugin_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_sqld_v1_plugin_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetInfoResponse) GetSupportedEngines() []ir.Engine {
	if x != nil {
		return x.SupportedEngines
	}
	return nil
}

func (x *GetInfoResponse) GetOptionsSchema() string {
	if x != nil {
		return x.OptionsSchema
	}
	return ""
}

func (x *GetInfoResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *GetInfoResponse) GetAnnotationSchema() *AnnotationSchema {
	if x != nil {
		return x.AnnotationSchema
	}
	return nil
}

// PluginContext carries host-side run information.
type PluginContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostVersion   string                 `protobuf:"bytes,1,opt,name=host_version,json=hostVersion,proto3" json:"host_version,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,2,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Engine        ir.Engine              `protobuf:"varint,3,opt,name=engine,proto3,enum=sqld.v1.ir.Engine" json:"engine,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginContext) Reset() {
	*x = PluginContext{}
	mi := &file_sqld_v1_plugin_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginContext) ProtoMessage() {}

func (x *PluginContext) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_plugin_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginContext.ProtoReflect.Descriptor instead.
func (*PluginContext) Descriptor() ([]byte, []int) {
	return file_sqld_v1_plugin_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PluginContext) GetHostVersion() string {
	if x != nil {
		return x.HostVersion
	}
	return ""
}

func (x *PluginContext) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *PluginContext) GetEngine() ir.Engine {
	if x != nil {
		return x.Engine
	}
	return ir.Engine(0)
}

func (x *PluginContext) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type GenerateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema IR derived from DDL and applied migrations.
	Catalog *ir.Catalog `protobuf:"bytes,1,opt,name=catalog,proto3" json:"catalog,omitempty"`
	// Named DML queries parsed from query sources.
	Queries []*Query `protobuf:"bytes,2,rep,name=queries,proto3" json:"queries,omitempty"`
	// Ordered migrations (raw + parsed), for migration-aware generators.
	Migrations []*Migration `protobuf:"bytes,3,rep,name=migrations,proto3" json:"migrations,omitempty"`
	// Plugin-specific settings, opaque to the host. The plugin decodes these
	// bytes into its own options message (see PluginConfig.options).
	Options []byte `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	// Output directory the plugin should target (host resolves/cleans it).
	OutDir  string         `protobuf:"bytes,5,opt,name=out_dir,json=outDir,proto3" json:"out_dir,omitempty"`
	Context *PluginContext `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	// All annotations parsed from the SQL sources, per the plugin's declared
	// AnnotationSchema. A flat, global list keyed by target; also mirrored onto
	// each object's Metadata.annotations.
	Annotations   []*ir.AnnotationValue `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_sqld_v1_plugin_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_plugin_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_sqld_v1_plugin_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateRequest) GetCatalog() *ir.Catalog {
	if x != nil {
		return x.Catalog
	}
	return nil
}

func (x *GenerateRequest) GetQueries() []*Query {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *GenerateRequest) GetMigrations() []*Migration {
	if x != nil {
		return x.Migrations
	}
	return nil
}

func (x *GenerateRequest) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *GenerateRequest) GetOutDir() string {
	if x != nil {
		return x.OutDir
	}
	return ""
}

func (x *GenerateRequest) GetContext() *PluginContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GenerateRequest) GetAnnotations() []*ir.AnnotationValue {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type GenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*GeneratedFile       `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,2,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_sqld_v1_plugin_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_plugin_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_sqld_v1_plugin_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateResponse) GetFiles() []*GeneratedFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *GenerateResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type GeneratedFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // relative to GenerateRequest.out_dir
	Contents      []byte                 `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
	Executable    bool                   `protobuf:"varint,3,opt,name=executable,proto3" json:"executable,omitempty"` // set the executable bit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratedFile) Reset() {
	*x = GeneratedFile{}
	mi := &file_sqld_v1_plugin_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedFile) ProtoMessage() {}

func (x *GeneratedFile) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_plugin_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedFile.ProtoReflect.Descriptor instead.
func (*GeneratedFile) Descriptor() ([]byte, []int) {
	return file_sqld_v1_plugin_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *GeneratedFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GeneratedFile) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *GeneratedFile) GetExecutable() bool {
	if x != nil {
		return x.Executable
	}
	return false
}

type Diagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      DiagnosticSeverity     `protobuf:"varint,1,opt,name=severity,proto3,enum=sqld.v1.plugin.DiagnosticSeverity" json:"severity,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Source        *ir.SourceSpan         `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"` // where it originated, when known
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`     // stable diagnostic code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_sqld_v1_plugin_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_plugin_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_sqld_v1_plugin_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *Diagnostic) GetSeverity() DiagnosticSeverity {
	if x != nil {
		return x.Severity
	}
	return DiagnosticSeverity_DIAGNOSTIC_SEVERITY_UNSPECIFIED
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Diagnostic) GetSource() *ir.SourceSpan {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Diagnostic) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// QueryParameter is an inferred bind parameter ($1, $2, ...).
type QueryParameter struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Number   uint32                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"` // 1-based position
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`      // named param, when available
	Type     *ir.TypeRef            `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Nullable bool                   `protobuf:"varint,4,opt,name=nullable,proto3" json:"nullable,omitempty"`
	Column   *ir.ObjectRef          `protobuf:"bytes,5,opt,name=column,proto3" json:"column,omitempty"` // originating column, when inferred
	// optional marks a dynamic-query parameter declared with the `@name?` suffix:
	// the WHERE condition using it is included only when the caller supplies it.
	Optional      bool `protobuf:"varint,6,opt,name=optional,proto3" json:"optional,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParameter) Reset() {
	*x = QueryParameter{}
	mi := &file_sqld_v1_plugin_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParameter) ProtoMessage() {}

func (x *QueryParameter) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_plugin_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParameter.ProtoReflect.Descriptor instead.
func (*QueryParameter) Descriptor() ([]byte, []int) {
	return file_sqld_v1_plugin_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *QueryParameter) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *QueryParameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryParameter) GetType() *ir.TypeRef {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *QueryParameter) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *QueryParameter) GetColumn() *ir.ObjectRef {
	if x != nil {
		return x.Column
	}
	return nil
}

func (x *QueryParameter) GetOptional() bool {
	if x != nil {
		return x.Optional
	}
	return false
}

// QueryColumn is an inferred output column of a query.
type QueryColumn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          *ir.TypeRef            `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Nullable      bool                   `protobuf:"varint,3,opt,name=nullable,proto3" json:"nullable,omitempty"`
	IsArray       bool                   `protobuf:"varint,4,opt,name=is_array,json=isArray,proto3" json:"is_array,omitempty"`
	SourceColumn  *ir.ObjectRef          `protobuf:"bytes,5,opt,name=source_column,json=sourceColumn,proto3" json:"source_column,omitempty"` // origin column, when inferred
	TableAlias    string                 `protobuf:"bytes,6,opt,name=table_alias,json=tableAlias,proto3" json:"table_alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryColumn) Reset() {
	*x = QueryColumn{}
	mi := &file_sqld_v1_plugin_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryColumn) ProtoMessage() {}

func (x *QueryColumn) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_plugin_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryColumn.ProtoReflect.Descriptor instead.
func (*QueryColumn) Descriptor() ([]byte, []int) {
	return file_sqld_v1_plugin_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *QueryColumn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryColumn) GetType() *ir.TypeRef {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *QueryColumn) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *QueryColumn) GetIsArray() bool {
	if x != nil {
		return x.IsArray
	}
	return false
}

func (x *QueryColumn) GetSourceColumn() *ir.ObjectRef {
	if x != nil {
		return x.SourceColumn
	}
	return nil
}

func (x *QueryColumn) GetTableAlias() string {
	if x != nil {
		return x.TableAlias
	}
	return ""
}

// Query is a named DML query plus its inferred signature.
type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // from `-- name: Foo :one`
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`   // raw SQL text
	Command       QueryCommand           `protobuf:"varint,3,opt,name=command,proto3,enum=sqld.v1.plugin.QueryCommand" json:"command,omitempty"`
	Ast           *ir.Statement          `protobuf:"bytes,4,opt,name=ast,proto3" json:"ast,omitempty"` // parsed statement IR
	Parameters    []*QueryParameter      `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty"`
	Columns       []*QueryColumn         `protobuf:"bytes,6,rep,name=columns,proto3" json:"columns,omitempty"`
	SourceFile    string                 `protobuf:"bytes,7,opt,name=source_file,json=sourceFile,proto3" json:"source_file,omitempty"`
	Comment       string                 `protobuf:"bytes,8,opt,name=comment,proto3" json:"comment,omitempty"` // leading doc comment, if any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_sqld_v1_plugin_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_plugin_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_sqld_v1_plugin_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *Query) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Query) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *Query) GetCommand() QueryCommand {
	if x != nil {
		return x.Command
	}
	return QueryCommand_QUERY_COMMAND_UNSPECIFIED
}

func (x *Query) GetAst() *ir.Statement {
	if x != nil {
		return x.Ast
	}
	return nil
}

func (x *Query) GetParameters() []*QueryParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Query) GetColumns() []*QueryColumn {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Query) GetSourceFile() string {
	if x != nil {
		return x.SourceFile
	}
	return ""
}

func (x *Query) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// Migration is one ordered migration step, raw and parsed.
type Migration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` // ordering key: "0001", timestamp, ...
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UpSql         string                 `protobuf:"bytes,3,opt,name=up_sql,json=upSql,proto3" json:"up_sql,omitempty"`
	DownSql       string                 `protobuf:"bytes,4,opt,name=down_sql,json=downSql,proto3" json:"down_sql,omitempty"`
	Up            []*ir.Statement        `protobuf:"bytes,5,rep,name=up,proto3" json:"up,omitempty"`     // parsed up statements
	Down          []*ir.Statement        `protobuf:"bytes,6,rep,name=down,proto3" json:"down,omitempty"` // parsed down statements
	SourceFile    string                 `protobuf:"bytes,7,opt,name=source_file,json=sourceFile,proto3" json:"source_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration) Reset() {
	*x = Migration{}
	mi := &file_sqld_v1_plugin_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration) ProtoMessage() {}

func (x *Migration) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_plugin_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration.ProtoReflect.Descriptor instead.
func (*Migration) Descriptor() ([]byte, []int) {
	return file_sqld_v1_plugin_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *Migration) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Migration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Migration) GetUpSql() string {
	if x != nil {
		return x.UpSql
	}
	return ""
}

func (x *Migration) GetDownSql() string {
	if x != nil {
		return x.DownSql
	}
	return ""
}

func (x *Migration) GetUp() []*ir.Statement {
	if x != nil {
		return x.Up
	}
	return nil
}

func (x *Migration) GetDown() []*ir.Statement {
	if x != nil {
		return x.Down
	}
	return nil
}

func (x *Migration) GetSourceFile() string {
	if x != nil {
		return x.SourceFile
	}
	return ""
}

var File_sqld_v1_plugin_plugin_proto protoreflect.FileDescriptor

const file_sqld_v1_plugin_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1bsqld/v1/plugin/plugin.proto\x12\x0esqld.v1.plugin\x1a\x17sqld/v1/ir/common.proto\x1a\x15sqld/v1/ir/type.proto\x1a\x14sqld/v1/ir/dml.proto\x1a\x18sqld/v1/ir/catalog.proto\x1a\x1fsqld/v1/plugin/annotation.proto\"\x10\n" +
	"\x0eGetInfoRequest\"\x9a\x02\n" +
	"\x0fGetInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12?\n" +
	"\x11supported_engines\x18\x03 \x03(\x0e2\x12.sqld.v1.ir.EngineR\x10supportedEngines\x12%\n" +
	"\x0eoptions_schema\x18\x04 \x01(\tR\roptionsSchema\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x12M\n" +
	"\x11annotation_schema\x18\x06 \x01(\v2 .sqld.v1.plugin.AnnotationSchemaR\x10annotationSchema\"\xf1\x01\n" +
	"\rPluginContext\x12!\n" +
	"\fhost_version\x18\x01 \x01(\tR\vhostVersion\x12\x1f\n" +
	"\vworking_dir\x18\x02 \x01(\tR\n" +
	"workingDir\x12*\n" +
	"\x06engine\x18\x03 \x01(\x0e2\x12.sqld.v1.ir.EngineR\x06engine\x128\n" +
	"\x03env\x18\x04 \x03(\v2&.sqld.v1.plugin.PluginContext.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd7\x02\n" +
	"\x0fGenerateRequest\x12-\n" +
	"\acatalog\x18\x01 \x01(\v2\x13.sqld.v1.ir.CatalogR\acatalog\x12/\n" +
	"\aqueries\x18\x02 \x03(\v2\x15.sqld.v1.plugin.QueryR\aqueries\x129\n" +
	"\n" +
	"migrations\x18\x03 \x03(\v2\x19.sqld.v1.plugin.MigrationR\n" +
	"migrations\x12\x18\n" +
	"\aoptions\x18\x04 \x01(\fR\aoptions\x12\x17\n" +
	"\aout_dir\x18\x05 \x01(\tR\x06outDir\x127\n" +
	"\acontext\x18\x06 \x01(\v2\x1d.sqld.v1.plugin.PluginContextR\acontext\x12=\n" +
	"\vannotations\x18\a \x03(\v2\x1b.sqld.v1.ir.AnnotationValueR\vannotations\"\x85\x01\n" +
	"\x10GenerateResponse\x123\n" +
	"\x05files\x18\x01 \x03(\v2\x1d.sqld.v1.plugin.GeneratedFileR\x05files\x12<\n" +
	"\vdiagnostics\x18\x02 \x03(\v2\x1a.sqld.v1.plugin.DiagnosticR\vdiagnostics\"_\n" +
	"\rGeneratedFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\bcontents\x18\x02 \x01(\fR\bcontents\x12\x1e\n" +
	"\n" +
	"executable\x18\x03 \x01(\bR\n" +
	"executable\"\xaa\x01\n" +
	"\n" +
	"Diagnostic\x12>\n" +
	"\bseverity\x18\x01 \x01(\x0e2\".sqld.v1.plugin.DiagnosticSeverityR\bseverity\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x06source\x18\x03 \x01(\v2\x16.sqld.v1.ir.SourceSpanR\x06source\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\"\xcc\x01\n" +
	"\x0eQueryParameter\x12\x16\n" +
	"\x06number\x18\x01 \x01(\rR\x06number\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x04type\x18\x03 \x01(\v2\x13.sqld.v1.ir.TypeRefR\x04type\x12\x1a\n" +
	"\bnullable\x18\x04 \x01(\bR\bnullable\x12-\n" +
	"\x06column\x18\x05 \x01(\v2\x15.sqld.v1.ir.ObjectRefR\x06column\x12\x1a\n" +
	"\boptional\x18\x06 \x01(\bR\boptional\"\xde\x01\n" +
	"\vQueryColumn\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x04type\x18\x02 \x01(\v2\x13.sqld.v1.ir.TypeRefR\x04type\x12\x1a\n" +
	"\bnullable\x18\x03 \x01(\bR\bnullable\x12\x19\n" +
	"\bis_array\x18\x04 \x01(\bR\aisArray\x12:\n" +
	"\rsource_column\x18\x05 \x01(\v2\x15.sqld.v1.ir.ObjectRefR\fsourceColumn\x12\x1f\n" +
	"\vtable_alias\x18\x06 \x01(\tR\n" +
	"tableAlias\"\xc0\x02\n" +
	"\x05Query\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\x126\n" +
	"\acommand\x18\x03 \x01(\x0e2\x1c.sqld.v1.plugin.QueryCommandR\acommand\x12'\n" +
	"\x03ast\x18\x04 \x01(\v2\x15.sqld.v1.ir.StatementR\x03ast\x12>\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2\x1e.sqld.v1.plugin.QueryParameterR\n" +
	"parameters\x125\n" +
	"\acolumns\x18\x06 \x03(\v2\x1b.sqld.v1.plugin.QueryColumnR\acolumns\x12\x1f\n" +
	"\vsource_file\x18\a \x01(\tR\n" +
	"sourceFile\x12\x18\n" +
	"\acomment\x18\b \x01(\tR\acomment\"\xde\x01\n" +
	"\tMigration\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x15\n" +
	"\x06up_sql\x18\x03 \x01(\tR\x05upSql\x12\x19\n" +
	"\bdown_sql\x18\x04 \x01(\tR\adownSql\x12%\n" +
	"\x02up\x18\x05 \x03(\v2\x15.sqld.v1.ir.StatementR\x02up\x12)\n" +
	"\x04down\x18\x06 \x03(\v2\x15.sqld.v1.ir.StatementR\x04down\x12\x1f\n" +
	"\vsource_file\x18\a \x01(\tR\n" +
	"sourceFile*\x97\x01\n" +
	"\x12DiagnosticSeverity\x12#\n" +
	"\x1fDIAGNOSTIC_SEVERITY_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DIAGNOSTIC_SEVERITY_INFO\x10\x01\x12\x1f\n" +
	"\x1bDIAGNOSTIC_SEVERITY_WARNING\x10\x02\x12\x1d\n" +
	"\x19DIAGNOSTIC_SEVERITY_ERROR\x10\x03*\x8a\x02\n" +
	"\fQueryCommand\x12\x1d\n" +
	"\x19QUERY_COMMAND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11QUERY_COMMAND_ONE\x10\x01\x12\x16\n" +
	"\x12QUERY_COMMAND_MANY\x10\x02\x12\x16\n" +
	"\x12QUERY_COMMAND_EXEC\x10\x03\x12\x1b\n" +
	"\x17QUERY_COMMAND_EXEC_ROWS\x10\x04\x12\x1d\n" +
	"\x19QUERY_COMMAND_EXEC_RESULT\x10\x05\x12\x1d\n" +
	"\x19QUERY_COMMAND_EXEC_LASTID\x10\x06\x12\x1c\n" +
	"\x18QUERY_COMMAND_BATCH_EXEC\x10\a\x12\x1b\n" +
	"\x17QUERY_COMMAND_COPY_FROM\x10\b2\xa6\x01\n" +
	"\tGenerator\x12J\n" +
	"\aGetInfo\x12\x1e.sqld.v1.plugin.GetInfoRequest\x1a\x1f.sqld.v1.plugin.GetInfoResponse\x12M\n" +
	"\bGenerate\x12\x1f.sqld.v1.plugin.GenerateRequest\x1a .sqld.v1.plugin.GenerateResponseB<Z:github.com/gopherex/sqld/pkg/proto/sqld/v1/plugin;pluginv1b\x06proto3"

var (
	file_sqld_v1_plugin_plugin_proto_rawDescOnce sync.Once
	file_sqld_v1_plugin_plugin_proto_rawDescData []byte
)

func file_sqld_v1_plugin_plugin_proto_rawDescGZIP() []byte {
	file_sqld_v1_plugin_plugin_proto_rawDescOnce.Do(func() {
		file_sqld_v1_plugin_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sqld_v1_plugin_plugin_proto_rawDesc), len(file_sqld_v1_plugin_plugin_proto_rawDesc)))
	})
	return file_sqld_v1_plugin_plugin_proto_rawDescData
}

var file_sqld_v1_plugin_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sqld_v1_plugin_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_sqld_v1_plugin_plugin_proto_goTypes = []any{
	(DiagnosticSeverity)(0),    // 0: sqld.v1.plugin.DiagnosticSeverity
	(QueryCommand)(0),          // 1: sqld.v1.plugin.QueryCommand
	(*GetInfoRequest)(nil),     // 2: sqld.v1.plugin.GetInfoRequest
	(*GetInfoResponse)(nil),    // 3: sqld.v1.plugin.GetInfoResponse
	(*PluginContext)(nil),      // 4: sqld.v1.plugin.PluginContext
	(*GenerateRequest)(nil),    // 5: sqld.v1.plugin.GenerateRequest
	(*GenerateResponse)(nil),   // 6: sqld.v1.plugin.GenerateResponse
	(*GeneratedFile)(nil),      // 7: sqld.v1.plugin.GeneratedFile
	(*Diagnostic)(nil),         // 8: sqld.v1.plugin.Diagnostic
	(*QueryParameter)(nil),     // 9: sqld.v1.plugin.QueryParameter
	(*QueryColumn)(nil),        // 10: sqld.v1.plugin.QueryColumn
	(*Query)(nil),              // 11: sqld.v1.plugin.Query
	(*Migration)(nil),          // 12: sqld.v1.plugin.Migration
	nil,                        // 13: sqld.v1.plugin.PluginContext.EnvEntry
	(ir.Engine)(0),             // 14: sqld.v1.ir.Engine
	(*AnnotationSchema)(nil),   // 15: sqld.v1.plugin.AnnotationSchema
	(*ir.Catalog)(nil),         // 16: sqld.v1.ir.Catalog
	(*ir.AnnotationValue)(nil), // 17: sqld.v1.ir.AnnotationValue
	(*ir.SourceSpan)(nil),      // 18: sqld.v1.ir.SourceSpan
	(*ir.TypeRef)(nil),         // 19: sqld.v1.ir.TypeRef
	(*ir.ObjectRef)(nil),       // 20: sqld.v1.ir.ObjectRef
	(*ir.Statement)(nil),       // 21: sqld.v1.ir.Statement
}
var file_sqld_v1_plugin_plugin_proto_depIdxs = []int32{
	14, // 0: sqld.v1.plugin.GetInfoResponse.supported_engines:type_name -> sqld.v1.ir.Engine
	15, // 1: sqld.v1.plugin.GetInfoResponse.annotation_schema:type_name -> sqld.v1.plugin.AnnotationSchema
	14, // 2: sqld.v1.plugin.PluginContext.engine:type_name -> sqld.v1.ir.Engine
	13, // 3: sqld.v1.plugin.PluginContext.env:type_name -> sqld.v1.plugin.PluginContext.EnvEntry
	16, // 4: sqld.v1.plugin.GenerateRequest.catalog:type_name -> sqld.v1.ir.Catalog
	11, // 5: sqld.v1.plugin.GenerateRequest.queries:type_name -> sqld.v1.plugin.Query
	12, // 6: sqld.v1.plugin.GenerateRequest.migrations:type_name -> sqld.v1.plugin.Migration
	4,  // 7: sqld.v1.plugin.GenerateRequest.context:type_name -> sqld.v1.plugin.PluginContext
	17, // 8: sqld.v1.plugin.GenerateRequest.annotations:type_name -> sqld.v1.ir.AnnotationValue
	7,  // 9: sqld.v1.plugin.GenerateResponse.files:type_name -> sqld.v1.plugin.GeneratedFile
	8,  // 10: sqld.v1.plugin.GenerateResponse.diagnostics:type_name -> sqld.v1.plugin.Diagnostic
	0,  // 11: sqld.v1.plugin.Diagnostic.severity:type_name -> sqld.v1.plugin.DiagnosticSeverity
	18, // 12: sqld.v1.plugin.Diagnostic.source:type_name -> sqld.v1.ir.SourceSpan
	19, // 13: sqld.v1.plugin.QueryParameter.type:type_name -> sqld.v1.ir.TypeRef
	20, // 14: sqld.v1.plugin.QueryParameter.column:type_name -> sqld.v1.ir.ObjectRef
	19, // 15: sqld.v1.plugin.QueryColumn.type:type_name -> sqld.v1.ir.TypeRef
	20, // 16: sqld.v1.plugin.QueryColumn.source_column:type_name -> sqld.v1.ir.ObjectRef
	1,  // 17: sqld.v1.plugin.Query.command:type_name -> sqld.v1.plugin.QueryCommand
	21, // 18: sqld.v1.plugin.Query.ast:type_name -> sqld.v1.ir.Statement
	9,  // 19: sqld.v1.plugin.Query.parameters:type_name -> sqld.v1.plugin.QueryParameter
	10, // 20: sqld.v1.plugin.Query.columns:type_name -> sqld.v1.plugin.QueryColumn
	21, // 21: sqld.v1.plugin.Migration.up:type_name -> sqld.v1.ir.Statement
	21, // 22: sqld.v1.plugin.Migration.down:type_name -> sqld.v1.ir.Statement
	2,  // 23: sqld.v1.plugin.Generator.GetInfo:input_type -> sqld.v1.plugin.GetInfoRequest
	5,  // 24: sqld.v1.plugin.Generator.Generate:input_type -> sqld.v1.plugin.GenerateRequest
	3,  // 25: sqld.v1.plugin.Generator.GetInfo:output_type -> sqld.v1.plugin.GetInfoResponse
	6,  // 26: sqld.v1.plugin.Generator.Generate:output_type -> sqld.v1.plugin.GenerateResponse
	25, // [25:27] is the sub-list for method output_type
	23, // [23:25] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_sqld_v1_plugin_plugin_proto_init() }
func file_sqld_v1_plugin_plugin_proto_init() {
	if File_sqld_v1_plugin_plugin_proto != nil {
		return
	}
	file_sqld_v1_plugin_annotation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sqld_v1_plugin_plugin_proto_rawDesc), len(file_sqld_v1_plugin_plugin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sqld_v1_plugin_plugin_proto_goTypes,
		DependencyIndexes: file_sqld_v1_plugin_plugin_proto_depIdxs,
		EnumInfos:         file_sqld_v1_plugin_plugin_proto_enumTypes,
		MessageInfos:      file_sqld_v1_plugin_plugin_proto_msgTypes,
	}.Build()
	File_sqld_v1_plugin_plugin_proto = out.File
	file_sqld_v1_plugin_plugin_proto_goTypes = nil
	file_sqld_v1_plugin_plugin_proto_depIdxs = nil
}
