package main

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/gopherex/sqld/pkg/devdb"
	"github.com/jackc/pgx/v5"
)

// Exercise the CLI's two introspected databases and execute its actual output.
// Catalog round trips alone cannot detect metadata lost on BOTH sides.
func TestMigrateGenerateIdentityPartitionsQualifiedNames(t *testing.T) {
	ctx := context.Background()
	dev, err := devdb.Start(ctx)
	if err != nil {
		t.Skipf("docker unavailable: %v", err)
	}
	defer dev.Close()
	conn, err := pgx.Connect(ctx, dev.URL())
	if err != nil {
		t.Fatal(err)
	}
	defer conn.Close(ctx)
	execSQL := func(sql string) {
		t.Helper()
		if _, err := conn.Exec(ctx, sql); err != nil {
			t.Fatalf("%v\n%s", err, sql)
		}
	}
	// Every newly opened dev connection sees backplane in search_path. Output
	// must nevertheless apply to a connection with an empty search_path.
	execSQL(`ALTER ROLE CURRENT_USER SET search_path = backplane, public`)
	root := t.TempDir()
	if err := os.Mkdir(filepath.Join(root, "migrations"), 0o755); err != nil {
		t.Fatal(err)
	}
	cfg := filepath.Join(root, "sqld.yaml")
	schema := `CREATE SCHEMA backplane;
CREATE TABLE backplane.a (id uuid PRIMARY KEY,
 seq bigint GENERATED ALWAYS AS IDENTITY UNIQUE, t timestamptz NOT NULL, attrs jsonb NOT NULL DEFAULT '{}');
CREATE TABLE backplane.b (id uuid PRIMARY KEY, t timestamptz NOT NULL, detail jsonb NOT NULL DEFAULT '{}');
CREATE VIEW backplane.feed AS
 SELECT 'a' AS source, id, t, attrs AS attributes FROM backplane.a
 UNION ALL SELECT 'b', id, t, detail FROM backplane.b;
CREATE TABLE backplane.p (id uuid NOT NULL, t timestamptz NOT NULL, PRIMARY KEY (t, id)) PARTITION BY RANGE (t);
CREATE TABLE backplane.p_default PARTITION OF backplane.p DEFAULT;
CREATE TABLE backplane.audit (id bigserial PRIMARY KEY);
CREATE TABLE backplane.by_default (
 id bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME backplane.custom_identity START 0 INCREMENT 2 MINVALUE 0 MAXVALUE 100 CACHE 3 CYCLE),
 doubled bigint GENERATED ALWAYS AS (id * 2) STORED);
-- Names deliberately sort children before parents; include all strategies.
CREATE TABLE backplane.z_root (id int NOT NULL, kind text NOT NULL, CHECK (id >= 0), UNIQUE (id, kind)) PARTITION BY LIST (kind);
CREATE TABLE backplane.m_middle PARTITION OF backplane.z_root FOR VALUES IN ('x') PARTITION BY HASH (id);
CREATE TABLE backplane.a_leaf PARTITION OF backplane.m_middle FOR VALUES WITH (MODULUS 1, REMAINDER 0);
CREATE INDEX z_root_idx ON backplane.z_root (id DESC);
CREATE INDEX a_leaf_local ON backplane.a_leaf (kind);
`
	for name, body := range map[string]string{
		"schema.sql": schema,
		"sqld.yaml":  fmt.Sprintf("version: \"1\"\nengine: postgresql\noptions:\n  defaultSchema: backplane\nschema:\n  - file: %s\nmigrations:\n  - dir: %s\n", filepath.Join(root, "schema.sql"), filepath.Join(root, "migrations")),
	} {
		if err := os.WriteFile(filepath.Join(root, name), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	generate := func(name string) string {
		t.Helper()
		var out, errs bytes.Buffer
		if code := run([]string{"migrate", "generate", name, "-c", cfg, "--dev-url", dev.URL()}, &out, &errs); code != 0 {
			t.Fatalf("generate: exit %d\n%s\n%s", code, &out, &errs)
		}
		return strings.TrimSpace(out.String())
	}
	path := generate("init")
	body, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	up, down, ok := strings.Cut(string(body), "-- sqld:down")
	if !ok {
		t.Fatal("missing down")
	}
	for _, want := range []string{
		`GENERATED ALWAYS AS IDENTITY`, `GENERATED BY DEFAULT AS IDENTITY`,
		`PARTITION BY RANGE (t)`, `PARTITION OF "backplane"."p" DEFAULT`,
		`FROM backplane.a`, `FROM backplane.b`, `nextval('backplane.audit_id_seq'::regclass)`,
	} {
		if !strings.Contains(up, want) {
			t.Errorf("missing %s\n%s", want, up)
		}
	}
	if strings.Contains(up, `CREATE SEQUENCE "backplane"."a_seq_seq"`) || strings.Contains(up, `CREATE SEQUENCE "backplane"."custom_identity"`) {
		t.Fatalf("identity sequences emitted twice:\n%s", up)
	}
	execSQL(`SET search_path = ''`)
	execSQL(up)
	var seq, serial, generated int64
	if err := conn.QueryRow(ctx, `INSERT INTO backplane.a (id,t) VALUES ('00000000-0000-0000-0000-000000000001',now()) RETURNING seq`).Scan(&seq); err != nil || seq != 1 {
		t.Fatalf("identity insert: seq=%d err=%v", seq, err)
	}
	if _, err := conn.Exec(ctx, `INSERT INTO backplane.a (id,t,seq) VALUES ('00000000-0000-0000-0000-000000000002',now(),2)`); err == nil {
		t.Fatal("ALWAYS accepted explicit value")
	}
	if err := conn.QueryRow(ctx, `INSERT INTO backplane.audit DEFAULT VALUES RETURNING id`).Scan(&serial); err != nil || serial != 1 {
		t.Fatalf("serial insert: %d %v", serial, err)
	}
	if err := conn.QueryRow(ctx, `INSERT INTO backplane.by_default DEFAULT VALUES RETURNING id,doubled`).Scan(&seq, &generated); err != nil || seq != 0 || generated != 0 {
		t.Fatalf("identity options: %d %d %v", seq, generated, err)
	}
	if err := conn.QueryRow(ctx, `INSERT INTO backplane.by_default DEFAULT VALUES RETURNING id,doubled`).Scan(&seq, &generated); err != nil || seq != 2 || generated != 4 {
		t.Fatalf("identity increment: %d %d %v", seq, generated, err)
	}
	execSQL(`INSERT INTO backplane.by_default(id) VALUES (8)`)
	var relation string
	if err := conn.QueryRow(ctx, `INSERT INTO backplane.p VALUES ('00000000-0000-0000-0000-000000000001',now()) RETURNING tableoid::regclass::text`).Scan(&relation); err != nil || relation != "backplane.p_default" {
		t.Fatalf("range routing: %s %v", relation, err)
	}
	if err := conn.QueryRow(ctx, `INSERT INTO backplane.z_root VALUES (1,'x') RETURNING tableoid::regclass::text`).Scan(&relation); err != nil || relation != "backplane.a_leaf" {
		t.Fatalf("nested routing: %s %v", relation, err)
	}
	var count int
	if err := conn.QueryRow(ctx, `SELECT count(*) FROM backplane.feed`).Scan(&count); err != nil || count != 1 {
		t.Fatalf("view: %d %v", count, err)
	}
	if _, err := conn.Exec(ctx, `INSERT INTO backplane.z_root VALUES (-1,'x')`); err == nil {
		t.Fatal("inherited CHECK lost")
	}
	if _, err := conn.Exec(ctx, `INSERT INTO backplane.z_root VALUES (1,'x')`); err == nil {
		t.Fatal("inherited UNIQUE lost")
	}
	execSQL(down)
	if err := conn.QueryRow(ctx, `SELECT count(*) FROM pg_catalog.pg_namespace WHERE nspname = 'backplane'`).Scan(&count); err != nil || count != 0 {
		t.Fatalf("down: count=%d err=%v", count, err)
	}
	if got := generate("unchanged"); got != "no changes" {
		t.Fatalf("second generate: %s", got)
	}
}
