package main

import (
	"fmt"
	"go/format"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/yaroher/sqld/pkg/gotypes"
	irv1 "github.com/yaroher/sqld/pkg/proto/sqld/v1/ir"
	pluginv1 "github.com/yaroher/sqld/pkg/proto/sqld/v1/plugin"
)

// newTablexRe extracts (model, schema, table) from the bob-generated table or
// view registration line, e.g.
//
//	var AppUsers = psql.NewTablex[*AppUser, AppUserSlice, *AppUserSetter]("app", "users", buildAppUserColumns("app.users"))
//	var AppKitchenSinks = psql.NewViewx[*AppKitchenSink, AppKitchenSinkSlice]("app", "kitchen_sink", buildAppKitchenSinkColumns("app.kitchen_sink"))
//
// A table without a primary key is registered as a view (NewViewx) rather than a
// table (NewTablex), so both forms are matched. group 1 = bob model type name,
// group 2 = schema, group 3 = table.
var newTablexRe = regexp.MustCompile(`New(?:Tablex|Viewx)\[\*(\w+),[^\]]*\]\("([^"]*)",\s*"([^"]*)"`)

// generateBridge emits, for each catalog table that bob produced a model for, a
// method
//
//	func (m AppUser) ToSqld() db.AppUsers { ... }
//
// that field-copies the bob model into sqld-gen-go's flat model (the canonical
// full-table struct), dropping bob's ORM-only R/C fields. The leaf types are
// shared (qualified into typesPackage), so column copies are trivial; the only
// adjustment is unwrapping bob's null.Val[T] back to what sqld-gen-go emits:
//   - a wrapped field (scalar/enum/composite, pointer mode) → ".Ptr()" (*T);
//     in opt mode both sides are null.Val so it is a direct copy;
//   - a nil-capable value field (slice/map/json.RawMessage/pgtype.* struct/
//     range), which bob still wraps in null.Val[T] but sqld-gen-go emits as the
//     bare value type → ".GetOrZero()".
//
// The bob model TYPE name per table is discovered by parsing the generated
// *.bob.go files (their NewTablex lines) rather than re-deriving bob's singular
// inflection. It is only invoked when opts.TypesPackage != "" (the bridge is
// meaningless without the shared leaf-type package), and writes the file
// directly to disk like bob writes its own outputs.
func generateBridge(req *pluginv1.GenerateRequest, opts bobOptions, mapper *gotypes.Mapper) error {
	pkgDir := filepath.Join(req.GetOutDir(), opts.Package)

	models, err := parseBobModels(pkgDir)
	if err != nil {
		return fmt.Errorf("parse bob models: %w", err)
	}

	alias := path.Base(opts.TypesPackage)

	var body strings.Builder
	for _, sc := range req.GetCatalog().GetSchemas() {
		for _, tbl := range sc.GetTables() {
			schema := sc.GetName()
			table := tbl.GetName().GetName()
			model, ok := models[schemaTableKey(schema, table)]
			if !ok {
				// bob produced no model for this table (e.g. excluded); skip.
				continue
			}
			writeToSqld(&body, opts, mapper, alias, model, schema, table, tbl)
		}
	}

	if body.Len() == 0 {
		// No tables matched a bob model; nothing to emit.
		return nil
	}

	var src strings.Builder
	fmt.Fprintf(&src, "// Code generated by sqld-gen-bob. DO NOT EDIT.\n\n")
	fmt.Fprintf(&src, "package %s\n\n", opts.Package)
	fmt.Fprintf(&src, "import %s %q\n\n", alias, opts.TypesPackage)
	src.WriteString(body.String())

	formatted, err := format.Source([]byte(src.String()))
	if err != nil {
		return fmt.Errorf("format sqld_bridge.go: %w\n%s", err, src.String())
	}

	out := filepath.Join(pkgDir, "sqld_bridge.go")
	if err := os.WriteFile(out, formatted, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", out, err)
	}
	return nil
}

// writeToSqld appends one ToSqld method to b for a single table.
func writeToSqld(b *strings.Builder, opts bobOptions, mapper *gotypes.Mapper, alias, model, schema, table string, tbl *irv1.Table) {
	ret := alias + "." + mapper.UDTName(schema, table)

	fmt.Fprintf(b, "// ToSqld converts the bob model to the sqld-gen-go model (%s),\n", ret)
	fmt.Fprintf(b, "// dropping bob's ORM fields. Leaf types are shared, so this is a plain copy\n")
	fmt.Fprintf(b, "// (null.Val[T] is unwrapped to match what sqld-gen-go emits).\n")
	fmt.Fprintf(b, "func (m %s) ToSqld() %s {\n", model, ret)
	fmt.Fprintf(b, "\treturn %s{\n", ret)
	for _, col := range tbl.GetColumns() {
		field := gotypes.Pascal(col.GetName())
		conv := "m." + field
		if col.GetNullable() {
			if mapper.IsNullWrapped(col.GetId(), col.GetType(), col.GetNullable()) {
				// sqld-gen-go emits *T (pointer mode) or null.Val[T] (opt mode);
				// bob always emits null.Val[T]. Unwrap to a pointer in pointer
				// mode; in opt mode both sides match so copy directly.
				if opts.NullMode != "opt" {
					conv += ".Ptr()"
				}
			} else {
				// nil-capable value type in sqld-gen-go, but bob still wraps it
				// in null.Val[T]; unwrap to the bare value.
				conv += ".GetOrZero()"
			}
		}
		fmt.Fprintf(b, "\t\t%s: %s,\n", field, conv)
	}
	fmt.Fprintf(b, "\t}\n")
	fmt.Fprintf(b, "}\n\n")
}

// parseBobModels reads every *.bob.go in dir and maps each table's
// schema-qualified key to the bob model type name parsed from its NewTablex
// registration line.
func parseBobModels(dir string) (map[string]string, error) {
	entries, err := filepath.Glob(filepath.Join(dir, "*.bob.go"))
	if err != nil {
		return nil, err
	}
	sort.Strings(entries)
	out := make(map[string]string)
	for _, f := range entries {
		data, err := os.ReadFile(f)
		if err != nil {
			return nil, err
		}
		for _, mtch := range newTablexRe.FindAllStringSubmatch(string(data), -1) {
			model, schema, table := mtch[1], mtch[2], mtch[3]
			out[schemaTableKey(schema, table)] = model
		}
	}
	return out, nil
}

// schemaTableKey is the lookup key joining a model's schema and table. bob's
// NewTablex line carries the real schema name (e.g. "app", "audit"), matching
// the catalog schema name, so this keys directly off the catalog.
func schemaTableKey(schema, table string) string {
	return schema + "\x00" + table
}
