// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: sqld/v1/ir/catalog.proto

package irv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Schema is a PostgreSQL namespace and the container for its objects.
type Schema struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // = name
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Owner             string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Tables            []*Table               `protobuf:"bytes,4,rep,name=tables,proto3" json:"tables,omitempty"`
	Views             []*View                `protobuf:"bytes,5,rep,name=views,proto3" json:"views,omitempty"`
	MaterializedViews []*MaterializedView    `protobuf:"bytes,6,rep,name=materialized_views,json=materializedViews,proto3" json:"materialized_views,omitempty"`
	Sequences         []*Sequence            `protobuf:"bytes,7,rep,name=sequences,proto3" json:"sequences,omitempty"`
	Functions         []*Function            `protobuf:"bytes,8,rep,name=functions,proto3" json:"functions,omitempty"`
	Procedures        []*Procedure           `protobuf:"bytes,9,rep,name=procedures,proto3" json:"procedures,omitempty"`
	Triggers          []*Trigger             `protobuf:"bytes,10,rep,name=triggers,proto3" json:"triggers,omitempty"` // resolved targets of Table.triggers
	Enums             []*EnumType            `protobuf:"bytes,11,rep,name=enums,proto3" json:"enums,omitempty"`
	Domains           []*DomainType          `protobuf:"bytes,12,rep,name=domains,proto3" json:"domains,omitempty"`
	Composites        []*CompositeType       `protobuf:"bytes,13,rep,name=composites,proto3" json:"composites,omitempty"`
	Ranges            []*RangeType           `protobuf:"bytes,14,rep,name=ranges,proto3" json:"ranges,omitempty"`
	Meta              *Metadata              `protobuf:"bytes,20,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_sqld_v1_ir_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Schema) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Schema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Schema) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Schema) GetTables() []*Table {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *Schema) GetViews() []*View {
	if x != nil {
		return x.Views
	}
	return nil
}

func (x *Schema) GetMaterializedViews() []*MaterializedView {
	if x != nil {
		return x.MaterializedViews
	}
	return nil
}

func (x *Schema) GetSequences() []*Sequence {
	if x != nil {
		return x.Sequences
	}
	return nil
}

func (x *Schema) GetFunctions() []*Function {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *Schema) GetProcedures() []*Procedure {
	if x != nil {
		return x.Procedures
	}
	return nil
}

func (x *Schema) GetTriggers() []*Trigger {
	if x != nil {
		return x.Triggers
	}
	return nil
}

func (x *Schema) GetEnums() []*EnumType {
	if x != nil {
		return x.Enums
	}
	return nil
}

func (x *Schema) GetDomains() []*DomainType {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *Schema) GetComposites() []*CompositeType {
	if x != nil {
		return x.Composites
	}
	return nil
}

func (x *Schema) GetRanges() []*RangeType {
	if x != nil {
		return x.Ranges
	}
	return nil
}

func (x *Schema) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

// Catalog is the whole database snapshot.
type Catalog struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                              // database name
	DatabaseVersion string                 `protobuf:"bytes,2,opt,name=database_version,json=databaseVersion,proto3" json:"database_version,omitempty"` // e.g. "PostgreSQL 16.2"
	IrVersion       string                 `protobuf:"bytes,3,opt,name=ir_version,json=irVersion,proto3" json:"ir_version,omitempty"`                   // IR producer version
	DefaultSchema   string                 `protobuf:"bytes,4,opt,name=default_schema,json=defaultSchema,proto3" json:"default_schema,omitempty"`       // usually "public"
	SearchPath      []string               `protobuf:"bytes,5,rep,name=search_path,json=searchPath,proto3" json:"search_path,omitempty"`
	Schemas         []*Schema              `protobuf:"bytes,6,rep,name=schemas,proto3" json:"schemas,omitempty"`
	// Derived relationship graph spanning all schemas (see relation.proto).
	Relationships []*Relationship `protobuf:"bytes,7,rep,name=relationships,proto3" json:"relationships,omitempty"`
	Meta          *Metadata       `protobuf:"bytes,15,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Catalog) Reset() {
	*x = Catalog{}
	mi := &file_sqld_v1_ir_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Catalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Catalog) ProtoMessage() {}

func (x *Catalog) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Catalog.ProtoReflect.Descriptor instead.
func (*Catalog) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *Catalog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Catalog) GetDatabaseVersion() string {
	if x != nil {
		return x.DatabaseVersion
	}
	return ""
}

func (x *Catalog) GetIrVersion() string {
	if x != nil {
		return x.IrVersion
	}
	return ""
}

func (x *Catalog) GetDefaultSchema() string {
	if x != nil {
		return x.DefaultSchema
	}
	return ""
}

func (x *Catalog) GetSearchPath() []string {
	if x != nil {
		return x.SearchPath
	}
	return nil
}

func (x *Catalog) GetSchemas() []*Schema {
	if x != nil {
		return x.Schemas
	}
	return nil
}

func (x *Catalog) GetRelationships() []*Relationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

func (x *Catalog) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_sqld_v1_ir_catalog_proto protoreflect.FileDescriptor

const file_sqld_v1_ir_catalog_proto_rawDesc = "" +
	"\n" +
	"\x18sqld/v1/ir/catalog.proto\x12\n" +
	"sqld.v1.ir\x1a\x17sqld/v1/ir/common.proto\x1a\x17sqld/v1/ir/schema.proto\x1a\x18sqld/v1/ir/routine.proto\x1a\x19sqld/v1/ir/relation.proto\"\xa4\x05\n" +
	"\x06Schema\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12)\n" +
	"\x06tables\x18\x04 \x03(\v2\x11.sqld.v1.ir.TableR\x06tables\x12&\n" +
	"\x05views\x18\x05 \x03(\v2\x10.sqld.v1.ir.ViewR\x05views\x12K\n" +
	"\x12materialized_views\x18\x06 \x03(\v2\x1c.sqld.v1.ir.MaterializedViewR\x11materializedViews\x122\n" +
	"\tsequences\x18\a \x03(\v2\x14.sqld.v1.ir.SequenceR\tsequences\x122\n" +
	"\tfunctions\x18\b \x03(\v2\x14.sqld.v1.ir.FunctionR\tfunctions\x125\n" +
	"\n" +
	"procedures\x18\t \x03(\v2\x15.sqld.v1.ir.ProcedureR\n" +
	"procedures\x12/\n" +
	"\btriggers\x18\n" +
	" \x03(\v2\x13.sqld.v1.ir.TriggerR\btriggers\x12*\n" +
	"\x05enums\x18\v \x03(\v2\x14.sqld.v1.ir.EnumTypeR\x05enums\x120\n" +
	"\adomains\x18\f \x03(\v2\x16.sqld.v1.ir.DomainTypeR\adomains\x129\n" +
	"\n" +
	"composites\x18\r \x03(\v2\x19.sqld.v1.ir.CompositeTypeR\n" +
	"composites\x12-\n" +
	"\x06ranges\x18\x0e \x03(\v2\x15.sqld.v1.ir.RangeTypeR\x06ranges\x12(\n" +
	"\x04meta\x18\x14 \x01(\v2\x14.sqld.v1.ir.MetadataR\x04meta\"\xc7\x02\n" +
	"\aCatalog\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x10database_version\x18\x02 \x01(\tR\x0fdatabaseVersion\x12\x1d\n" +
	"\n" +
	"ir_version\x18\x03 \x01(\tR\tirVersion\x12%\n" +
	"\x0edefault_schema\x18\x04 \x01(\tR\rdefaultSchema\x12\x1f\n" +
	"\vsearch_path\x18\x05 \x03(\tR\n" +
	"searchPath\x12,\n" +
	"\aschemas\x18\x06 \x03(\v2\x12.sqld.v1.ir.SchemaR\aschemas\x12>\n" +
	"\rrelationships\x18\a \x03(\v2\x18.sqld.v1.ir.RelationshipR\rrelationships\x12(\n" +
	"\x04meta\x18\x0f \x01(\v2\x14.sqld.v1.ir.MetadataR\x04metaB3Z1github.com/gopherex/sqld/pkg/proto/sqld/v1/ir;irv1b\x06proto3"

var (
	file_sqld_v1_ir_catalog_proto_rawDescOnce sync.Once
	file_sqld_v1_ir_catalog_proto_rawDescData []byte
)

func file_sqld_v1_ir_catalog_proto_rawDescGZIP() []byte {
	file_sqld_v1_ir_catalog_proto_rawDescOnce.Do(func() {
		file_sqld_v1_ir_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sqld_v1_ir_catalog_proto_rawDesc), len(file_sqld_v1_ir_catalog_proto_rawDesc)))
	})
	return file_sqld_v1_ir_catalog_proto_rawDescData
}

var file_sqld_v1_ir_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sqld_v1_ir_catalog_proto_goTypes = []any{
	(*Schema)(nil),           // 0: sqld.v1.ir.Schema
	(*Catalog)(nil),          // 1: sqld.v1.ir.Catalog
	(*Table)(nil),            // 2: sqld.v1.ir.Table
	(*View)(nil),             // 3: sqld.v1.ir.View
	(*MaterializedView)(nil), // 4: sqld.v1.ir.MaterializedView
	(*Sequence)(nil),         // 5: sqld.v1.ir.Sequence
	(*Function)(nil),         // 6: sqld.v1.ir.Function
	(*Procedure)(nil),        // 7: sqld.v1.ir.Procedure
	(*Trigger)(nil),          // 8: sqld.v1.ir.Trigger
	(*EnumType)(nil),         // 9: sqld.v1.ir.EnumType
	(*DomainType)(nil),       // 10: sqld.v1.ir.DomainType
	(*CompositeType)(nil),    // 11: sqld.v1.ir.CompositeType
	(*RangeType)(nil),        // 12: sqld.v1.ir.RangeType
	(*Metadata)(nil),         // 13: sqld.v1.ir.Metadata
	(*Relationship)(nil),     // 14: sqld.v1.ir.Relationship
}
var file_sqld_v1_ir_catalog_proto_depIdxs = []int32{
	2,  // 0: sqld.v1.ir.Schema.tables:type_name -> sqld.v1.ir.Table
	3,  // 1: sqld.v1.ir.Schema.views:type_name -> sqld.v1.ir.View
	4,  // 2: sqld.v1.ir.Schema.materialized_views:type_name -> sqld.v1.ir.MaterializedView
	5,  // 3: sqld.v1.ir.Schema.sequences:type_name -> sqld.v1.ir.Sequence
	6,  // 4: sqld.v1.ir.Schema.functions:type_name -> sqld.v1.ir.Function
	7,  // 5: sqld.v1.ir.Schema.procedures:type_name -> sqld.v1.ir.Procedure
	8,  // 6: sqld.v1.ir.Schema.triggers:type_name -> sqld.v1.ir.Trigger
	9,  // 7: sqld.v1.ir.Schema.enums:type_name -> sqld.v1.ir.EnumType
	10, // 8: sqld.v1.ir.Schema.domains:type_name -> sqld.v1.ir.DomainType
	11, // 9: sqld.v1.ir.Schema.composites:type_name -> sqld.v1.ir.CompositeType
	12, // 10: sqld.v1.ir.Schema.ranges:type_name -> sqld.v1.ir.RangeType
	13, // 11: sqld.v1.ir.Schema.meta:type_name -> sqld.v1.ir.Metadata
	0,  // 12: sqld.v1.ir.Catalog.schemas:type_name -> sqld.v1.ir.Schema
	14, // 13: sqld.v1.ir.Catalog.relationships:type_name -> sqld.v1.ir.Relationship
	13, // 14: sqld.v1.ir.Catalog.meta:type_name -> sqld.v1.ir.Metadata
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_sqld_v1_ir_catalog_proto_init() }
func file_sqld_v1_ir_catalog_proto_init() {
	if File_sqld_v1_ir_catalog_proto != nil {
		return
	}
	file_sqld_v1_ir_common_proto_init()
	file_sqld_v1_ir_schema_proto_init()
	file_sqld_v1_ir_routine_proto_init()
	file_sqld_v1_ir_relation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sqld_v1_ir_catalog_proto_rawDesc), len(file_sqld_v1_ir_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sqld_v1_ir_catalog_proto_goTypes,
		DependencyIndexes: file_sqld_v1_ir_catalog_proto_depIdxs,
		MessageInfos:      file_sqld_v1_ir_catalog_proto_msgTypes,
	}.Build()
	File_sqld_v1_ir_catalog_proto = out.File
	file_sqld_v1_ir_catalog_proto_goTypes = nil
	file_sqld_v1_ir_catalog_proto_depIdxs = nil
}
