// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: sqld/v1/ir/common.proto

package irv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Engine identifies the SQL dialect. Shared by config and plugin packages so
// neither has to depend on the other.
type Engine int32

const (
	Engine_ENGINE_UNSPECIFIED Engine = 0
	Engine_ENGINE_POSTGRESQL  Engine = 1
)

// Enum value maps for Engine.
var (
	Engine_name = map[int32]string{
		0: "ENGINE_UNSPECIFIED",
		1: "ENGINE_POSTGRESQL",
	}
	Engine_value = map[string]int32{
		"ENGINE_UNSPECIFIED": 0,
		"ENGINE_POSTGRESQL":  1,
	}
)

func (x Engine) Enum() *Engine {
	p := new(Engine)
	*p = x
	return p
}

func (x Engine) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Engine) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_common_proto_enumTypes[0].Descriptor()
}

func (Engine) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_common_proto_enumTypes[0]
}

func (x Engine) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Engine.Descriptor instead.
func (Engine) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_common_proto_rawDescGZIP(), []int{0}
}

// ObjectKind discriminates what an ObjectRef points at.
type ObjectKind int32

const (
	ObjectKind_OBJECT_KIND_UNSPECIFIED       ObjectKind = 0
	ObjectKind_OBJECT_KIND_SCHEMA            ObjectKind = 1
	ObjectKind_OBJECT_KIND_TABLE             ObjectKind = 2
	ObjectKind_OBJECT_KIND_VIEW              ObjectKind = 3
	ObjectKind_OBJECT_KIND_MATERIALIZED_VIEW ObjectKind = 4
	ObjectKind_OBJECT_KIND_COLUMN            ObjectKind = 5
	ObjectKind_OBJECT_KIND_CONSTRAINT        ObjectKind = 6
	ObjectKind_OBJECT_KIND_INDEX             ObjectKind = 7
	ObjectKind_OBJECT_KIND_SEQUENCE          ObjectKind = 8
	ObjectKind_OBJECT_KIND_FUNCTION          ObjectKind = 9
	ObjectKind_OBJECT_KIND_PROCEDURE         ObjectKind = 10
	ObjectKind_OBJECT_KIND_TRIGGER           ObjectKind = 11
	ObjectKind_OBJECT_KIND_ENUM_TYPE         ObjectKind = 12
	ObjectKind_OBJECT_KIND_DOMAIN_TYPE       ObjectKind = 13
	ObjectKind_OBJECT_KIND_COMPOSITE_TYPE    ObjectKind = 14
	ObjectKind_OBJECT_KIND_RANGE_TYPE        ObjectKind = 15
)

// Enum value maps for ObjectKind.
var (
	ObjectKind_name = map[int32]string{
		0:  "OBJECT_KIND_UNSPECIFIED",
		1:  "OBJECT_KIND_SCHEMA",
		2:  "OBJECT_KIND_TABLE",
		3:  "OBJECT_KIND_VIEW",
		4:  "OBJECT_KIND_MATERIALIZED_VIEW",
		5:  "OBJECT_KIND_COLUMN",
		6:  "OBJECT_KIND_CONSTRAINT",
		7:  "OBJECT_KIND_INDEX",
		8:  "OBJECT_KIND_SEQUENCE",
		9:  "OBJECT_KIND_FUNCTION",
		10: "OBJECT_KIND_PROCEDURE",
		11: "OBJECT_KIND_TRIGGER",
		12: "OBJECT_KIND_ENUM_TYPE",
		13: "OBJECT_KIND_DOMAIN_TYPE",
		14: "OBJECT_KIND_COMPOSITE_TYPE",
		15: "OBJECT_KIND_RANGE_TYPE",
	}
	ObjectKind_value = map[string]int32{
		"OBJECT_KIND_UNSPECIFIED":       0,
		"OBJECT_KIND_SCHEMA":            1,
		"OBJECT_KIND_TABLE":             2,
		"OBJECT_KIND_VIEW":              3,
		"OBJECT_KIND_MATERIALIZED_VIEW": 4,
		"OBJECT_KIND_COLUMN":            5,
		"OBJECT_KIND_CONSTRAINT":        6,
		"OBJECT_KIND_INDEX":             7,
		"OBJECT_KIND_SEQUENCE":          8,
		"OBJECT_KIND_FUNCTION":          9,
		"OBJECT_KIND_PROCEDURE":         10,
		"OBJECT_KIND_TRIGGER":           11,
		"OBJECT_KIND_ENUM_TYPE":         12,
		"OBJECT_KIND_DOMAIN_TYPE":       13,
		"OBJECT_KIND_COMPOSITE_TYPE":    14,
		"OBJECT_KIND_RANGE_TYPE":        15,
	}
)

func (x ObjectKind) Enum() *ObjectKind {
	p := new(ObjectKind)
	*p = x
	return p
}

func (x ObjectKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectKind) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_common_proto_enumTypes[1].Descriptor()
}

func (ObjectKind) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_common_proto_enumTypes[1]
}

func (x ObjectKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectKind.Descriptor instead.
func (ObjectKind) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_common_proto_rawDescGZIP(), []int{1}
}

// AnnotationTargetKind identifies what an annotation is attached to. Shared by
// the value model (here) and the grammar model (plugin package).
type AnnotationTargetKind int32

const (
	AnnotationTargetKind_ANNOTATION_TARGET_KIND_UNSPECIFIED       AnnotationTargetKind = 0
	AnnotationTargetKind_ANNOTATION_TARGET_KIND_SCHEMA            AnnotationTargetKind = 1
	AnnotationTargetKind_ANNOTATION_TARGET_KIND_TABLE             AnnotationTargetKind = 2
	AnnotationTargetKind_ANNOTATION_TARGET_KIND_COLUMN            AnnotationTargetKind = 3
	AnnotationTargetKind_ANNOTATION_TARGET_KIND_VIEW              AnnotationTargetKind = 4
	AnnotationTargetKind_ANNOTATION_TARGET_KIND_MATERIALIZED_VIEW AnnotationTargetKind = 5
	AnnotationTargetKind_ANNOTATION_TARGET_KIND_FUNCTION          AnnotationTargetKind = 6
	AnnotationTargetKind_ANNOTATION_TARGET_KIND_PROCEDURE         AnnotationTargetKind = 7
	AnnotationTargetKind_ANNOTATION_TARGET_KIND_TRIGGER           AnnotationTargetKind = 8
	AnnotationTargetKind_ANNOTATION_TARGET_KIND_CONSTRAINT        AnnotationTargetKind = 9
	AnnotationTargetKind_ANNOTATION_TARGET_KIND_INDEX             AnnotationTargetKind = 10
	AnnotationTargetKind_ANNOTATION_TARGET_KIND_SEQUENCE          AnnotationTargetKind = 11
	AnnotationTargetKind_ANNOTATION_TARGET_KIND_TYPE              AnnotationTargetKind = 12
	AnnotationTargetKind_ANNOTATION_TARGET_KIND_QUERY             AnnotationTargetKind = 13 // named DML query
	AnnotationTargetKind_ANNOTATION_TARGET_KIND_MIGRATION         AnnotationTargetKind = 14
)

// Enum value maps for AnnotationTargetKind.
var (
	AnnotationTargetKind_name = map[int32]string{
		0:  "ANNOTATION_TARGET_KIND_UNSPECIFIED",
		1:  "ANNOTATION_TARGET_KIND_SCHEMA",
		2:  "ANNOTATION_TARGET_KIND_TABLE",
		3:  "ANNOTATION_TARGET_KIND_COLUMN",
		4:  "ANNOTATION_TARGET_KIND_VIEW",
		5:  "ANNOTATION_TARGET_KIND_MATERIALIZED_VIEW",
		6:  "ANNOTATION_TARGET_KIND_FUNCTION",
		7:  "ANNOTATION_TARGET_KIND_PROCEDURE",
		8:  "ANNOTATION_TARGET_KIND_TRIGGER",
		9:  "ANNOTATION_TARGET_KIND_CONSTRAINT",
		10: "ANNOTATION_TARGET_KIND_INDEX",
		11: "ANNOTATION_TARGET_KIND_SEQUENCE",
		12: "ANNOTATION_TARGET_KIND_TYPE",
		13: "ANNOTATION_TARGET_KIND_QUERY",
		14: "ANNOTATION_TARGET_KIND_MIGRATION",
	}
	AnnotationTargetKind_value = map[string]int32{
		"ANNOTATION_TARGET_KIND_UNSPECIFIED":       0,
		"ANNOTATION_TARGET_KIND_SCHEMA":            1,
		"ANNOTATION_TARGET_KIND_TABLE":             2,
		"ANNOTATION_TARGET_KIND_COLUMN":            3,
		"ANNOTATION_TARGET_KIND_VIEW":              4,
		"ANNOTATION_TARGET_KIND_MATERIALIZED_VIEW": 5,
		"ANNOTATION_TARGET_KIND_FUNCTION":          6,
		"ANNOTATION_TARGET_KIND_PROCEDURE":         7,
		"ANNOTATION_TARGET_KIND_TRIGGER":           8,
		"ANNOTATION_TARGET_KIND_CONSTRAINT":        9,
		"ANNOTATION_TARGET_KIND_INDEX":             10,
		"ANNOTATION_TARGET_KIND_SEQUENCE":          11,
		"ANNOTATION_TARGET_KIND_TYPE":              12,
		"ANNOTATION_TARGET_KIND_QUERY":             13,
		"ANNOTATION_TARGET_KIND_MIGRATION":         14,
	}
)

func (x AnnotationTargetKind) Enum() *AnnotationTargetKind {
	p := new(AnnotationTargetKind)
	*p = x
	return p
}

func (x AnnotationTargetKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnnotationTargetKind) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_common_proto_enumTypes[2].Descriptor()
}

func (AnnotationTargetKind) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_common_proto_enumTypes[2]
}

func (x AnnotationTargetKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnnotationTargetKind.Descriptor instead.
func (AnnotationTargetKind) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_common_proto_rawDescGZIP(), []int{2}
}

// AnnotationArgType is the scalar type of a parsed argument. Shared with the
// grammar model's FieldSpec.
type AnnotationArgType int32

const (
	AnnotationArgType_ANNOTATION_ARG_TYPE_UNSPECIFIED AnnotationArgType = 0
	AnnotationArgType_ANNOTATION_ARG_TYPE_STRING      AnnotationArgType = 1
	AnnotationArgType_ANNOTATION_ARG_TYPE_INT         AnnotationArgType = 2
	AnnotationArgType_ANNOTATION_ARG_TYPE_FLOAT       AnnotationArgType = 3
	AnnotationArgType_ANNOTATION_ARG_TYPE_BOOL        AnnotationArgType = 4
	AnnotationArgType_ANNOTATION_ARG_TYPE_IDENT       AnnotationArgType = 5 // bare identifier
	AnnotationArgType_ANNOTATION_ARG_TYPE_DURATION    AnnotationArgType = 6 // "30s", "5m" -> duration_nanos
	AnnotationArgType_ANNOTATION_ARG_TYPE_ENUM        AnnotationArgType = 7
)

// Enum value maps for AnnotationArgType.
var (
	AnnotationArgType_name = map[int32]string{
		0: "ANNOTATION_ARG_TYPE_UNSPECIFIED",
		1: "ANNOTATION_ARG_TYPE_STRING",
		2: "ANNOTATION_ARG_TYPE_INT",
		3: "ANNOTATION_ARG_TYPE_FLOAT",
		4: "ANNOTATION_ARG_TYPE_BOOL",
		5: "ANNOTATION_ARG_TYPE_IDENT",
		6: "ANNOTATION_ARG_TYPE_DURATION",
		7: "ANNOTATION_ARG_TYPE_ENUM",
	}
	AnnotationArgType_value = map[string]int32{
		"ANNOTATION_ARG_TYPE_UNSPECIFIED": 0,
		"ANNOTATION_ARG_TYPE_STRING":      1,
		"ANNOTATION_ARG_TYPE_INT":         2,
		"ANNOTATION_ARG_TYPE_FLOAT":       3,
		"ANNOTATION_ARG_TYPE_BOOL":        4,
		"ANNOTATION_ARG_TYPE_IDENT":       5,
		"ANNOTATION_ARG_TYPE_DURATION":    6,
		"ANNOTATION_ARG_TYPE_ENUM":        7,
	}
)

func (x AnnotationArgType) Enum() *AnnotationArgType {
	p := new(AnnotationArgType)
	*p = x
	return p
}

func (x AnnotationArgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnnotationArgType) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_common_proto_enumTypes[3].Descriptor()
}

func (AnnotationArgType) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_common_proto_enumTypes[3]
}

func (x AnnotationArgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnnotationArgType.Descriptor instead.
func (AnnotationArgType) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_common_proto_rawDescGZIP(), []int{3}
}

// QualifiedName is a (catalog, schema, name) tuple. `name` is always set;
// `schema` and `catalog` are empty when not applicable (e.g. a schema object
// has only `name`).
type QualifiedName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Catalog       string                 `protobuf:"bytes,1,opt,name=catalog,proto3" json:"catalog,omitempty"` // database name; usually empty
	Schema        string                 `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`   // namespace; empty for schema-less objects
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`       // object's own name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualifiedName) Reset() {
	*x = QualifiedName{}
	mi := &file_sqld_v1_ir_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualifiedName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualifiedName) ProtoMessage() {}

func (x *QualifiedName) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualifiedName.ProtoReflect.Descriptor instead.
func (*QualifiedName) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_common_proto_rawDescGZIP(), []int{0}
}

func (x *QualifiedName) GetCatalog() string {
	if x != nil {
		return x.Catalog
	}
	return ""
}

func (x *QualifiedName) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *QualifiedName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ObjectRef is a stable, by-id reference to another object in the catalog.
// `id` is the canonical lookup key (e.g. "public.users", "public.users.id").
// `name` and `kind` are carried for readability and validation.
type ObjectRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          ObjectKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=sqld.v1.ir.ObjectKind" json:"kind,omitempty"`
	Name          *QualifiedName         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectRef) Reset() {
	*x = ObjectRef{}
	mi := &file_sqld_v1_ir_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRef) ProtoMessage() {}

func (x *ObjectRef) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRef.ProtoReflect.Descriptor instead.
func (*ObjectRef) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_common_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObjectRef) GetKind() ObjectKind {
	if x != nil {
		return x.Kind
	}
	return ObjectKind_OBJECT_KIND_UNSPECIFIED
}

func (x *ObjectRef) GetName() *QualifiedName {
	if x != nil {
		return x.Name
	}
	return nil
}

// SourceSpan records where an object came from in the original SQL source.
type SourceSpan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	StartLine     uint32                 `protobuf:"varint,2,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	StartColumn   uint32                 `protobuf:"varint,3,opt,name=start_column,json=startColumn,proto3" json:"start_column,omitempty"`
	EndLine       uint32                 `protobuf:"varint,4,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	EndColumn     uint32                 `protobuf:"varint,5,opt,name=end_column,json=endColumn,proto3" json:"end_column,omitempty"`
	StartOffset   uint64                 `protobuf:"varint,6,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	EndOffset     uint64                 `protobuf:"varint,7,opt,name=end_offset,json=endOffset,proto3" json:"end_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceSpan) Reset() {
	*x = SourceSpan{}
	mi := &file_sqld_v1_ir_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceSpan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceSpan) ProtoMessage() {}

func (x *SourceSpan) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceSpan.ProtoReflect.Descriptor instead.
func (*SourceSpan) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_common_proto_rawDescGZIP(), []int{2}
}

func (x *SourceSpan) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *SourceSpan) GetStartLine() uint32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *SourceSpan) GetStartColumn() uint32 {
	if x != nil {
		return x.StartColumn
	}
	return 0
}

func (x *SourceSpan) GetEndLine() uint32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *SourceSpan) GetEndColumn() uint32 {
	if x != nil {
		return x.EndColumn
	}
	return 0
}

func (x *SourceSpan) GetStartOffset() uint64 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *SourceSpan) GetEndOffset() uint64 {
	if x != nil {
		return x.EndOffset
	}
	return 0
}

// AnnotationTargetRef points at the object an annotation is attached to.
// `object` is set for catalog objects; `query_name`/`migration_version` for
// non-catalog targets.
type AnnotationTargetRef struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Kind             AnnotationTargetKind   `protobuf:"varint,1,opt,name=kind,proto3,enum=sqld.v1.ir.AnnotationTargetKind" json:"kind,omitempty"`
	Object           *ObjectRef             `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	QueryName        string                 `protobuf:"bytes,3,opt,name=query_name,json=queryName,proto3" json:"query_name,omitempty"`
	MigrationVersion string                 `protobuf:"bytes,4,opt,name=migration_version,json=migrationVersion,proto3" json:"migration_version,omitempty"`
	Source           *SourceSpan            `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"` // location of the originating comment
	// AST node the annotation guards, when it targets a part of a query/migration
	// (e.g. an optional predicate or join). Matches a `node_id` on a node inside
	// Query.ast / Migration. Empty when the annotation targets a whole object.
	NodeId        string `protobuf:"bytes,6,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotationTargetRef) Reset() {
	*x = AnnotationTargetRef{}
	mi := &file_sqld_v1_ir_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotationTargetRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotationTargetRef) ProtoMessage() {}

func (x *AnnotationTargetRef) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotationTargetRef.ProtoReflect.Descriptor instead.
func (*AnnotationTargetRef) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_common_proto_rawDescGZIP(), []int{3}
}

func (x *AnnotationTargetRef) GetKind() AnnotationTargetKind {
	if x != nil {
		return x.Kind
	}
	return AnnotationTargetKind_ANNOTATION_TARGET_KIND_UNSPECIFIED
}

func (x *AnnotationTargetRef) GetObject() *ObjectRef {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *AnnotationTargetRef) GetQueryName() string {
	if x != nil {
		return x.QueryName
	}
	return ""
}

func (x *AnnotationTargetRef) GetMigrationVersion() string {
	if x != nil {
		return x.MigrationVersion
	}
	return ""
}

func (x *AnnotationTargetRef) GetSource() *SourceSpan {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *AnnotationTargetRef) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// AnnotationArg is one parsed argument: a positional value or a named key.
type AnnotationArg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`    // key/field name; empty for pure positional args
	Index uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"` // 0-based positional index
	Type  AnnotationArgType      `protobuf:"varint,3,opt,name=type,proto3,enum=sqld.v1.ir.AnnotationArgType" json:"type,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*AnnotationArg_StringValue
	//	*AnnotationArg_IntValue
	//	*AnnotationArg_FloatValue
	//	*AnnotationArg_BoolValue
	//	*AnnotationArg_DurationNanos
	Value         isAnnotationArg_Value `protobuf_oneof:"value"`
	Raw           string                `protobuf:"bytes,9,opt,name=raw,proto3" json:"raw,omitempty"` // original token text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotationArg) Reset() {
	*x = AnnotationArg{}
	mi := &file_sqld_v1_ir_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotationArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotationArg) ProtoMessage() {}

func (x *AnnotationArg) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotationArg.ProtoReflect.Descriptor instead.
func (*AnnotationArg) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_common_proto_rawDescGZIP(), []int{4}
}

func (x *AnnotationArg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnnotationArg) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *AnnotationArg) GetType() AnnotationArgType {
	if x != nil {
		return x.Type
	}
	return AnnotationArgType_ANNOTATION_ARG_TYPE_UNSPECIFIED
}

func (x *AnnotationArg) GetValue() isAnnotationArg_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AnnotationArg) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*AnnotationArg_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *AnnotationArg) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*AnnotationArg_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *AnnotationArg) GetFloatValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*AnnotationArg_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *AnnotationArg) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*AnnotationArg_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *AnnotationArg) GetDurationNanos() int64 {
	if x != nil {
		if x, ok := x.Value.(*AnnotationArg_DurationNanos); ok {
			return x.DurationNanos
		}
	}
	return 0
}

func (x *AnnotationArg) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

type isAnnotationArg_Value interface {
	isAnnotationArg_Value()
}

type AnnotationArg_StringValue struct {
	StringValue string `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type AnnotationArg_IntValue struct {
	IntValue int64 `protobuf:"varint,5,opt,name=int_value,json=intValue,proto3,oneof"`
}

type AnnotationArg_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,6,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type AnnotationArg_BoolValue struct {
	BoolValue bool `protobuf:"varint,7,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type AnnotationArg_DurationNanos struct {
	DurationNanos int64 `protobuf:"varint,8,opt,name=duration_nanos,json=durationNanos,proto3,oneof"`
}

func (*AnnotationArg_StringValue) isAnnotationArg_Value() {}

func (*AnnotationArg_IntValue) isAnnotationArg_Value() {}

func (*AnnotationArg_FloatValue) isAnnotationArg_Value() {}

func (*AnnotationArg_BoolValue) isAnnotationArg_Value() {}

func (*AnnotationArg_DurationNanos) isAnnotationArg_Value() {}

// AnnotationValue is one parsed annotation instance.
type AnnotationValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // the AnnotationDef name it matched
	Target        *AnnotationTargetRef   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Args          []*AnnotationArg       `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Present       bool                   `protobuf:"varint,4,opt,name=present,proto3" json:"present,omitempty"` // FLAG form: annotation was present
	Raw           string                 `protobuf:"bytes,5,opt,name=raw,proto3" json:"raw,omitempty"`          // full original annotation text
	Source        *SourceSpan            `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotationValue) Reset() {
	*x = AnnotationValue{}
	mi := &file_sqld_v1_ir_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotationValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotationValue) ProtoMessage() {}

func (x *AnnotationValue) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotationValue.ProtoReflect.Descriptor instead.
func (*AnnotationValue) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_common_proto_rawDescGZIP(), []int{5}
}

func (x *AnnotationValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnnotationValue) GetTarget() *AnnotationTargetRef {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *AnnotationValue) GetArgs() []*AnnotationArg {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *AnnotationValue) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *AnnotationValue) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *AnnotationValue) GetSource() *SourceSpan {
	if x != nil {
		return x.Source
	}
	return nil
}

// Metadata is attached to every modeled object. It carries the SQL COMMENT,
// source provenance, an options bag, and parsed annotations.
type Metadata struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Comment string                 `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`                                                                           // SQL COMMENT ON ...
	Source  *SourceSpan            `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`                                                                             // provenance, optional
	Options map[string]string      `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // free-form generator hints
	// Annotations parsed from this object's comments, per the active plugin's
	// declared schema. Mirrored in GenerateRequest.annotations.
	Annotations   []*AnnotationValue `protobuf:"bytes,4,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_sqld_v1_ir_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_common_proto_rawDescGZIP(), []int{6}
}

func (x *Metadata) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Metadata) GetSource() *SourceSpan {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Metadata) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Metadata) GetAnnotations() []*AnnotationValue {
	if x != nil {
		return x.Annotations
	}
	return nil
}

var File_sqld_v1_ir_common_proto protoreflect.FileDescriptor

const file_sqld_v1_ir_common_proto_rawDesc = "" +
	"\n" +
	"\x17sqld/v1/ir/common.proto\x12\n" +
	"sqld.v1.ir\"U\n" +
	"\rQualifiedName\x12\x18\n" +
	"\acatalog\x18\x01 \x01(\tR\acatalog\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\tR\x06schema\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"v\n" +
	"\tObjectRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x16.sqld.v1.ir.ObjectKindR\x04kind\x12-\n" +
	"\x04name\x18\x03 \x01(\v2\x19.sqld.v1.ir.QualifiedNameR\x04name\"\xde\x01\n" +
	"\n" +
	"SourceSpan\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x1d\n" +
	"\n" +
	"start_line\x18\x02 \x01(\rR\tstartLine\x12!\n" +
	"\fstart_column\x18\x03 \x01(\rR\vstartColumn\x12\x19\n" +
	"\bend_line\x18\x04 \x01(\rR\aendLine\x12\x1d\n" +
	"\n" +
	"end_column\x18\x05 \x01(\rR\tendColumn\x12!\n" +
	"\fstart_offset\x18\x06 \x01(\x04R\vstartOffset\x12\x1d\n" +
	"\n" +
	"end_offset\x18\a \x01(\x04R\tendOffset\"\x8f\x02\n" +
	"\x13AnnotationTargetRef\x124\n" +
	"\x04kind\x18\x01 \x01(\x0e2 .sqld.v1.ir.AnnotationTargetKindR\x04kind\x12-\n" +
	"\x06object\x18\x02 \x01(\v2\x15.sqld.v1.ir.ObjectRefR\x06object\x12\x1d\n" +
	"\n" +
	"query_name\x18\x03 \x01(\tR\tqueryName\x12+\n" +
	"\x11migration_version\x18\x04 \x01(\tR\x10migrationVersion\x12.\n" +
	"\x06source\x18\x05 \x01(\v2\x16.sqld.v1.ir.SourceSpanR\x06source\x12\x17\n" +
	"\anode_id\x18\x06 \x01(\tR\x06nodeId\"\xb8\x02\n" +
	"\rAnnotationArg\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1d.sqld.v1.ir.AnnotationArgTypeR\x04type\x12#\n" +
	"\fstring_value\x18\x04 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x05 \x01(\x03H\x00R\bintValue\x12!\n" +
	"\vfloat_value\x18\x06 \x01(\x01H\x00R\n" +
	"floatValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\a \x01(\bH\x00R\tboolValue\x12'\n" +
	"\x0eduration_nanos\x18\b \x01(\x03H\x00R\rdurationNanos\x12\x10\n" +
	"\x03raw\x18\t \x01(\tR\x03rawB\a\n" +
	"\x05value\"\xe9\x01\n" +
	"\x0fAnnotationValue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\x06target\x18\x02 \x01(\v2\x1f.sqld.v1.ir.AnnotationTargetRefR\x06target\x12-\n" +
	"\x04args\x18\x03 \x03(\v2\x19.sqld.v1.ir.AnnotationArgR\x04args\x12\x18\n" +
	"\apresent\x18\x04 \x01(\bR\apresent\x12\x10\n" +
	"\x03raw\x18\x05 \x01(\tR\x03raw\x12.\n" +
	"\x06source\x18\x06 \x01(\v2\x16.sqld.v1.ir.SourceSpanR\x06source\"\x8c\x02\n" +
	"\bMetadata\x12\x18\n" +
	"\acomment\x18\x01 \x01(\tR\acomment\x12.\n" +
	"\x06source\x18\x02 \x01(\v2\x16.sqld.v1.ir.SourceSpanR\x06source\x12;\n" +
	"\aoptions\x18\x03 \x03(\v2!.sqld.v1.ir.Metadata.OptionsEntryR\aoptions\x12=\n" +
	"\vannotations\x18\x04 \x03(\v2\x1b.sqld.v1.ir.AnnotationValueR\vannotations\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*7\n" +
	"\x06Engine\x12\x16\n" +
	"\x12ENGINE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ENGINE_POSTGRESQL\x10\x01*\xb8\x03\n" +
	"\n" +
	"ObjectKind\x12\x1b\n" +
	"\x17OBJECT_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12OBJECT_KIND_SCHEMA\x10\x01\x12\x15\n" +
	"\x11OBJECT_KIND_TABLE\x10\x02\x12\x14\n" +
	"\x10OBJECT_KIND_VIEW\x10\x03\x12!\n" +
	"\x1dOBJECT_KIND_MATERIALIZED_VIEW\x10\x04\x12\x16\n" +
	"\x12OBJECT_KIND_COLUMN\x10\x05\x12\x1a\n" +
	"\x16OBJECT_KIND_CONSTRAINT\x10\x06\x12\x15\n" +
	"\x11OBJECT_KIND_INDEX\x10\a\x12\x18\n" +
	"\x14OBJECT_KIND_SEQUENCE\x10\b\x12\x18\n" +
	"\x14OBJECT_KIND_FUNCTION\x10\t\x12\x19\n" +
	"\x15OBJECT_KIND_PROCEDURE\x10\n" +
	"\x12\x17\n" +
	"\x13OBJECT_KIND_TRIGGER\x10\v\x12\x19\n" +
	"\x15OBJECT_KIND_ENUM_TYPE\x10\f\x12\x1b\n" +
	"\x17OBJECT_KIND_DOMAIN_TYPE\x10\r\x12\x1e\n" +
	"\x1aOBJECT_KIND_COMPOSITE_TYPE\x10\x0e\x12\x1a\n" +
	"\x16OBJECT_KIND_RANGE_TYPE\x10\x0f*\xbb\x04\n" +
	"\x14AnnotationTargetKind\x12&\n" +
	"\"ANNOTATION_TARGET_KIND_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dANNOTATION_TARGET_KIND_SCHEMA\x10\x01\x12 \n" +
	"\x1cANNOTATION_TARGET_KIND_TABLE\x10\x02\x12!\n" +
	"\x1dANNOTATION_TARGET_KIND_COLUMN\x10\x03\x12\x1f\n" +
	"\x1bANNOTATION_TARGET_KIND_VIEW\x10\x04\x12,\n" +
	"(ANNOTATION_TARGET_KIND_MATERIALIZED_VIEW\x10\x05\x12#\n" +
	"\x1fANNOTATION_TARGET_KIND_FUNCTION\x10\x06\x12$\n" +
	" ANNOTATION_TARGET_KIND_PROCEDURE\x10\a\x12\"\n" +
	"\x1eANNOTATION_TARGET_KIND_TRIGGER\x10\b\x12%\n" +
	"!ANNOTATION_TARGET_KIND_CONSTRAINT\x10\t\x12 \n" +
	"\x1cANNOTATION_TARGET_KIND_INDEX\x10\n" +
	"\x12#\n" +
	"\x1fANNOTATION_TARGET_KIND_SEQUENCE\x10\v\x12\x1f\n" +
	"\x1bANNOTATION_TARGET_KIND_TYPE\x10\f\x12 \n" +
	"\x1cANNOTATION_TARGET_KIND_QUERY\x10\r\x12$\n" +
	" ANNOTATION_TARGET_KIND_MIGRATION\x10\x0e*\x91\x02\n" +
	"\x11AnnotationArgType\x12#\n" +
	"\x1fANNOTATION_ARG_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aANNOTATION_ARG_TYPE_STRING\x10\x01\x12\x1b\n" +
	"\x17ANNOTATION_ARG_TYPE_INT\x10\x02\x12\x1d\n" +
	"\x19ANNOTATION_ARG_TYPE_FLOAT\x10\x03\x12\x1c\n" +
	"\x18ANNOTATION_ARG_TYPE_BOOL\x10\x04\x12\x1d\n" +
	"\x19ANNOTATION_ARG_TYPE_IDENT\x10\x05\x12 \n" +
	"\x1cANNOTATION_ARG_TYPE_DURATION\x10\x06\x12\x1c\n" +
	"\x18ANNOTATION_ARG_TYPE_ENUM\x10\aB3Z1github.com/yaroher/sqld/pkg/proto/sqld/v1/ir;irv1b\x06proto3"

var (
	file_sqld_v1_ir_common_proto_rawDescOnce sync.Once
	file_sqld_v1_ir_common_proto_rawDescData []byte
)

func file_sqld_v1_ir_common_proto_rawDescGZIP() []byte {
	file_sqld_v1_ir_common_proto_rawDescOnce.Do(func() {
		file_sqld_v1_ir_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sqld_v1_ir_common_proto_rawDesc), len(file_sqld_v1_ir_common_proto_rawDesc)))
	})
	return file_sqld_v1_ir_common_proto_rawDescData
}

var file_sqld_v1_ir_common_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_sqld_v1_ir_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sqld_v1_ir_common_proto_goTypes = []any{
	(Engine)(0),                 // 0: sqld.v1.ir.Engine
	(ObjectKind)(0),             // 1: sqld.v1.ir.ObjectKind
	(AnnotationTargetKind)(0),   // 2: sqld.v1.ir.AnnotationTargetKind
	(AnnotationArgType)(0),      // 3: sqld.v1.ir.AnnotationArgType
	(*QualifiedName)(nil),       // 4: sqld.v1.ir.QualifiedName
	(*ObjectRef)(nil),           // 5: sqld.v1.ir.ObjectRef
	(*SourceSpan)(nil),          // 6: sqld.v1.ir.SourceSpan
	(*AnnotationTargetRef)(nil), // 7: sqld.v1.ir.AnnotationTargetRef
	(*AnnotationArg)(nil),       // 8: sqld.v1.ir.AnnotationArg
	(*AnnotationValue)(nil),     // 9: sqld.v1.ir.AnnotationValue
	(*Metadata)(nil),            // 10: sqld.v1.ir.Metadata
	nil,                         // 11: sqld.v1.ir.Metadata.OptionsEntry
}
var file_sqld_v1_ir_common_proto_depIdxs = []int32{
	1,  // 0: sqld.v1.ir.ObjectRef.kind:type_name -> sqld.v1.ir.ObjectKind
	4,  // 1: sqld.v1.ir.ObjectRef.name:type_name -> sqld.v1.ir.QualifiedName
	2,  // 2: sqld.v1.ir.AnnotationTargetRef.kind:type_name -> sqld.v1.ir.AnnotationTargetKind
	5,  // 3: sqld.v1.ir.AnnotationTargetRef.object:type_name -> sqld.v1.ir.ObjectRef
	6,  // 4: sqld.v1.ir.AnnotationTargetRef.source:type_name -> sqld.v1.ir.SourceSpan
	3,  // 5: sqld.v1.ir.AnnotationArg.type:type_name -> sqld.v1.ir.AnnotationArgType
	7,  // 6: sqld.v1.ir.AnnotationValue.target:type_name -> sqld.v1.ir.AnnotationTargetRef
	8,  // 7: sqld.v1.ir.AnnotationValue.args:type_name -> sqld.v1.ir.AnnotationArg
	6,  // 8: sqld.v1.ir.AnnotationValue.source:type_name -> sqld.v1.ir.SourceSpan
	6,  // 9: sqld.v1.ir.Metadata.source:type_name -> sqld.v1.ir.SourceSpan
	11, // 10: sqld.v1.ir.Metadata.options:type_name -> sqld.v1.ir.Metadata.OptionsEntry
	9,  // 11: sqld.v1.ir.Metadata.annotations:type_name -> sqld.v1.ir.AnnotationValue
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_sqld_v1_ir_common_proto_init() }
func file_sqld_v1_ir_common_proto_init() {
	if File_sqld_v1_ir_common_proto != nil {
		return
	}
	file_sqld_v1_ir_common_proto_msgTypes[4].OneofWrappers = []any{
		(*AnnotationArg_StringValue)(nil),
		(*AnnotationArg_IntValue)(nil),
		(*AnnotationArg_FloatValue)(nil),
		(*AnnotationArg_BoolValue)(nil),
		(*AnnotationArg_DurationNanos)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sqld_v1_ir_common_proto_rawDesc), len(file_sqld_v1_ir_common_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sqld_v1_ir_common_proto_goTypes,
		DependencyIndexes: file_sqld_v1_ir_common_proto_depIdxs,
		EnumInfos:         file_sqld_v1_ir_common_proto_enumTypes,
		MessageInfos:      file_sqld_v1_ir_common_proto_msgTypes,
	}.Build()
	File_sqld_v1_ir_common_proto = out.File
	file_sqld_v1_ir_common_proto_goTypes = nil
	file_sqld_v1_ir_common_proto_depIdxs = nil
}
