// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: sqld/v1/ir/dml.proto

package irv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StatementKind is a best-effort classification of a RawStatement.
type StatementKind int32

const (
	StatementKind_STATEMENT_KIND_UNSPECIFIED StatementKind = 0
	StatementKind_STATEMENT_KIND_MERGE       StatementKind = 1 // MERGE not structured into MergeStmt
	StatementKind_STATEMENT_KIND_TRUNCATE    StatementKind = 2
	StatementKind_STATEMENT_KIND_COPY        StatementKind = 3
	StatementKind_STATEMENT_KIND_DDL         StatementKind = 4 // CREATE / ALTER / DROP / ...
	StatementKind_STATEMENT_KIND_TCL         StatementKind = 5 // BEGIN / COMMIT / ROLLBACK / SAVEPOINT
	StatementKind_STATEMENT_KIND_UTILITY     StatementKind = 6 // VACUUM / ANALYZE / SET / EXPLAIN / ...
	StatementKind_STATEMENT_KIND_OTHER       StatementKind = 7
)

// Enum value maps for StatementKind.
var (
	StatementKind_name = map[int32]string{
		0: "STATEMENT_KIND_UNSPECIFIED",
		1: "STATEMENT_KIND_MERGE",
		2: "STATEMENT_KIND_TRUNCATE",
		3: "STATEMENT_KIND_COPY",
		4: "STATEMENT_KIND_DDL",
		5: "STATEMENT_KIND_TCL",
		6: "STATEMENT_KIND_UTILITY",
		7: "STATEMENT_KIND_OTHER",
	}
	StatementKind_value = map[string]int32{
		"STATEMENT_KIND_UNSPECIFIED": 0,
		"STATEMENT_KIND_MERGE":       1,
		"STATEMENT_KIND_TRUNCATE":    2,
		"STATEMENT_KIND_COPY":        3,
		"STATEMENT_KIND_DDL":         4,
		"STATEMENT_KIND_TCL":         5,
		"STATEMENT_KIND_UTILITY":     6,
		"STATEMENT_KIND_OTHER":       7,
	}
)

func (x StatementKind) Enum() *StatementKind {
	p := new(StatementKind)
	*p = x
	return p
}

func (x StatementKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatementKind) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_dml_proto_enumTypes[0].Descriptor()
}

func (StatementKind) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_dml_proto_enumTypes[0]
}

func (x StatementKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatementKind.Descriptor instead.
func (StatementKind) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_dml_proto_rawDescGZIP(), []int{0}
}

type OnConflictAction int32

const (
	OnConflictAction_ON_CONFLICT_ACTION_UNSPECIFIED OnConflictAction = 0
	OnConflictAction_ON_CONFLICT_ACTION_DO_NOTHING  OnConflictAction = 1
	OnConflictAction_ON_CONFLICT_ACTION_DO_UPDATE   OnConflictAction = 2
)

// Enum value maps for OnConflictAction.
var (
	OnConflictAction_name = map[int32]string{
		0: "ON_CONFLICT_ACTION_UNSPECIFIED",
		1: "ON_CONFLICT_ACTION_DO_NOTHING",
		2: "ON_CONFLICT_ACTION_DO_UPDATE",
	}
	OnConflictAction_value = map[string]int32{
		"ON_CONFLICT_ACTION_UNSPECIFIED": 0,
		"ON_CONFLICT_ACTION_DO_NOTHING":  1,
		"ON_CONFLICT_ACTION_DO_UPDATE":   2,
	}
)

func (x OnConflictAction) Enum() *OnConflictAction {
	p := new(OnConflictAction)
	*p = x
	return p
}

func (x OnConflictAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OnConflictAction) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_dml_proto_enumTypes[1].Descriptor()
}

func (OnConflictAction) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_dml_proto_enumTypes[1]
}

func (x OnConflictAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OnConflictAction.Descriptor instead.
func (OnConflictAction) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_dml_proto_rawDescGZIP(), []int{1}
}

type MergeMatch int32

const (
	MergeMatch_MERGE_MATCH_UNSPECIFIED           MergeMatch = 0
	MergeMatch_MERGE_MATCH_MATCHED               MergeMatch = 1 // WHEN MATCHED
	MergeMatch_MERGE_MATCH_NOT_MATCHED_BY_TARGET MergeMatch = 2 // WHEN NOT MATCHED [BY TARGET]
	MergeMatch_MERGE_MATCH_NOT_MATCHED_BY_SOURCE MergeMatch = 3 // WHEN NOT MATCHED BY SOURCE (PG 17+)
)

// Enum value maps for MergeMatch.
var (
	MergeMatch_name = map[int32]string{
		0: "MERGE_MATCH_UNSPECIFIED",
		1: "MERGE_MATCH_MATCHED",
		2: "MERGE_MATCH_NOT_MATCHED_BY_TARGET",
		3: "MERGE_MATCH_NOT_MATCHED_BY_SOURCE",
	}
	MergeMatch_value = map[string]int32{
		"MERGE_MATCH_UNSPECIFIED":           0,
		"MERGE_MATCH_MATCHED":               1,
		"MERGE_MATCH_NOT_MATCHED_BY_TARGET": 2,
		"MERGE_MATCH_NOT_MATCHED_BY_SOURCE": 3,
	}
)

func (x MergeMatch) Enum() *MergeMatch {
	p := new(MergeMatch)
	*p = x
	return p
}

func (x MergeMatch) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MergeMatch) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_dml_proto_enumTypes[2].Descriptor()
}

func (MergeMatch) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_dml_proto_enumTypes[2]
}

func (x MergeMatch) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MergeMatch.Descriptor instead.
func (MergeMatch) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_dml_proto_rawDescGZIP(), []int{2}
}

type MergeActionKind int32

const (
	MergeActionKind_MERGE_ACTION_KIND_UNSPECIFIED MergeActionKind = 0
	MergeActionKind_MERGE_ACTION_KIND_INSERT      MergeActionKind = 1
	MergeActionKind_MERGE_ACTION_KIND_UPDATE      MergeActionKind = 2
	MergeActionKind_MERGE_ACTION_KIND_DELETE      MergeActionKind = 3
	MergeActionKind_MERGE_ACTION_KIND_DO_NOTHING  MergeActionKind = 4
)

// Enum value maps for MergeActionKind.
var (
	MergeActionKind_name = map[int32]string{
		0: "MERGE_ACTION_KIND_UNSPECIFIED",
		1: "MERGE_ACTION_KIND_INSERT",
		2: "MERGE_ACTION_KIND_UPDATE",
		3: "MERGE_ACTION_KIND_DELETE",
		4: "MERGE_ACTION_KIND_DO_NOTHING",
	}
	MergeActionKind_value = map[string]int32{
		"MERGE_ACTION_KIND_UNSPECIFIED": 0,
		"MERGE_ACTION_KIND_INSERT":      1,
		"MERGE_ACTION_KIND_UPDATE":      2,
		"MERGE_ACTION_KIND_DELETE":      3,
		"MERGE_ACTION_KIND_DO_NOTHING":  4,
	}
)

func (x MergeActionKind) Enum() *MergeActionKind {
	p := new(MergeActionKind)
	*p = x
	return p
}

func (x MergeActionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MergeActionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_dml_proto_enumTypes[3].Descriptor()
}

func (MergeActionKind) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_dml_proto_enumTypes[3]
}

func (x MergeActionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MergeActionKind.Descriptor instead.
func (MergeActionKind) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_dml_proto_rawDescGZIP(), []int{3}
}

// Statement is the top-level wrapper for any single DML statement.
type Statement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Statement:
	//
	//	*Statement_Select
	//	*Statement_Insert
	//	*Statement_Update
	//	*Statement_Delete
	//	*Statement_Merge
	//	*Statement_Raw
	Statement     isStatement_Statement `protobuf_oneof:"statement"`
	Meta          *Metadata             `protobuf:"bytes,15,opt,name=meta,proto3" json:"meta,omitempty"`
	NodeId        string                `protobuf:"bytes,21,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // stable host-assigned AST id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Statement) Reset() {
	*x = Statement{}
	mi := &file_sqld_v1_ir_dml_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Statement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statement) ProtoMessage() {}

func (x *Statement) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_dml_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statement.ProtoReflect.Descriptor instead.
func (*Statement) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_dml_proto_rawDescGZIP(), []int{0}
}

func (x *Statement) GetStatement() isStatement_Statement {
	if x != nil {
		return x.Statement
	}
	return nil
}

func (x *Statement) GetSelect() *SelectStmt {
	if x != nil {
		if x, ok := x.Statement.(*Statement_Select); ok {
			return x.Select
		}
	}
	return nil
}

func (x *Statement) GetInsert() *InsertStmt {
	if x != nil {
		if x, ok := x.Statement.(*Statement_Insert); ok {
			return x.Insert
		}
	}
	return nil
}

func (x *Statement) GetUpdate() *UpdateStmt {
	if x != nil {
		if x, ok := x.Statement.(*Statement_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *Statement) GetDelete() *DeleteStmt {
	if x != nil {
		if x, ok := x.Statement.(*Statement_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *Statement) GetMerge() *MergeStmt {
	if x != nil {
		if x, ok := x.Statement.(*Statement_Merge); ok {
			return x.Merge
		}
	}
	return nil
}

func (x *Statement) GetRaw() *RawStatement {
	if x != nil {
		if x, ok := x.Statement.(*Statement_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

func (x *Statement) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Statement) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type isStatement_Statement interface {
	isStatement_Statement()
}

type Statement_Select struct {
	Select *SelectStmt `protobuf:"bytes,1,opt,name=select,proto3,oneof"`
}

type Statement_Insert struct {
	Insert *InsertStmt `protobuf:"bytes,2,opt,name=insert,proto3,oneof"`
}

type Statement_Update struct {
	Update *UpdateStmt `protobuf:"bytes,3,opt,name=update,proto3,oneof"`
}

type Statement_Delete struct {
	Delete *DeleteStmt `protobuf:"bytes,4,opt,name=delete,proto3,oneof"`
}

type Statement_Merge struct {
	Merge *MergeStmt `protobuf:"bytes,5,opt,name=merge,proto3,oneof"`
}

type Statement_Raw struct {
	// Escape hatch for any statement not structured above (TRUNCATE, COPY,
	// DDL, transaction control, utility...). Keeps the statement level lossless.
	Raw *RawStatement `protobuf:"bytes,6,opt,name=raw,proto3,oneof"`
}

func (*Statement_Select) isStatement_Statement() {}

func (*Statement_Insert) isStatement_Statement() {}

func (*Statement_Update) isStatement_Statement() {}

func (*Statement_Delete) isStatement_Statement() {}

func (*Statement_Merge) isStatement_Statement() {}

func (*Statement_Raw) isStatement_Statement() {}

// RawStatement carries a statement the IR does not (yet) model structurally,
// as raw SQL plus a best-effort kind. Lossless fallback at the statement level.
type RawStatement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          StatementKind          `protobuf:"varint,1,opt,name=kind,proto3,enum=sqld.v1.ir.StatementKind" json:"kind,omitempty"`
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawStatement) Reset() {
	*x = RawStatement{}
	mi := &file_sqld_v1_ir_dml_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawStatement) ProtoMessage() {}

func (x *RawStatement) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_dml_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawStatement.ProtoReflect.Descriptor instead.
func (*RawStatement) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_dml_proto_rawDescGZIP(), []int{1}
}

func (x *RawStatement) GetKind() StatementKind {
	if x != nil {
		return x.Kind
	}
	return StatementKind_STATEMENT_KIND_UNSPECIFIED
}

func (x *RawStatement) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

// Assignment is `column = value` in UPDATE SET / ON CONFLICT DO UPDATE SET.
type Assignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`              // 1 col, or multi-col (a, b) = (...)
	Value         *Expr                  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`                  // scalar value or row/subquery for multi-col
	NodeId        string                 `protobuf:"bytes,21,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // stable host-assigned AST id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_sqld_v1_ir_dml_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_dml_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_dml_proto_rawDescGZIP(), []int{2}
}

func (x *Assignment) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Assignment) GetValue() *Expr {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Assignment) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// OnConflict models INSERT ... ON CONFLICT [target] action.
type OnConflict struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TargetColumns    []string               `protobuf:"bytes,1,rep,name=target_columns,json=targetColumns,proto3" json:"target_columns,omitempty"`          // ON CONFLICT (col, ...)
	TargetConstraint string                 `protobuf:"bytes,2,opt,name=target_constraint,json=targetConstraint,proto3" json:"target_constraint,omitempty"` // ON CONFLICT ON CONSTRAINT name
	IndexPredicate   *Expr                  `protobuf:"bytes,3,opt,name=index_predicate,json=indexPredicate,proto3" json:"index_predicate,omitempty"`       // partial-index predicate
	Action           OnConflictAction       `protobuf:"varint,4,opt,name=action,proto3,enum=sqld.v1.ir.OnConflictAction" json:"action,omitempty"`
	Set              []*Assignment          `protobuf:"bytes,5,rep,name=set,proto3" json:"set,omitempty"`                                    // DO UPDATE SET ...
	UpdateWhere      *Expr                  `protobuf:"bytes,6,opt,name=update_where,json=updateWhere,proto3" json:"update_where,omitempty"` // DO UPDATE ... WHERE ...
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OnConflict) Reset() {
	*x = OnConflict{}
	mi := &file_sqld_v1_ir_dml_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnConflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnConflict) ProtoMessage() {}

func (x *OnConflict) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_dml_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnConflict.ProtoReflect.Descriptor instead.
func (*OnConflict) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_dml_proto_rawDescGZIP(), []int{3}
}

func (x *OnConflict) GetTargetColumns() []string {
	if x != nil {
		return x.TargetColumns
	}
	return nil
}

func (x *OnConflict) GetTargetConstraint() string {
	if x != nil {
		return x.TargetConstraint
	}
	return ""
}

func (x *OnConflict) GetIndexPredicate() *Expr {
	if x != nil {
		return x.IndexPredicate
	}
	return nil
}

func (x *OnConflict) GetAction() OnConflictAction {
	if x != nil {
		return x.Action
	}
	return OnConflictAction_ON_CONFLICT_ACTION_UNSPECIFIED
}

func (x *OnConflict) GetSet() []*Assignment {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *OnConflict) GetUpdateWhere() *Expr {
	if x != nil {
		return x.UpdateWhere
	}
	return nil
}

type InsertStmt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	With          []*CommonTableExpr     `protobuf:"bytes,1,rep,name=with,proto3" json:"with,omitempty"`
	WithRecursive bool                   `protobuf:"varint,2,opt,name=with_recursive,json=withRecursive,proto3" json:"with_recursive,omitempty"`
	Table         *ObjectRef             `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	TableName     *QualifiedName         `protobuf:"bytes,4,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Alias         string                 `protobuf:"bytes,5,opt,name=alias,proto3" json:"alias,omitempty"`
	Columns       []string               `protobuf:"bytes,6,rep,name=columns,proto3" json:"columns,omitempty"` // target column list; empty => all
	// Types that are valid to be assigned to Source:
	//
	//	*InsertStmt_Values
	//	*InsertStmt_Query
	//	*InsertStmt_DefaultValues
	Source           isInsertStmt_Source `protobuf_oneof:"source"`
	OnConflict       *OnConflict         `protobuf:"bytes,10,opt,name=on_conflict,json=onConflict,proto3" json:"on_conflict,omitempty"`
	Returning        []*SelectTarget     `protobuf:"bytes,11,rep,name=returning,proto3" json:"returning,omitempty"`                                        // RETURNING ...
	OverridingSystem bool                `protobuf:"varint,12,opt,name=overriding_system,json=overridingSystem,proto3" json:"overriding_system,omitempty"` // OVERRIDING SYSTEM VALUE
	Meta             *Metadata           `protobuf:"bytes,15,opt,name=meta,proto3" json:"meta,omitempty"`
	NodeId           string              `protobuf:"bytes,21,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // stable host-assigned AST id
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InsertStmt) Reset() {
	*x = InsertStmt{}
	mi := &file_sqld_v1_ir_dml_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertStmt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertStmt) ProtoMessage() {}

func (x *InsertStmt) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_dml_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertStmt.ProtoReflect.Descriptor instead.
func (*InsertStmt) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_dml_proto_rawDescGZIP(), []int{4}
}

func (x *InsertStmt) GetWith() []*CommonTableExpr {
	if x != nil {
		return x.With
	}
	return nil
}

func (x *InsertStmt) GetWithRecursive() bool {
	if x != nil {
		return x.WithRecursive
	}
	return false
}

func (x *InsertStmt) GetTable() *ObjectRef {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *InsertStmt) GetTableName() *QualifiedName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *InsertStmt) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *InsertStmt) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *InsertStmt) GetSource() isInsertStmt_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *InsertStmt) GetValues() *Values {
	if x != nil {
		if x, ok := x.Source.(*InsertStmt_Values); ok {
			return x.Values
		}
	}
	return nil
}

func (x *InsertStmt) GetQuery() *SelectStmt {
	if x != nil {
		if x, ok := x.Source.(*InsertStmt_Query); ok {
			return x.Query
		}
	}
	return nil
}

func (x *InsertStmt) GetDefaultValues() bool {
	if x != nil {
		if x, ok := x.Source.(*InsertStmt_DefaultValues); ok {
			return x.DefaultValues
		}
	}
	return false
}

func (x *InsertStmt) GetOnConflict() *OnConflict {
	if x != nil {
		return x.OnConflict
	}
	return nil
}

func (x *InsertStmt) GetReturning() []*SelectTarget {
	if x != nil {
		return x.Returning
	}
	return nil
}

func (x *InsertStmt) GetOverridingSystem() bool {
	if x != nil {
		return x.OverridingSystem
	}
	return false
}

func (x *InsertStmt) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *InsertStmt) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type isInsertStmt_Source interface {
	isInsertStmt_Source()
}

type InsertStmt_Values struct {
	Values *Values `protobuf:"bytes,7,opt,name=values,proto3,oneof"` // VALUES (...), (...)
}

type InsertStmt_Query struct {
	Query *SelectStmt `protobuf:"bytes,8,opt,name=query,proto3,oneof"` // INSERT ... SELECT
}

type InsertStmt_DefaultValues struct {
	DefaultValues bool `protobuf:"varint,9,opt,name=default_values,json=defaultValues,proto3,oneof"` // DEFAULT VALUES
}

func (*InsertStmt_Values) isInsertStmt_Source() {}

func (*InsertStmt_Query) isInsertStmt_Source() {}

func (*InsertStmt_DefaultValues) isInsertStmt_Source() {}

type UpdateStmt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	With          []*CommonTableExpr     `protobuf:"bytes,1,rep,name=with,proto3" json:"with,omitempty"`
	WithRecursive bool                   `protobuf:"varint,2,opt,name=with_recursive,json=withRecursive,proto3" json:"with_recursive,omitempty"`
	Table         *ObjectRef             `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	TableName     *QualifiedName         `protobuf:"bytes,4,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Alias         string                 `protobuf:"bytes,5,opt,name=alias,proto3" json:"alias,omitempty"`
	Only          bool                   `protobuf:"varint,6,opt,name=only,proto3" json:"only,omitempty"` // UPDATE ONLY t
	Set           []*Assignment          `protobuf:"bytes,7,rep,name=set,proto3" json:"set,omitempty"`
	From          []*FromItem            `protobuf:"bytes,8,rep,name=from,proto3" json:"from,omitempty"` // UPDATE ... FROM ...
	Where         *Expr                  `protobuf:"bytes,9,opt,name=where,proto3" json:"where,omitempty"`
	Returning     []*SelectTarget        `protobuf:"bytes,10,rep,name=returning,proto3" json:"returning,omitempty"`
	Meta          *Metadata              `protobuf:"bytes,15,opt,name=meta,proto3" json:"meta,omitempty"`
	NodeId        string                 `protobuf:"bytes,21,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // stable host-assigned AST id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStmt) Reset() {
	*x = UpdateStmt{}
	mi := &file_sqld_v1_ir_dml_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStmt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStmt) ProtoMessage() {}

func (x *UpdateStmt) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_dml_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStmt.ProtoReflect.Descriptor instead.
func (*UpdateStmt) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_dml_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateStmt) GetWith() []*CommonTableExpr {
	if x != nil {
		return x.With
	}
	return nil
}

func (x *UpdateStmt) GetWithRecursive() bool {
	if x != nil {
		return x.WithRecursive
	}
	return false
}

func (x *UpdateStmt) GetTable() *ObjectRef {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *UpdateStmt) GetTableName() *QualifiedName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *UpdateStmt) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *UpdateStmt) GetOnly() bool {
	if x != nil {
		return x.Only
	}
	return false
}

func (x *UpdateStmt) GetSet() []*Assignment {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *UpdateStmt) GetFrom() []*FromItem {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *UpdateStmt) GetWhere() *Expr {
	if x != nil {
		return x.Where
	}
	return nil
}

func (x *UpdateStmt) GetReturning() []*SelectTarget {
	if x != nil {
		return x.Returning
	}
	return nil
}

func (x *UpdateStmt) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *UpdateStmt) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type DeleteStmt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	With          []*CommonTableExpr     `protobuf:"bytes,1,rep,name=with,proto3" json:"with,omitempty"`
	WithRecursive bool                   `protobuf:"varint,2,opt,name=with_recursive,json=withRecursive,proto3" json:"with_recursive,omitempty"`
	Table         *ObjectRef             `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	TableName     *QualifiedName         `protobuf:"bytes,4,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Alias         string                 `protobuf:"bytes,5,opt,name=alias,proto3" json:"alias,omitempty"`
	Only          bool                   `protobuf:"varint,6,opt,name=only,proto3" json:"only,omitempty"`  // DELETE FROM ONLY t
	Using         []*FromItem            `protobuf:"bytes,7,rep,name=using,proto3" json:"using,omitempty"` // USING ...
	Where         *Expr                  `protobuf:"bytes,8,opt,name=where,proto3" json:"where,omitempty"`
	Returning     []*SelectTarget        `protobuf:"bytes,9,rep,name=returning,proto3" json:"returning,omitempty"`
	Meta          *Metadata              `protobuf:"bytes,15,opt,name=meta,proto3" json:"meta,omitempty"`
	NodeId        string                 `protobuf:"bytes,21,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // stable host-assigned AST id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStmt) Reset() {
	*x = DeleteStmt{}
	mi := &file_sqld_v1_ir_dml_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStmt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStmt) ProtoMessage() {}

func (x *DeleteStmt) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_dml_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStmt.ProtoReflect.Descriptor instead.
func (*DeleteStmt) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_dml_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteStmt) GetWith() []*CommonTableExpr {
	if x != nil {
		return x.With
	}
	return nil
}

func (x *DeleteStmt) GetWithRecursive() bool {
	if x != nil {
		return x.WithRecursive
	}
	return false
}

func (x *DeleteStmt) GetTable() *ObjectRef {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *DeleteStmt) GetTableName() *QualifiedName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *DeleteStmt) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *DeleteStmt) GetOnly() bool {
	if x != nil {
		return x.Only
	}
	return false
}

func (x *DeleteStmt) GetUsing() []*FromItem {
	if x != nil {
		return x.Using
	}
	return nil
}

func (x *DeleteStmt) GetWhere() *Expr {
	if x != nil {
		return x.Where
	}
	return nil
}

func (x *DeleteStmt) GetReturning() []*SelectTarget {
	if x != nil {
		return x.Returning
	}
	return nil
}

func (x *DeleteStmt) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *DeleteStmt) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// MergeStmt is `MERGE INTO target USING source ON cond WHEN ... THEN ...`.
type MergeStmt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	With          []*CommonTableExpr     `protobuf:"bytes,1,rep,name=with,proto3" json:"with,omitempty"`
	WithRecursive bool                   `protobuf:"varint,2,opt,name=with_recursive,json=withRecursive,proto3" json:"with_recursive,omitempty"`
	Target        *ObjectRef             `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	TargetName    *QualifiedName         `protobuf:"bytes,4,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	TargetAlias   string                 `protobuf:"bytes,5,opt,name=target_alias,json=targetAlias,proto3" json:"target_alias,omitempty"`
	Source        *FromItem              `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"` // USING <table | subquery | values>
	On            *Expr                  `protobuf:"bytes,7,opt,name=on,proto3" json:"on,omitempty"`         // ON <join condition>
	Whens         []*MergeWhen           `protobuf:"bytes,8,rep,name=whens,proto3" json:"whens,omitempty"`
	Returning     []*SelectTarget        `protobuf:"bytes,9,rep,name=returning,proto3" json:"returning,omitempty"` // RETURNING (PG 17+)
	Meta          *Metadata              `protobuf:"bytes,15,opt,name=meta,proto3" json:"meta,omitempty"`
	NodeId        string                 `protobuf:"bytes,21,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // stable host-assigned AST id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeStmt) Reset() {
	*x = MergeStmt{}
	mi := &file_sqld_v1_ir_dml_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeStmt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeStmt) ProtoMessage() {}

func (x *MergeStmt) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_dml_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeStmt.ProtoReflect.Descriptor instead.
func (*MergeStmt) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_dml_proto_rawDescGZIP(), []int{7}
}

func (x *MergeStmt) GetWith() []*CommonTableExpr {
	if x != nil {
		return x.With
	}
	return nil
}

func (x *MergeStmt) GetWithRecursive() bool {
	if x != nil {
		return x.WithRecursive
	}
	return false
}

func (x *MergeStmt) GetTarget() *ObjectRef {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *MergeStmt) GetTargetName() *QualifiedName {
	if x != nil {
		return x.TargetName
	}
	return nil
}

func (x *MergeStmt) GetTargetAlias() string {
	if x != nil {
		return x.TargetAlias
	}
	return ""
}

func (x *MergeStmt) GetSource() *FromItem {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *MergeStmt) GetOn() *Expr {
	if x != nil {
		return x.On
	}
	return nil
}

func (x *MergeStmt) GetWhens() []*MergeWhen {
	if x != nil {
		return x.Whens
	}
	return nil
}

func (x *MergeStmt) GetReturning() []*SelectTarget {
	if x != nil {
		return x.Returning
	}
	return nil
}

func (x *MergeStmt) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *MergeStmt) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// MergeWhen is one WHEN clause with an optional extra `AND` condition.
type MergeWhen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         MergeMatch             `protobuf:"varint,1,opt,name=match,proto3,enum=sqld.v1.ir.MergeMatch" json:"match,omitempty"`
	Condition     *Expr                  `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"` // AND <condition>; unset if none
	Action        *MergeAction           `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeWhen) Reset() {
	*x = MergeWhen{}
	mi := &file_sqld_v1_ir_dml_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeWhen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeWhen) ProtoMessage() {}

func (x *MergeWhen) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_dml_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeWhen.ProtoReflect.Descriptor instead.
func (*MergeWhen) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_dml_proto_rawDescGZIP(), []int{8}
}

func (x *MergeWhen) GetMatch() MergeMatch {
	if x != nil {
		return x.Match
	}
	return MergeMatch_MERGE_MATCH_UNSPECIFIED
}

func (x *MergeWhen) GetCondition() *Expr {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *MergeWhen) GetAction() *MergeAction {
	if x != nil {
		return x.Action
	}
	return nil
}

// MergeAction is the THEN action of a WHEN clause.
type MergeAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          MergeActionKind        `protobuf:"varint,1,opt,name=kind,proto3,enum=sqld.v1.ir.MergeActionKind" json:"kind,omitempty"`
	Set           []*Assignment          `protobuf:"bytes,2,rep,name=set,proto3" json:"set,omitempty"`                                          // UPDATE SET ...
	InsertColumns []string               `protobuf:"bytes,3,rep,name=insert_columns,json=insertColumns,proto3" json:"insert_columns,omitempty"` // INSERT (cols)
	// Types that are valid to be assigned to InsertValues:
	//
	//	*MergeAction_Values
	//	*MergeAction_DefaultValues
	InsertValues     isMergeAction_InsertValues `protobuf_oneof:"insert_values"`
	OverridingSystem bool                       `protobuf:"varint,6,opt,name=overriding_system,json=overridingSystem,proto3" json:"overriding_system,omitempty"` // OVERRIDING SYSTEM VALUE
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MergeAction) Reset() {
	*x = MergeAction{}
	mi := &file_sqld_v1_ir_dml_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeAction) ProtoMessage() {}

func (x *MergeAction) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_dml_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeAction.ProtoReflect.Descriptor instead.
func (*MergeAction) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_dml_proto_rawDescGZIP(), []int{9}
}

func (x *MergeAction) GetKind() MergeActionKind {
	if x != nil {
		return x.Kind
	}
	return MergeActionKind_MERGE_ACTION_KIND_UNSPECIFIED
}

func (x *MergeAction) GetSet() []*Assignment {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *MergeAction) GetInsertColumns() []string {
	if x != nil {
		return x.InsertColumns
	}
	return nil
}

func (x *MergeAction) GetInsertValues() isMergeAction_InsertValues {
	if x != nil {
		return x.InsertValues
	}
	return nil
}

func (x *MergeAction) GetValues() *Values {
	if x != nil {
		if x, ok := x.InsertValues.(*MergeAction_Values); ok {
			return x.Values
		}
	}
	return nil
}

func (x *MergeAction) GetDefaultValues() bool {
	if x != nil {
		if x, ok := x.InsertValues.(*MergeAction_DefaultValues); ok {
			return x.DefaultValues
		}
	}
	return false
}

func (x *MergeAction) GetOverridingSystem() bool {
	if x != nil {
		return x.OverridingSystem
	}
	return false
}

type isMergeAction_InsertValues interface {
	isMergeAction_InsertValues()
}

type MergeAction_Values struct {
	Values *Values `protobuf:"bytes,4,opt,name=values,proto3,oneof"` // INSERT ... VALUES (...)
}

type MergeAction_DefaultValues struct {
	DefaultValues bool `protobuf:"varint,5,opt,name=default_values,json=defaultValues,proto3,oneof"` // INSERT DEFAULT VALUES
}

func (*MergeAction_Values) isMergeAction_InsertValues() {}

func (*MergeAction_DefaultValues) isMergeAction_InsertValues() {}

var File_sqld_v1_ir_dml_proto protoreflect.FileDescriptor

const file_sqld_v1_ir_dml_proto_rawDesc = "" +
	"\n" +
	"\x14sqld/v1/ir/dml.proto\x12\n" +
	"sqld.v1.ir\x1a\x17sqld/v1/ir/common.proto\x1a\x15sqld/v1/ir/expr.proto\"\x80\x03\n" +
	"\tStatement\x120\n" +
	"\x06select\x18\x01 \x01(\v2\x16.sqld.v1.ir.SelectStmtH\x00R\x06select\x120\n" +
	"\x06insert\x18\x02 \x01(\v2\x16.sqld.v1.ir.InsertStmtH\x00R\x06insert\x120\n" +
	"\x06update\x18\x03 \x01(\v2\x16.sqld.v1.ir.UpdateStmtH\x00R\x06update\x120\n" +
	"\x06delete\x18\x04 \x01(\v2\x16.sqld.v1.ir.DeleteStmtH\x00R\x06delete\x12-\n" +
	"\x05merge\x18\x05 \x01(\v2\x15.sqld.v1.ir.MergeStmtH\x00R\x05merge\x12,\n" +
	"\x03raw\x18\x06 \x01(\v2\x18.sqld.v1.ir.RawStatementH\x00R\x03raw\x12(\n" +
	"\x04meta\x18\x0f \x01(\v2\x14.sqld.v1.ir.MetadataR\x04meta\x12\x17\n" +
	"\anode_id\x18\x15 \x01(\tR\x06nodeIdB\v\n" +
	"\tstatement\"O\n" +
	"\fRawStatement\x12-\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x19.sqld.v1.ir.StatementKindR\x04kind\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\"g\n" +
	"\n" +
	"Assignment\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.sqld.v1.ir.ExprR\x05value\x12\x17\n" +
	"\anode_id\x18\x15 \x01(\tR\x06nodeId\"\xb0\x02\n" +
	"\n" +
	"OnConflict\x12%\n" +
	"\x0etarget_columns\x18\x01 \x03(\tR\rtargetColumns\x12+\n" +
	"\x11target_constraint\x18\x02 \x01(\tR\x10targetConstraint\x129\n" +
	"\x0findex_predicate\x18\x03 \x01(\v2\x10.sqld.v1.ir.ExprR\x0eindexPredicate\x124\n" +
	"\x06action\x18\x04 \x01(\x0e2\x1c.sqld.v1.ir.OnConflictActionR\x06action\x12(\n" +
	"\x03set\x18\x05 \x03(\v2\x16.sqld.v1.ir.AssignmentR\x03set\x123\n" +
	"\fupdate_where\x18\x06 \x01(\v2\x10.sqld.v1.ir.ExprR\vupdateWhere\"\xed\x04\n" +
	"\n" +
	"InsertStmt\x12/\n" +
	"\x04with\x18\x01 \x03(\v2\x1b.sqld.v1.ir.CommonTableExprR\x04with\x12%\n" +
	"\x0ewith_recursive\x18\x02 \x01(\bR\rwithRecursive\x12+\n" +
	"\x05table\x18\x03 \x01(\v2\x15.sqld.v1.ir.ObjectRefR\x05table\x128\n" +
	"\n" +
	"table_name\x18\x04 \x01(\v2\x19.sqld.v1.ir.QualifiedNameR\ttableName\x12\x14\n" +
	"\x05alias\x18\x05 \x01(\tR\x05alias\x12\x18\n" +
	"\acolumns\x18\x06 \x03(\tR\acolumns\x12,\n" +
	"\x06values\x18\a \x01(\v2\x12.sqld.v1.ir.ValuesH\x00R\x06values\x12.\n" +
	"\x05query\x18\b \x01(\v2\x16.sqld.v1.ir.SelectStmtH\x00R\x05query\x12'\n" +
	"\x0edefault_values\x18\t \x01(\bH\x00R\rdefaultValues\x127\n" +
	"\von_conflict\x18\n" +
	" \x01(\v2\x16.sqld.v1.ir.OnConflictR\n" +
	"onConflict\x126\n" +
	"\treturning\x18\v \x03(\v2\x18.sqld.v1.ir.SelectTargetR\treturning\x12+\n" +
	"\x11overriding_system\x18\f \x01(\bR\x10overridingSystem\x12(\n" +
	"\x04meta\x18\x0f \x01(\v2\x14.sqld.v1.ir.MetadataR\x04meta\x12\x17\n" +
	"\anode_id\x18\x15 \x01(\tR\x06nodeIdB\b\n" +
	"\x06source\"\xec\x03\n" +
	"\n" +
	"UpdateStmt\x12/\n" +
	"\x04with\x18\x01 \x03(\v2\x1b.sqld.v1.ir.CommonTableExprR\x04with\x12%\n" +
	"\x0ewith_recursive\x18\x02 \x01(\bR\rwithRecursive\x12+\n" +
	"\x05table\x18\x03 \x01(\v2\x15.sqld.v1.ir.ObjectRefR\x05table\x128\n" +
	"\n" +
	"table_name\x18\x04 \x01(\v2\x19.sqld.v1.ir.QualifiedNameR\ttableName\x12\x14\n" +
	"\x05alias\x18\x05 \x01(\tR\x05alias\x12\x12\n" +
	"\x04only\x18\x06 \x01(\bR\x04only\x12(\n" +
	"\x03set\x18\a \x03(\v2\x16.sqld.v1.ir.AssignmentR\x03set\x12(\n" +
	"\x04from\x18\b \x03(\v2\x14.sqld.v1.ir.FromItemR\x04from\x12&\n" +
	"\x05where\x18\t \x01(\v2\x10.sqld.v1.ir.ExprR\x05where\x126\n" +
	"\treturning\x18\n" +
	" \x03(\v2\x18.sqld.v1.ir.SelectTargetR\treturning\x12(\n" +
	"\x04meta\x18\x0f \x01(\v2\x14.sqld.v1.ir.MetadataR\x04meta\x12\x17\n" +
	"\anode_id\x18\x15 \x01(\tR\x06nodeId\"\xc4\x03\n" +
	"\n" +
	"DeleteStmt\x12/\n" +
	"\x04with\x18\x01 \x03(\v2\x1b.sqld.v1.ir.CommonTableExprR\x04with\x12%\n" +
	"\x0ewith_recursive\x18\x02 \x01(\bR\rwithRecursive\x12+\n" +
	"\x05table\x18\x03 \x01(\v2\x15.sqld.v1.ir.ObjectRefR\x05table\x128\n" +
	"\n" +
	"table_name\x18\x04 \x01(\v2\x19.sqld.v1.ir.QualifiedNameR\ttableName\x12\x14\n" +
	"\x05alias\x18\x05 \x01(\tR\x05alias\x12\x12\n" +
	"\x04only\x18\x06 \x01(\bR\x04only\x12*\n" +
	"\x05using\x18\a \x03(\v2\x14.sqld.v1.ir.FromItemR\x05using\x12&\n" +
	"\x05where\x18\b \x01(\v2\x10.sqld.v1.ir.ExprR\x05where\x126\n" +
	"\treturning\x18\t \x03(\v2\x18.sqld.v1.ir.SelectTargetR\treturning\x12(\n" +
	"\x04meta\x18\x0f \x01(\v2\x14.sqld.v1.ir.MetadataR\x04meta\x12\x17\n" +
	"\anode_id\x18\x15 \x01(\tR\x06nodeId\"\xe9\x03\n" +
	"\tMergeStmt\x12/\n" +
	"\x04with\x18\x01 \x03(\v2\x1b.sqld.v1.ir.CommonTableExprR\x04with\x12%\n" +
	"\x0ewith_recursive\x18\x02 \x01(\bR\rwithRecursive\x12-\n" +
	"\x06target\x18\x03 \x01(\v2\x15.sqld.v1.ir.ObjectRefR\x06target\x12:\n" +
	"\vtarget_name\x18\x04 \x01(\v2\x19.sqld.v1.ir.QualifiedNameR\n" +
	"targetName\x12!\n" +
	"\ftarget_alias\x18\x05 \x01(\tR\vtargetAlias\x12,\n" +
	"\x06source\x18\x06 \x01(\v2\x14.sqld.v1.ir.FromItemR\x06source\x12 \n" +
	"\x02on\x18\a \x01(\v2\x10.sqld.v1.ir.ExprR\x02on\x12+\n" +
	"\x05whens\x18\b \x03(\v2\x15.sqld.v1.ir.MergeWhenR\x05whens\x126\n" +
	"\treturning\x18\t \x03(\v2\x18.sqld.v1.ir.SelectTargetR\treturning\x12(\n" +
	"\x04meta\x18\x0f \x01(\v2\x14.sqld.v1.ir.MetadataR\x04meta\x12\x17\n" +
	"\anode_id\x18\x15 \x01(\tR\x06nodeId\"\x9a\x01\n" +
	"\tMergeWhen\x12,\n" +
	"\x05match\x18\x01 \x01(\x0e2\x16.sqld.v1.ir.MergeMatchR\x05match\x12.\n" +
	"\tcondition\x18\x02 \x01(\v2\x10.sqld.v1.ir.ExprR\tcondition\x12/\n" +
	"\x06action\x18\x03 \x01(\v2\x17.sqld.v1.ir.MergeActionR\x06action\"\xa4\x02\n" +
	"\vMergeAction\x12/\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1b.sqld.v1.ir.MergeActionKindR\x04kind\x12(\n" +
	"\x03set\x18\x02 \x03(\v2\x16.sqld.v1.ir.AssignmentR\x03set\x12%\n" +
	"\x0einsert_columns\x18\x03 \x03(\tR\rinsertColumns\x12,\n" +
	"\x06values\x18\x04 \x01(\v2\x12.sqld.v1.ir.ValuesH\x00R\x06values\x12'\n" +
	"\x0edefault_values\x18\x05 \x01(\bH\x00R\rdefaultValues\x12+\n" +
	"\x11overriding_system\x18\x06 \x01(\bR\x10overridingSystemB\x0f\n" +
	"\rinsert_values*\xe5\x01\n" +
	"\rStatementKind\x12\x1e\n" +
	"\x1aSTATEMENT_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14STATEMENT_KIND_MERGE\x10\x01\x12\x1b\n" +
	"\x17STATEMENT_KIND_TRUNCATE\x10\x02\x12\x17\n" +
	"\x13STATEMENT_KIND_COPY\x10\x03\x12\x16\n" +
	"\x12STATEMENT_KIND_DDL\x10\x04\x12\x16\n" +
	"\x12STATEMENT_KIND_TCL\x10\x05\x12\x1a\n" +
	"\x16STATEMENT_KIND_UTILITY\x10\x06\x12\x18\n" +
	"\x14STATEMENT_KIND_OTHER\x10\a*{\n" +
	"\x10OnConflictAction\x12\"\n" +
	"\x1eON_CONFLICT_ACTION_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dON_CONFLICT_ACTION_DO_NOTHING\x10\x01\x12 \n" +
	"\x1cON_CONFLICT_ACTION_DO_UPDATE\x10\x02*\x90\x01\n" +
	"\n" +
	"MergeMatch\x12\x1b\n" +
	"\x17MERGE_MATCH_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MERGE_MATCH_MATCHED\x10\x01\x12%\n" +
	"!MERGE_MATCH_NOT_MATCHED_BY_TARGET\x10\x02\x12%\n" +
	"!MERGE_MATCH_NOT_MATCHED_BY_SOURCE\x10\x03*\xb0\x01\n" +
	"\x0fMergeActionKind\x12!\n" +
	"\x1dMERGE_ACTION_KIND_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18MERGE_ACTION_KIND_INSERT\x10\x01\x12\x1c\n" +
	"\x18MERGE_ACTION_KIND_UPDATE\x10\x02\x12\x1c\n" +
	"\x18MERGE_ACTION_KIND_DELETE\x10\x03\x12 \n" +
	"\x1cMERGE_ACTION_KIND_DO_NOTHING\x10\x04B3Z1github.com/gopherex/sqld/pkg/proto/sqld/v1/ir;irv1b\x06proto3"

var (
	file_sqld_v1_ir_dml_proto_rawDescOnce sync.Once
	file_sqld_v1_ir_dml_proto_rawDescData []byte
)

func file_sqld_v1_ir_dml_proto_rawDescGZIP() []byte {
	file_sqld_v1_ir_dml_proto_rawDescOnce.Do(func() {
		file_sqld_v1_ir_dml_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sqld_v1_ir_dml_proto_rawDesc), len(file_sqld_v1_ir_dml_proto_rawDesc)))
	})
	return file_sqld_v1_ir_dml_proto_rawDescData
}

var file_sqld_v1_ir_dml_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_sqld_v1_ir_dml_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_sqld_v1_ir_dml_proto_goTypes = []any{
	(StatementKind)(0),      // 0: sqld.v1.ir.StatementKind
	(OnConflictAction)(0),   // 1: sqld.v1.ir.OnConflictAction
	(MergeMatch)(0),         // 2: sqld.v1.ir.MergeMatch
	(MergeActionKind)(0),    // 3: sqld.v1.ir.MergeActionKind
	(*Statement)(nil),       // 4: sqld.v1.ir.Statement
	(*RawStatement)(nil),    // 5: sqld.v1.ir.RawStatement
	(*Assignment)(nil),      // 6: sqld.v1.ir.Assignment
	(*OnConflict)(nil),      // 7: sqld.v1.ir.OnConflict
	(*InsertStmt)(nil),      // 8: sqld.v1.ir.InsertStmt
	(*UpdateStmt)(nil),      // 9: sqld.v1.ir.UpdateStmt
	(*DeleteStmt)(nil),      // 10: sqld.v1.ir.DeleteStmt
	(*MergeStmt)(nil),       // 11: sqld.v1.ir.MergeStmt
	(*MergeWhen)(nil),       // 12: sqld.v1.ir.MergeWhen
	(*MergeAction)(nil),     // 13: sqld.v1.ir.MergeAction
	(*SelectStmt)(nil),      // 14: sqld.v1.ir.SelectStmt
	(*Metadata)(nil),        // 15: sqld.v1.ir.Metadata
	(*Expr)(nil),            // 16: sqld.v1.ir.Expr
	(*CommonTableExpr)(nil), // 17: sqld.v1.ir.CommonTableExpr
	(*ObjectRef)(nil),       // 18: sqld.v1.ir.ObjectRef
	(*QualifiedName)(nil),   // 19: sqld.v1.ir.QualifiedName
	(*Values)(nil),          // 20: sqld.v1.ir.Values
	(*SelectTarget)(nil),    // 21: sqld.v1.ir.SelectTarget
	(*FromItem)(nil),        // 22: sqld.v1.ir.FromItem
}
var file_sqld_v1_ir_dml_proto_depIdxs = []int32{
	14, // 0: sqld.v1.ir.Statement.select:type_name -> sqld.v1.ir.SelectStmt
	8,  // 1: sqld.v1.ir.Statement.insert:type_name -> sqld.v1.ir.InsertStmt
	9,  // 2: sqld.v1.ir.Statement.update:type_name -> sqld.v1.ir.UpdateStmt
	10, // 3: sqld.v1.ir.Statement.delete:type_name -> sqld.v1.ir.DeleteStmt
	11, // 4: sqld.v1.ir.Statement.merge:type_name -> sqld.v1.ir.MergeStmt
	5,  // 5: sqld.v1.ir.Statement.raw:type_name -> sqld.v1.ir.RawStatement
	15, // 6: sqld.v1.ir.Statement.meta:type_name -> sqld.v1.ir.Metadata
	0,  // 7: sqld.v1.ir.RawStatement.kind:type_name -> sqld.v1.ir.StatementKind
	16, // 8: sqld.v1.ir.Assignment.value:type_name -> sqld.v1.ir.Expr
	16, // 9: sqld.v1.ir.OnConflict.index_predicate:type_name -> sqld.v1.ir.Expr
	1,  // 10: sqld.v1.ir.OnConflict.action:type_name -> sqld.v1.ir.OnConflictAction
	6,  // 11: sqld.v1.ir.OnConflict.set:type_name -> sqld.v1.ir.Assignment
	16, // 12: sqld.v1.ir.OnConflict.update_where:type_name -> sqld.v1.ir.Expr
	17, // 13: sqld.v1.ir.InsertStmt.with:type_name -> sqld.v1.ir.CommonTableExpr
	18, // 14: sqld.v1.ir.InsertStmt.table:type_name -> sqld.v1.ir.ObjectRef
	19, // 15: sqld.v1.ir.InsertStmt.table_name:type_name -> sqld.v1.ir.QualifiedName
	20, // 16: sqld.v1.ir.InsertStmt.values:type_name -> sqld.v1.ir.Values
	14, // 17: sqld.v1.ir.InsertStmt.query:type_name -> sqld.v1.ir.SelectStmt
	7,  // 18: sqld.v1.ir.InsertStmt.on_conflict:type_name -> sqld.v1.ir.OnConflict
	21, // 19: sqld.v1.ir.InsertStmt.returning:type_name -> sqld.v1.ir.SelectTarget
	15, // 20: sqld.v1.ir.InsertStmt.meta:type_name -> sqld.v1.ir.Metadata
	17, // 21: sqld.v1.ir.UpdateStmt.with:type_name -> sqld.v1.ir.CommonTableExpr
	18, // 22: sqld.v1.ir.UpdateStmt.table:type_name -> sqld.v1.ir.ObjectRef
	19, // 23: sqld.v1.ir.UpdateStmt.table_name:type_name -> sqld.v1.ir.QualifiedName
	6,  // 24: sqld.v1.ir.UpdateStmt.set:type_name -> sqld.v1.ir.Assignment
	22, // 25: sqld.v1.ir.UpdateStmt.from:type_name -> sqld.v1.ir.FromItem
	16, // 26: sqld.v1.ir.UpdateStmt.where:type_name -> sqld.v1.ir.Expr
	21, // 27: sqld.v1.ir.UpdateStmt.returning:type_name -> sqld.v1.ir.SelectTarget
	15, // 28: sqld.v1.ir.UpdateStmt.meta:type_name -> sqld.v1.ir.Metadata
	17, // 29: sqld.v1.ir.DeleteStmt.with:type_name -> sqld.v1.ir.CommonTableExpr
	18, // 30: sqld.v1.ir.DeleteStmt.table:type_name -> sqld.v1.ir.ObjectRef
	19, // 31: sqld.v1.ir.DeleteStmt.table_name:type_name -> sqld.v1.ir.QualifiedName
	22, // 32: sqld.v1.ir.DeleteStmt.using:type_name -> sqld.v1.ir.FromItem
	16, // 33: sqld.v1.ir.DeleteStmt.where:type_name -> sqld.v1.ir.Expr
	21, // 34: sqld.v1.ir.DeleteStmt.returning:type_name -> sqld.v1.ir.SelectTarget
	15, // 35: sqld.v1.ir.DeleteStmt.meta:type_name -> sqld.v1.ir.Metadata
	17, // 36: sqld.v1.ir.MergeStmt.with:type_name -> sqld.v1.ir.CommonTableExpr
	18, // 37: sqld.v1.ir.MergeStmt.target:type_name -> sqld.v1.ir.ObjectRef
	19, // 38: sqld.v1.ir.MergeStmt.target_name:type_name -> sqld.v1.ir.QualifiedName
	22, // 39: sqld.v1.ir.MergeStmt.source:type_name -> sqld.v1.ir.FromItem
	16, // 40: sqld.v1.ir.MergeStmt.on:type_name -> sqld.v1.ir.Expr
	12, // 41: sqld.v1.ir.MergeStmt.whens:type_name -> sqld.v1.ir.MergeWhen
	21, // 42: sqld.v1.ir.MergeStmt.returning:type_name -> sqld.v1.ir.SelectTarget
	15, // 43: sqld.v1.ir.MergeStmt.meta:type_name -> sqld.v1.ir.Metadata
	2,  // 44: sqld.v1.ir.MergeWhen.match:type_name -> sqld.v1.ir.MergeMatch
	16, // 45: sqld.v1.ir.MergeWhen.condition:type_name -> sqld.v1.ir.Expr
	13, // 46: sqld.v1.ir.MergeWhen.action:type_name -> sqld.v1.ir.MergeAction
	3,  // 47: sqld.v1.ir.MergeAction.kind:type_name -> sqld.v1.ir.MergeActionKind
	6,  // 48: sqld.v1.ir.MergeAction.set:type_name -> sqld.v1.ir.Assignment
	20, // 49: sqld.v1.ir.MergeAction.values:type_name -> sqld.v1.ir.Values
	50, // [50:50] is the sub-list for method output_type
	50, // [50:50] is the sub-list for method input_type
	50, // [50:50] is the sub-list for extension type_name
	50, // [50:50] is the sub-list for extension extendee
	0,  // [0:50] is the sub-list for field type_name
}

func init() { file_sqld_v1_ir_dml_proto_init() }
func file_sqld_v1_ir_dml_proto_init() {
	if File_sqld_v1_ir_dml_proto != nil {
		return
	}
	file_sqld_v1_ir_common_proto_init()
	file_sqld_v1_ir_expr_proto_init()
	file_sqld_v1_ir_dml_proto_msgTypes[0].OneofWrappers = []any{
		(*Statement_Select)(nil),
		(*Statement_Insert)(nil),
		(*Statement_Update)(nil),
		(*Statement_Delete)(nil),
		(*Statement_Merge)(nil),
		(*Statement_Raw)(nil),
	}
	file_sqld_v1_ir_dml_proto_msgTypes[4].OneofWrappers = []any{
		(*InsertStmt_Values)(nil),
		(*InsertStmt_Query)(nil),
		(*InsertStmt_DefaultValues)(nil),
	}
	file_sqld_v1_ir_dml_proto_msgTypes[9].OneofWrappers = []any{
		(*MergeAction_Values)(nil),
		(*MergeAction_DefaultValues)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sqld_v1_ir_dml_proto_rawDesc), len(file_sqld_v1_ir_dml_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sqld_v1_ir_dml_proto_goTypes,
		DependencyIndexes: file_sqld_v1_ir_dml_proto_depIdxs,
		EnumInfos:         file_sqld_v1_ir_dml_proto_enumTypes,
		MessageInfos:      file_sqld_v1_ir_dml_proto_msgTypes,
	}.Build()
	File_sqld_v1_ir_dml_proto = out.File
	file_sqld_v1_ir_dml_proto_goTypes = nil
	file_sqld_v1_ir_dml_proto_depIdxs = nil
}
