// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: sqld/v1/ir/expr.proto

package irv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubqueryKind int32

const (
	SubqueryKind_SUBQUERY_KIND_UNSPECIFIED SubqueryKind = 0
	SubqueryKind_SUBQUERY_KIND_SCALAR      SubqueryKind = 1 // (SELECT ...)
	SubqueryKind_SUBQUERY_KIND_EXISTS      SubqueryKind = 2 // EXISTS (SELECT ...)
	SubqueryKind_SUBQUERY_KIND_IN          SubqueryKind = 3 // expr IN (SELECT ...)
	SubqueryKind_SUBQUERY_KIND_ANY         SubqueryKind = 4 // expr op ANY (SELECT ...)
	SubqueryKind_SUBQUERY_KIND_ALL         SubqueryKind = 5 // expr op ALL (SELECT ...)
)

// Enum value maps for SubqueryKind.
var (
	SubqueryKind_name = map[int32]string{
		0: "SUBQUERY_KIND_UNSPECIFIED",
		1: "SUBQUERY_KIND_SCALAR",
		2: "SUBQUERY_KIND_EXISTS",
		3: "SUBQUERY_KIND_IN",
		4: "SUBQUERY_KIND_ANY",
		5: "SUBQUERY_KIND_ALL",
	}
	SubqueryKind_value = map[string]int32{
		"SUBQUERY_KIND_UNSPECIFIED": 0,
		"SUBQUERY_KIND_SCALAR":      1,
		"SUBQUERY_KIND_EXISTS":      2,
		"SUBQUERY_KIND_IN":          3,
		"SUBQUERY_KIND_ANY":         4,
		"SUBQUERY_KIND_ALL":         5,
	}
)

func (x SubqueryKind) Enum() *SubqueryKind {
	p := new(SubqueryKind)
	*p = x
	return p
}

func (x SubqueryKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubqueryKind) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_expr_proto_enumTypes[0].Descriptor()
}

func (SubqueryKind) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_expr_proto_enumTypes[0]
}

func (x SubqueryKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubqueryKind.Descriptor instead.
func (SubqueryKind) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{0}
}

type SortOrder int32

const (
	SortOrder_SORT_ORDER_UNSPECIFIED SortOrder = 0
	SortOrder_SORT_ORDER_ASC         SortOrder = 1
	SortOrder_SORT_ORDER_DESC        SortOrder = 2
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_UNSPECIFIED",
		1: "SORT_ORDER_ASC",
		2: "SORT_ORDER_DESC",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_UNSPECIFIED": 0,
		"SORT_ORDER_ASC":         1,
		"SORT_ORDER_DESC":        2,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_expr_proto_enumTypes[1].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_expr_proto_enumTypes[1]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{1}
}

type NullsOrder int32

const (
	NullsOrder_NULLS_ORDER_UNSPECIFIED NullsOrder = 0
	NullsOrder_NULLS_ORDER_FIRST       NullsOrder = 1
	NullsOrder_NULLS_ORDER_LAST        NullsOrder = 2
)

// Enum value maps for NullsOrder.
var (
	NullsOrder_name = map[int32]string{
		0: "NULLS_ORDER_UNSPECIFIED",
		1: "NULLS_ORDER_FIRST",
		2: "NULLS_ORDER_LAST",
	}
	NullsOrder_value = map[string]int32{
		"NULLS_ORDER_UNSPECIFIED": 0,
		"NULLS_ORDER_FIRST":       1,
		"NULLS_ORDER_LAST":        2,
	}
)

func (x NullsOrder) Enum() *NullsOrder {
	p := new(NullsOrder)
	*p = x
	return p
}

func (x NullsOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NullsOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_expr_proto_enumTypes[2].Descriptor()
}

func (NullsOrder) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_expr_proto_enumTypes[2]
}

func (x NullsOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NullsOrder.Descriptor instead.
func (NullsOrder) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{2}
}

type SetOpKind int32

const (
	SetOpKind_SET_OP_KIND_UNSPECIFIED SetOpKind = 0
	SetOpKind_SET_OP_KIND_UNION       SetOpKind = 1
	SetOpKind_SET_OP_KIND_INTERSECT   SetOpKind = 2
	SetOpKind_SET_OP_KIND_EXCEPT      SetOpKind = 3
)

// Enum value maps for SetOpKind.
var (
	SetOpKind_name = map[int32]string{
		0: "SET_OP_KIND_UNSPECIFIED",
		1: "SET_OP_KIND_UNION",
		2: "SET_OP_KIND_INTERSECT",
		3: "SET_OP_KIND_EXCEPT",
	}
	SetOpKind_value = map[string]int32{
		"SET_OP_KIND_UNSPECIFIED": 0,
		"SET_OP_KIND_UNION":       1,
		"SET_OP_KIND_INTERSECT":   2,
		"SET_OP_KIND_EXCEPT":      3,
	}
)

func (x SetOpKind) Enum() *SetOpKind {
	p := new(SetOpKind)
	*p = x
	return p
}

func (x SetOpKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetOpKind) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_expr_proto_enumTypes[3].Descriptor()
}

func (SetOpKind) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_expr_proto_enumTypes[3]
}

func (x SetOpKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetOpKind.Descriptor instead.
func (SetOpKind) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{3}
}

type CteMaterialization int32

const (
	CteMaterialization_CTE_MATERIALIZATION_UNSPECIFIED      CteMaterialization = 0 // default (planner decides)
	CteMaterialization_CTE_MATERIALIZATION_MATERIALIZED     CteMaterialization = 1
	CteMaterialization_CTE_MATERIALIZATION_NOT_MATERIALIZED CteMaterialization = 2
)

// Enum value maps for CteMaterialization.
var (
	CteMaterialization_name = map[int32]string{
		0: "CTE_MATERIALIZATION_UNSPECIFIED",
		1: "CTE_MATERIALIZATION_MATERIALIZED",
		2: "CTE_MATERIALIZATION_NOT_MATERIALIZED",
	}
	CteMaterialization_value = map[string]int32{
		"CTE_MATERIALIZATION_UNSPECIFIED":      0,
		"CTE_MATERIALIZATION_MATERIALIZED":     1,
		"CTE_MATERIALIZATION_NOT_MATERIALIZED": 2,
	}
)

func (x CteMaterialization) Enum() *CteMaterialization {
	p := new(CteMaterialization)
	*p = x
	return p
}

func (x CteMaterialization) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CteMaterialization) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_expr_proto_enumTypes[4].Descriptor()
}

func (CteMaterialization) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_expr_proto_enumTypes[4]
}

func (x CteMaterialization) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CteMaterialization.Descriptor instead.
func (CteMaterialization) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{4}
}

type LockStrength int32

const (
	LockStrength_LOCK_STRENGTH_UNSPECIFIED   LockStrength = 0
	LockStrength_LOCK_STRENGTH_UPDATE        LockStrength = 1 // FOR UPDATE
	LockStrength_LOCK_STRENGTH_NO_KEY_UPDATE LockStrength = 2 // FOR NO KEY UPDATE
	LockStrength_LOCK_STRENGTH_SHARE         LockStrength = 3 // FOR SHARE
	LockStrength_LOCK_STRENGTH_KEY_SHARE     LockStrength = 4 // FOR KEY SHARE
)

// Enum value maps for LockStrength.
var (
	LockStrength_name = map[int32]string{
		0: "LOCK_STRENGTH_UNSPECIFIED",
		1: "LOCK_STRENGTH_UPDATE",
		2: "LOCK_STRENGTH_NO_KEY_UPDATE",
		3: "LOCK_STRENGTH_SHARE",
		4: "LOCK_STRENGTH_KEY_SHARE",
	}
	LockStrength_value = map[string]int32{
		"LOCK_STRENGTH_UNSPECIFIED":   0,
		"LOCK_STRENGTH_UPDATE":        1,
		"LOCK_STRENGTH_NO_KEY_UPDATE": 2,
		"LOCK_STRENGTH_SHARE":         3,
		"LOCK_STRENGTH_KEY_SHARE":     4,
	}
)

func (x LockStrength) Enum() *LockStrength {
	p := new(LockStrength)
	*p = x
	return p
}

func (x LockStrength) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LockStrength) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_expr_proto_enumTypes[5].Descriptor()
}

func (LockStrength) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_expr_proto_enumTypes[5]
}

func (x LockStrength) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LockStrength.Descriptor instead.
func (LockStrength) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{5}
}

type LockWaitPolicy int32

const (
	LockWaitPolicy_LOCK_WAIT_POLICY_UNSPECIFIED LockWaitPolicy = 0 // wait (default)
	LockWaitPolicy_LOCK_WAIT_POLICY_NOWAIT      LockWaitPolicy = 1
	LockWaitPolicy_LOCK_WAIT_POLICY_SKIP_LOCKED LockWaitPolicy = 2
)

// Enum value maps for LockWaitPolicy.
var (
	LockWaitPolicy_name = map[int32]string{
		0: "LOCK_WAIT_POLICY_UNSPECIFIED",
		1: "LOCK_WAIT_POLICY_NOWAIT",
		2: "LOCK_WAIT_POLICY_SKIP_LOCKED",
	}
	LockWaitPolicy_value = map[string]int32{
		"LOCK_WAIT_POLICY_UNSPECIFIED": 0,
		"LOCK_WAIT_POLICY_NOWAIT":      1,
		"LOCK_WAIT_POLICY_SKIP_LOCKED": 2,
	}
)

func (x LockWaitPolicy) Enum() *LockWaitPolicy {
	p := new(LockWaitPolicy)
	*p = x
	return p
}

func (x LockWaitPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LockWaitPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_expr_proto_enumTypes[6].Descriptor()
}

func (LockWaitPolicy) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_expr_proto_enumTypes[6]
}

func (x LockWaitPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LockWaitPolicy.Descriptor instead.
func (LockWaitPolicy) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{6}
}

type JoinType int32

const (
	JoinType_JOIN_TYPE_UNSPECIFIED JoinType = 0
	JoinType_JOIN_TYPE_INNER       JoinType = 1
	JoinType_JOIN_TYPE_LEFT        JoinType = 2
	JoinType_JOIN_TYPE_RIGHT       JoinType = 3
	JoinType_JOIN_TYPE_FULL        JoinType = 4
	JoinType_JOIN_TYPE_CROSS       JoinType = 5
)

// Enum value maps for JoinType.
var (
	JoinType_name = map[int32]string{
		0: "JOIN_TYPE_UNSPECIFIED",
		1: "JOIN_TYPE_INNER",
		2: "JOIN_TYPE_LEFT",
		3: "JOIN_TYPE_RIGHT",
		4: "JOIN_TYPE_FULL",
		5: "JOIN_TYPE_CROSS",
	}
	JoinType_value = map[string]int32{
		"JOIN_TYPE_UNSPECIFIED": 0,
		"JOIN_TYPE_INNER":       1,
		"JOIN_TYPE_LEFT":        2,
		"JOIN_TYPE_RIGHT":       3,
		"JOIN_TYPE_FULL":        4,
		"JOIN_TYPE_CROSS":       5,
	}
)

func (x JoinType) Enum() *JoinType {
	p := new(JoinType)
	*p = x
	return p
}

func (x JoinType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinType) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_expr_proto_enumTypes[7].Descriptor()
}

func (JoinType) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_expr_proto_enumTypes[7]
}

func (x JoinType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinType.Descriptor instead.
func (JoinType) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{7}
}

type Expr struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Node:
	//
	//	*Expr_Literal
	//	*Expr_ColumnRef
	//	*Expr_Parameter
	//	*Expr_FunctionCall
	//	*Expr_Operator
	//	*Expr_CaseExpr
	//	*Expr_Cast
	//	*Expr_Subquery
	//	*Expr_List
	//	*Expr_Star
	//	*Expr_RawSql
	Node          isExpr_Node `protobuf_oneof:"node"`
	Meta          *Metadata   `protobuf:"bytes,20,opt,name=meta,proto3" json:"meta,omitempty"`
	NodeId        string      `protobuf:"bytes,21,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // stable host-assigned AST id; see AnnotationTargetRef
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expr) Reset() {
	*x = Expr{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expr) ProtoMessage() {}

func (x *Expr) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expr.ProtoReflect.Descriptor instead.
func (*Expr) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{0}
}

func (x *Expr) GetNode() isExpr_Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *Expr) GetLiteral() *Literal {
	if x != nil {
		if x, ok := x.Node.(*Expr_Literal); ok {
			return x.Literal
		}
	}
	return nil
}

func (x *Expr) GetColumnRef() *ColumnRef {
	if x != nil {
		if x, ok := x.Node.(*Expr_ColumnRef); ok {
			return x.ColumnRef
		}
	}
	return nil
}

func (x *Expr) GetParameter() *ParameterRef {
	if x != nil {
		if x, ok := x.Node.(*Expr_Parameter); ok {
			return x.Parameter
		}
	}
	return nil
}

func (x *Expr) GetFunctionCall() *FunctionCall {
	if x != nil {
		if x, ok := x.Node.(*Expr_FunctionCall); ok {
			return x.FunctionCall
		}
	}
	return nil
}

func (x *Expr) GetOperator() *OperatorExpr {
	if x != nil {
		if x, ok := x.Node.(*Expr_Operator); ok {
			return x.Operator
		}
	}
	return nil
}

func (x *Expr) GetCaseExpr() *CaseExpr {
	if x != nil {
		if x, ok := x.Node.(*Expr_CaseExpr); ok {
			return x.CaseExpr
		}
	}
	return nil
}

func (x *Expr) GetCast() *CastExpr {
	if x != nil {
		if x, ok := x.Node.(*Expr_Cast); ok {
			return x.Cast
		}
	}
	return nil
}

func (x *Expr) GetSubquery() *SubqueryExpr {
	if x != nil {
		if x, ok := x.Node.(*Expr_Subquery); ok {
			return x.Subquery
		}
	}
	return nil
}

func (x *Expr) GetList() *ListExpr {
	if x != nil {
		if x, ok := x.Node.(*Expr_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *Expr) GetStar() *StarExpr {
	if x != nil {
		if x, ok := x.Node.(*Expr_Star); ok {
			return x.Star
		}
	}
	return nil
}

func (x *Expr) GetRawSql() string {
	if x != nil {
		if x, ok := x.Node.(*Expr_RawSql); ok {
			return x.RawSql
		}
	}
	return ""
}

func (x *Expr) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Expr) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type isExpr_Node interface {
	isExpr_Node()
}

type Expr_Literal struct {
	Literal *Literal `protobuf:"bytes,1,opt,name=literal,proto3,oneof"`
}

type Expr_ColumnRef struct {
	ColumnRef *ColumnRef `protobuf:"bytes,2,opt,name=column_ref,json=columnRef,proto3,oneof"`
}

type Expr_Parameter struct {
	Parameter *ParameterRef `protobuf:"bytes,3,opt,name=parameter,proto3,oneof"`
}

type Expr_FunctionCall struct {
	FunctionCall *FunctionCall `protobuf:"bytes,4,opt,name=function_call,json=functionCall,proto3,oneof"`
}

type Expr_Operator struct {
	Operator *OperatorExpr `protobuf:"bytes,5,opt,name=operator,proto3,oneof"`
}

type Expr_CaseExpr struct {
	CaseExpr *CaseExpr `protobuf:"bytes,6,opt,name=case_expr,json=caseExpr,proto3,oneof"`
}

type Expr_Cast struct {
	Cast *CastExpr `protobuf:"bytes,7,opt,name=cast,proto3,oneof"`
}

type Expr_Subquery struct {
	Subquery *SubqueryExpr `protobuf:"bytes,8,opt,name=subquery,proto3,oneof"`
}

type Expr_List struct {
	List *ListExpr `protobuf:"bytes,9,opt,name=list,proto3,oneof"` // (a, b, c) / row(...)
}

type Expr_Star struct {
	Star *StarExpr `protobuf:"bytes,10,opt,name=star,proto3,oneof"` // * or t.*
}

type Expr_RawSql struct {
	RawSql string `protobuf:"bytes,11,opt,name=raw_sql,json=rawSql,proto3,oneof"` // escape hatch
}

func (*Expr_Literal) isExpr_Node() {}

func (*Expr_ColumnRef) isExpr_Node() {}

func (*Expr_Parameter) isExpr_Node() {}

func (*Expr_FunctionCall) isExpr_Node() {}

func (*Expr_Operator) isExpr_Node() {}

func (*Expr_CaseExpr) isExpr_Node() {}

func (*Expr_Cast) isExpr_Node() {}

func (*Expr_Subquery) isExpr_Node() {}

func (*Expr_List) isExpr_Node() {}

func (*Expr_Star) isExpr_Node() {}

func (*Expr_RawSql) isExpr_Node() {}

// Literal is a constant. Exactly one value field is set; `null_value = true`
// represents SQL NULL.
type Literal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Literal_NullValue
	//	*Literal_IntValue
	//	*Literal_FloatValue
	//	*Literal_NumericValue
	//	*Literal_StringValue
	//	*Literal_BoolValue
	//	*Literal_ByteaValue
	Value         isLiteral_Value `protobuf_oneof:"value"`
	Type          *TypeRef        `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"` // declared/inferred type, when known
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Literal) Reset() {
	*x = Literal{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Literal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Literal) ProtoMessage() {}

func (x *Literal) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Literal.ProtoReflect.Descriptor instead.
func (*Literal) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{1}
}

func (x *Literal) GetValue() isLiteral_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Literal) GetNullValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Literal_NullValue); ok {
			return x.NullValue
		}
	}
	return false
}

func (x *Literal) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*Literal_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Literal) GetFloatValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*Literal_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *Literal) GetNumericValue() string {
	if x != nil {
		if x, ok := x.Value.(*Literal_NumericValue); ok {
			return x.NumericValue
		}
	}
	return ""
}

func (x *Literal) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Literal_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Literal) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Literal_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Literal) GetByteaValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*Literal_ByteaValue); ok {
			return x.ByteaValue
		}
	}
	return nil
}

func (x *Literal) GetType() *TypeRef {
	if x != nil {
		return x.Type
	}
	return nil
}

type isLiteral_Value interface {
	isLiteral_Value()
}

type Literal_NullValue struct {
	NullValue bool `protobuf:"varint,1,opt,name=null_value,json=nullValue,proto3,oneof"`
}

type Literal_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Literal_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,3,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type Literal_NumericValue struct {
	NumericValue string `protobuf:"bytes,4,opt,name=numeric_value,json=numericValue,proto3,oneof"` // exact decimal carried as text
}

type Literal_StringValue struct {
	StringValue string `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Literal_BoolValue struct {
	BoolValue bool `protobuf:"varint,6,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Literal_ByteaValue struct {
	ByteaValue []byte `protobuf:"bytes,7,opt,name=bytea_value,json=byteaValue,proto3,oneof"`
}

func (*Literal_NullValue) isLiteral_Value() {}

func (*Literal_IntValue) isLiteral_Value() {}

func (*Literal_FloatValue) isLiteral_Value() {}

func (*Literal_NumericValue) isLiteral_Value() {}

func (*Literal_StringValue) isLiteral_Value() {}

func (*Literal_BoolValue) isLiteral_Value() {}

func (*Literal_ByteaValue) isLiteral_Value() {}

// ColumnRef references a column, optionally qualified by a table alias/name.
type ColumnRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qualifier     string                 `protobuf:"bytes,1,opt,name=qualifier,proto3" json:"qualifier,omitempty"` // table alias or name; empty if unqualified
	Column        string                 `protobuf:"bytes,2,opt,name=column,proto3" json:"column,omitempty"`
	Target        *ObjectRef             `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"` // resolved column, when known
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnRef) Reset() {
	*x = ColumnRef{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnRef) ProtoMessage() {}

func (x *ColumnRef) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnRef.ProtoReflect.Descriptor instead.
func (*ColumnRef) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{2}
}

func (x *ColumnRef) GetQualifier() string {
	if x != nil {
		return x.Qualifier
	}
	return ""
}

func (x *ColumnRef) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *ColumnRef) GetTarget() *ObjectRef {
	if x != nil {
		return x.Target
	}
	return nil
}

// ParameterRef is a bind parameter: $1 (position) or :name / @name (name).
type ParameterRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      uint32                 `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"` // 1-based; 0 if named
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParameterRef) Reset() {
	*x = ParameterRef{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterRef) ProtoMessage() {}

func (x *ParameterRef) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterRef.ProtoReflect.Descriptor instead.
func (*ParameterRef) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{3}
}

func (x *ParameterRef) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *ParameterRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// FunctionCall is a scalar/aggregate/window function invocation.
type FunctionCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *QualifiedName         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Target        *ObjectRef             `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"` // resolved function, when known
	Arguments     []*Expr                `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	Distinct      bool                   `protobuf:"varint,4,opt,name=distinct,proto3" json:"distinct,omitempty"`             // agg(DISTINCT ...)
	OrderBy       []*OrderByItem         `protobuf:"bytes,5,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"` // agg WITHIN GROUP / ORDER BY
	Filter        *Expr                  `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"`                  // FILTER (WHERE ...)
	Over          *WindowSpec            `protobuf:"bytes,7,opt,name=over,proto3" json:"over,omitempty"`                      // OVER (...) -> window function
	Variadic      bool                   `protobuf:"varint,8,opt,name=variadic,proto3" json:"variadic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionCall) Reset() {
	*x = FunctionCall{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCall) ProtoMessage() {}

func (x *FunctionCall) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCall.ProtoReflect.Descriptor instead.
func (*FunctionCall) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{4}
}

func (x *FunctionCall) GetName() *QualifiedName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *FunctionCall) GetTarget() *ObjectRef {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *FunctionCall) GetArguments() []*Expr {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *FunctionCall) GetDistinct() bool {
	if x != nil {
		return x.Distinct
	}
	return false
}

func (x *FunctionCall) GetOrderBy() []*OrderByItem {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *FunctionCall) GetFilter() *Expr {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *FunctionCall) GetOver() *WindowSpec {
	if x != nil {
		return x.Over
	}
	return nil
}

func (x *FunctionCall) GetVariadic() bool {
	if x != nil {
		return x.Variadic
	}
	return false
}

// OperatorExpr is any operator application: unary, binary, or logical
// (AND/OR/NOT). `symbol` is the operator token, e.g. "=", "+", "AND",
// "IS NULL", "@>", "LIKE".
type OperatorExpr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Operands      []*Expr                `protobuf:"bytes,2,rep,name=operands,proto3" json:"operands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorExpr) Reset() {
	*x = OperatorExpr{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorExpr) ProtoMessage() {}

func (x *OperatorExpr) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorExpr.ProtoReflect.Descriptor instead.
func (*OperatorExpr) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{5}
}

func (x *OperatorExpr) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OperatorExpr) GetOperands() []*Expr {
	if x != nil {
		return x.Operands
	}
	return nil
}

type CaseWhen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Condition     *Expr                  `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	Result        *Expr                  `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaseWhen) Reset() {
	*x = CaseWhen{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaseWhen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseWhen) ProtoMessage() {}

func (x *CaseWhen) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseWhen.ProtoReflect.Descriptor instead.
func (*CaseWhen) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{6}
}

func (x *CaseWhen) GetCondition() *Expr {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *CaseWhen) GetResult() *Expr {
	if x != nil {
		return x.Result
	}
	return nil
}

// CaseExpr models simple and searched CASE. For simple CASE, `operand` is set
// and each `whens[i].condition` is the compared value.
type CaseExpr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operand       *Expr                  `protobuf:"bytes,1,opt,name=operand,proto3" json:"operand,omitempty"` // optional (searched CASE leaves it unset)
	Whens         []*CaseWhen            `protobuf:"bytes,2,rep,name=whens,proto3" json:"whens,omitempty"`
	ElseResult    *Expr                  `protobuf:"bytes,3,opt,name=else_result,json=elseResult,proto3" json:"else_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaseExpr) Reset() {
	*x = CaseExpr{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaseExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseExpr) ProtoMessage() {}

func (x *CaseExpr) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseExpr.ProtoReflect.Descriptor instead.
func (*CaseExpr) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{7}
}

func (x *CaseExpr) GetOperand() *Expr {
	if x != nil {
		return x.Operand
	}
	return nil
}

func (x *CaseExpr) GetWhens() []*CaseWhen {
	if x != nil {
		return x.Whens
	}
	return nil
}

func (x *CaseExpr) GetElseResult() *Expr {
	if x != nil {
		return x.ElseResult
	}
	return nil
}

// CastExpr is CAST(expr AS type) / expr::type.
type CastExpr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          *Expr                  `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	TargetType    *TypeRef               `protobuf:"bytes,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastExpr) Reset() {
	*x = CastExpr{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastExpr) ProtoMessage() {}

func (x *CastExpr) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastExpr.ProtoReflect.Descriptor instead.
func (*CastExpr) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{8}
}

func (x *CastExpr) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *CastExpr) GetTargetType() *TypeRef {
	if x != nil {
		return x.TargetType
	}
	return nil
}

// SubqueryExpr embeds a query inside an expression. `operand`/`symbol` are used
// by IN/ANY/ALL forms.
type SubqueryExpr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          SubqueryKind           `protobuf:"varint,1,opt,name=kind,proto3,enum=sqld.v1.ir.SubqueryKind" json:"kind,omitempty"`
	Query         *SelectStmt            `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Operand       *Expr                  `protobuf:"bytes,3,opt,name=operand,proto3" json:"operand,omitempty"` // left-hand side for IN/ANY/ALL
	Symbol        string                 `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`   // comparison operator for ANY/ALL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubqueryExpr) Reset() {
	*x = SubqueryExpr{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubqueryExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubqueryExpr) ProtoMessage() {}

func (x *SubqueryExpr) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubqueryExpr.ProtoReflect.Descriptor instead.
func (*SubqueryExpr) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{9}
}

func (x *SubqueryExpr) GetKind() SubqueryKind {
	if x != nil {
		return x.Kind
	}
	return SubqueryKind_SUBQUERY_KIND_UNSPECIFIED
}

func (x *SubqueryExpr) GetQuery() *SelectStmt {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SubqueryExpr) GetOperand() *Expr {
	if x != nil {
		return x.Operand
	}
	return nil
}

func (x *SubqueryExpr) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// ListExpr is a parenthesized list / row constructor.
type ListExpr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*Expr                `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	IsRow         bool                   `protobuf:"varint,2,opt,name=is_row,json=isRow,proto3" json:"is_row,omitempty"` // true for ROW(...)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExpr) Reset() {
	*x = ListExpr{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExpr) ProtoMessage() {}

func (x *ListExpr) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExpr.ProtoReflect.Descriptor instead.
func (*ListExpr) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{10}
}

func (x *ListExpr) GetElements() []*Expr {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *ListExpr) GetIsRow() bool {
	if x != nil {
		return x.IsRow
	}
	return false
}

// StarExpr is `*` or `qualifier.*`.
type StarExpr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qualifier     string                 `protobuf:"bytes,1,opt,name=qualifier,proto3" json:"qualifier,omitempty"` // empty for bare *
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarExpr) Reset() {
	*x = StarExpr{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarExpr) ProtoMessage() {}

func (x *StarExpr) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarExpr.ProtoReflect.Descriptor instead.
func (*StarExpr) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{11}
}

func (x *StarExpr) GetQualifier() string {
	if x != nil {
		return x.Qualifier
	}
	return ""
}

type OrderByItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          *Expr                  `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Order         SortOrder              `protobuf:"varint,2,opt,name=order,proto3,enum=sqld.v1.ir.SortOrder" json:"order,omitempty"`
	Nulls         NullsOrder             `protobuf:"varint,3,opt,name=nulls,proto3,enum=sqld.v1.ir.NullsOrder" json:"nulls,omitempty"`
	UsingOperator string                 `protobuf:"bytes,4,opt,name=using_operator,json=usingOperator,proto3" json:"using_operator,omitempty"` // ORDER BY ... USING op
	NodeId        string                 `protobuf:"bytes,21,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                     // stable host-assigned AST id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderByItem) Reset() {
	*x = OrderByItem{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderByItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderByItem) ProtoMessage() {}

func (x *OrderByItem) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderByItem.ProtoReflect.Descriptor instead.
func (*OrderByItem) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{12}
}

func (x *OrderByItem) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *OrderByItem) GetOrder() SortOrder {
	if x != nil {
		return x.Order
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

func (x *OrderByItem) GetNulls() NullsOrder {
	if x != nil {
		return x.Nulls
	}
	return NullsOrder_NULLS_ORDER_UNSPECIFIED
}

func (x *OrderByItem) GetUsingOperator() string {
	if x != nil {
		return x.UsingOperator
	}
	return ""
}

func (x *OrderByItem) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// SelectTarget is one item in a select list or RETURNING list.
type SelectTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          *Expr                  `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`                  // AS alias; empty if none
	NodeId        string                 `protobuf:"bytes,21,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // stable host-assigned AST id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectTarget) Reset() {
	*x = SelectTarget{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectTarget) ProtoMessage() {}

func (x *SelectTarget) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectTarget.ProtoReflect.Descriptor instead.
func (*SelectTarget) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{13}
}

func (x *SelectTarget) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *SelectTarget) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *SelectTarget) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// SetOperation combines two queries (UNION / INTERSECT / EXCEPT).
type SetOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          SetOpKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=sqld.v1.ir.SetOpKind" json:"kind,omitempty"`
	All           bool                   `protobuf:"varint,2,opt,name=all,proto3" json:"all,omitempty"` // UNION ALL vs UNION
	Left          *SelectStmt            `protobuf:"bytes,3,opt,name=left,proto3" json:"left,omitempty"`
	Right         *SelectStmt            `protobuf:"bytes,4,opt,name=right,proto3" json:"right,omitempty"`
	NodeId        string                 `protobuf:"bytes,21,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // stable host-assigned AST id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOperation) Reset() {
	*x = SetOperation{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOperation) ProtoMessage() {}

func (x *SetOperation) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOperation.ProtoReflect.Descriptor instead.
func (*SetOperation) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{14}
}

func (x *SetOperation) GetKind() SetOpKind {
	if x != nil {
		return x.Kind
	}
	return SetOpKind_SET_OP_KIND_UNSPECIFIED
}

func (x *SetOperation) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *SetOperation) GetLeft() *SelectStmt {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *SetOperation) GetRight() *SelectStmt {
	if x != nil {
		return x.Right
	}
	return nil
}

func (x *SetOperation) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// SimpleSelect is a single SELECT block (no set operation at this level).
type SimpleSelect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Distinct      bool                   `protobuf:"varint,1,opt,name=distinct,proto3" json:"distinct,omitempty"`
	DistinctOn    []*Expr                `protobuf:"bytes,2,rep,name=distinct_on,json=distinctOn,proto3" json:"distinct_on,omitempty"` // DISTINCT ON (...)
	Targets       []*SelectTarget        `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	From          []*FromItem            `protobuf:"bytes,4,rep,name=from,proto3" json:"from,omitempty"`
	Where         *Expr                  `protobuf:"bytes,5,opt,name=where,proto3" json:"where,omitempty"`
	GroupBy       []*Expr                `protobuf:"bytes,6,rep,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	GroupByAll    bool                   `protobuf:"varint,7,opt,name=group_by_all,json=groupByAll,proto3" json:"group_by_all,omitempty"` // GROUP BY ALL / DISTINCT variants -> see raw_sql
	Having        *Expr                  `protobuf:"bytes,8,opt,name=having,proto3" json:"having,omitempty"`
	Windows       []*WindowDef           `protobuf:"bytes,9,rep,name=windows,proto3" json:"windows,omitempty"`
	NodeId        string                 `protobuf:"bytes,21,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // stable host-assigned AST id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleSelect) Reset() {
	*x = SimpleSelect{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleSelect) ProtoMessage() {}

func (x *SimpleSelect) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleSelect.ProtoReflect.Descriptor instead.
func (*SimpleSelect) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{15}
}

func (x *SimpleSelect) GetDistinct() bool {
	if x != nil {
		return x.Distinct
	}
	return false
}

func (x *SimpleSelect) GetDistinctOn() []*Expr {
	if x != nil {
		return x.DistinctOn
	}
	return nil
}

func (x *SimpleSelect) GetTargets() []*SelectTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *SimpleSelect) GetFrom() []*FromItem {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *SimpleSelect) GetWhere() *Expr {
	if x != nil {
		return x.Where
	}
	return nil
}

func (x *SimpleSelect) GetGroupBy() []*Expr {
	if x != nil {
		return x.GroupBy
	}
	return nil
}

func (x *SimpleSelect) GetGroupByAll() bool {
	if x != nil {
		return x.GroupByAll
	}
	return false
}

func (x *SimpleSelect) GetHaving() *Expr {
	if x != nil {
		return x.Having
	}
	return nil
}

func (x *SimpleSelect) GetWindows() []*WindowDef {
	if x != nil {
		return x.Windows
	}
	return nil
}

func (x *SimpleSelect) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// CommonTableExpr is one WITH entry. `query` may be a SelectStmt; non-SELECT
// CTEs fall back to raw_sql on the inner statement.
type CommonTableExpr struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Columns         []string               `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	Query           *SelectStmt            `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Materialization CteMaterialization     `protobuf:"varint,4,opt,name=materialization,proto3,enum=sqld.v1.ir.CteMaterialization" json:"materialization,omitempty"`
	NodeId          string                 `protobuf:"bytes,21,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // stable host-assigned AST id
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommonTableExpr) Reset() {
	*x = CommonTableExpr{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonTableExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonTableExpr) ProtoMessage() {}

func (x *CommonTableExpr) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonTableExpr.ProtoReflect.Descriptor instead.
func (*CommonTableExpr) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{16}
}

func (x *CommonTableExpr) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommonTableExpr) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *CommonTableExpr) GetQuery() *SelectStmt {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *CommonTableExpr) GetMaterialization() CteMaterialization {
	if x != nil {
		return x.Materialization
	}
	return CteMaterialization_CTE_MATERIALIZATION_UNSPECIFIED
}

func (x *CommonTableExpr) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type LockingClause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strength      LockStrength           `protobuf:"varint,1,opt,name=strength,proto3,enum=sqld.v1.ir.LockStrength" json:"strength,omitempty"`
	OfTables      []*ObjectRef           `protobuf:"bytes,2,rep,name=of_tables,json=ofTables,proto3" json:"of_tables,omitempty"` // OF table, ...
	Wait          LockWaitPolicy         `protobuf:"varint,3,opt,name=wait,proto3,enum=sqld.v1.ir.LockWaitPolicy" json:"wait,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockingClause) Reset() {
	*x = LockingClause{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockingClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockingClause) ProtoMessage() {}

func (x *LockingClause) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockingClause.ProtoReflect.Descriptor instead.
func (*LockingClause) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{17}
}

func (x *LockingClause) GetStrength() LockStrength {
	if x != nil {
		return x.Strength
	}
	return LockStrength_LOCK_STRENGTH_UNSPECIFIED
}

func (x *LockingClause) GetOfTables() []*ObjectRef {
	if x != nil {
		return x.OfTables
	}
	return nil
}

func (x *LockingClause) GetWait() LockWaitPolicy {
	if x != nil {
		return x.Wait
	}
	return LockWaitPolicy_LOCK_WAIT_POLICY_UNSPECIFIED
}

// SelectStmt is a complete query expression: optional CTEs, a body (a simple
// select, a set operation, or a VALUES list), and trailing ORDER/LIMIT/locking.
type SelectStmt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	With          []*CommonTableExpr     `protobuf:"bytes,1,rep,name=with,proto3" json:"with,omitempty"`
	WithRecursive bool                   `protobuf:"varint,2,opt,name=with_recursive,json=withRecursive,proto3" json:"with_recursive,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*SelectStmt_Select
	//	*SelectStmt_SetOperation
	//	*SelectStmt_Values
	Body          isSelectStmt_Body `protobuf_oneof:"body"`
	OrderBy       []*OrderByItem    `protobuf:"bytes,6,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Limit         *Expr             `protobuf:"bytes,7,opt,name=limit,proto3" json:"limit,omitempty"`   // LIMIT count / FETCH FIRST
	Offset        *Expr             `protobuf:"bytes,8,opt,name=offset,proto3" json:"offset,omitempty"` // OFFSET
	Locking       *LockingClause    `protobuf:"bytes,9,opt,name=locking,proto3" json:"locking,omitempty"`
	RawSql        string            `protobuf:"bytes,15,opt,name=raw_sql,json=rawSql,proto3" json:"raw_sql,omitempty"` // escape hatch for the whole statement
	Meta          *Metadata         `protobuf:"bytes,16,opt,name=meta,proto3" json:"meta,omitempty"`
	NodeId        string            `protobuf:"bytes,21,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // stable host-assigned AST id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectStmt) Reset() {
	*x = SelectStmt{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectStmt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectStmt) ProtoMessage() {}

func (x *SelectStmt) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectStmt.ProtoReflect.Descriptor instead.
func (*SelectStmt) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{18}
}

func (x *SelectStmt) GetWith() []*CommonTableExpr {
	if x != nil {
		return x.With
	}
	return nil
}

func (x *SelectStmt) GetWithRecursive() bool {
	if x != nil {
		return x.WithRecursive
	}
	return false
}

func (x *SelectStmt) GetBody() isSelectStmt_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SelectStmt) GetSelect() *SimpleSelect {
	if x != nil {
		if x, ok := x.Body.(*SelectStmt_Select); ok {
			return x.Select
		}
	}
	return nil
}

func (x *SelectStmt) GetSetOperation() *SetOperation {
	if x != nil {
		if x, ok := x.Body.(*SelectStmt_SetOperation); ok {
			return x.SetOperation
		}
	}
	return nil
}

func (x *SelectStmt) GetValues() *Values {
	if x != nil {
		if x, ok := x.Body.(*SelectStmt_Values); ok {
			return x.Values
		}
	}
	return nil
}

func (x *SelectStmt) GetOrderBy() []*OrderByItem {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *SelectStmt) GetLimit() *Expr {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *SelectStmt) GetOffset() *Expr {
	if x != nil {
		return x.Offset
	}
	return nil
}

func (x *SelectStmt) GetLocking() *LockingClause {
	if x != nil {
		return x.Locking
	}
	return nil
}

func (x *SelectStmt) GetRawSql() string {
	if x != nil {
		return x.RawSql
	}
	return ""
}

func (x *SelectStmt) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *SelectStmt) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type isSelectStmt_Body interface {
	isSelectStmt_Body()
}

type SelectStmt_Select struct {
	Select *SimpleSelect `protobuf:"bytes,3,opt,name=select,proto3,oneof"`
}

type SelectStmt_SetOperation struct {
	SetOperation *SetOperation `protobuf:"bytes,4,opt,name=set_operation,json=setOperation,proto3,oneof"`
}

type SelectStmt_Values struct {
	Values *Values `protobuf:"bytes,5,opt,name=values,proto3,oneof"`
}

func (*SelectStmt_Select) isSelectStmt_Body() {}

func (*SelectStmt_SetOperation) isSelectStmt_Body() {}

func (*SelectStmt_Values) isSelectStmt_Body() {}

type TableRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         *ObjectRef             `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Name          *QualifiedName         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // carried even when unresolved
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Only          bool                   `protobuf:"varint,4,opt,name=only,proto3" json:"only,omitempty"` // FROM ONLY t
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableRef) Reset() {
	*x = TableRef{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableRef) ProtoMessage() {}

func (x *TableRef) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableRef.ProtoReflect.Descriptor instead.
func (*TableRef) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{19}
}

func (x *TableRef) GetTable() *ObjectRef {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *TableRef) GetName() *QualifiedName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *TableRef) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *TableRef) GetOnly() bool {
	if x != nil {
		return x.Only
	}
	return false
}

type SubqueryRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *SelectStmt            `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	ColumnAliases []string               `protobuf:"bytes,3,rep,name=column_aliases,json=columnAliases,proto3" json:"column_aliases,omitempty"`
	Lateral       bool                   `protobuf:"varint,4,opt,name=lateral,proto3" json:"lateral,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubqueryRef) Reset() {
	*x = SubqueryRef{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubqueryRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubqueryRef) ProtoMessage() {}

func (x *SubqueryRef) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubqueryRef.ProtoReflect.Descriptor instead.
func (*SubqueryRef) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{20}
}

func (x *SubqueryRef) GetQuery() *SelectStmt {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SubqueryRef) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *SubqueryRef) GetColumnAliases() []string {
	if x != nil {
		return x.ColumnAliases
	}
	return nil
}

func (x *SubqueryRef) GetLateral() bool {
	if x != nil {
		return x.Lateral
	}
	return false
}

type FunctionRef struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Call           *Expr                  `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"` // table function, e.g. unnest(...) / jsonb_to_recordset(...)
	Alias          string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	ColumnAliases  []string               `protobuf:"bytes,3,rep,name=column_aliases,json=columnAliases,proto3" json:"column_aliases,omitempty"`
	Lateral        bool                   `protobuf:"varint,4,opt,name=lateral,proto3" json:"lateral,omitempty"`
	WithOrdinality bool                   `protobuf:"varint,5,opt,name=with_ordinality,json=withOrdinality,proto3" json:"with_ordinality,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FunctionRef) Reset() {
	*x = FunctionRef{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionRef) ProtoMessage() {}

func (x *FunctionRef) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionRef.ProtoReflect.Descriptor instead.
func (*FunctionRef) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{21}
}

func (x *FunctionRef) GetCall() *Expr {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *FunctionRef) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *FunctionRef) GetColumnAliases() []string {
	if x != nil {
		return x.ColumnAliases
	}
	return nil
}

func (x *FunctionRef) GetLateral() bool {
	if x != nil {
		return x.Lateral
	}
	return false
}

func (x *FunctionRef) GetWithOrdinality() bool {
	if x != nil {
		return x.WithOrdinality
	}
	return false
}

type ValuesRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        *Values                `protobuf:"bytes,1,opt,name=values,proto3" json:"values,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	ColumnAliases []string               `protobuf:"bytes,3,rep,name=column_aliases,json=columnAliases,proto3" json:"column_aliases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValuesRef) Reset() {
	*x = ValuesRef{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValuesRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValuesRef) ProtoMessage() {}

func (x *ValuesRef) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValuesRef.ProtoReflect.Descriptor instead.
func (*ValuesRef) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{22}
}

func (x *ValuesRef) GetValues() *Values {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ValuesRef) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *ValuesRef) GetColumnAliases() []string {
	if x != nil {
		return x.ColumnAliases
	}
	return nil
}

type JoinClause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          JoinType               `protobuf:"varint,1,opt,name=type,proto3,enum=sqld.v1.ir.JoinType" json:"type,omitempty"`
	Left          *FromItem              `protobuf:"bytes,2,opt,name=left,proto3" json:"left,omitempty"`
	Right         *FromItem              `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
	On            *Expr                  `protobuf:"bytes,4,opt,name=on,proto3" json:"on,omitempty"`                        // ON <condition>
	Using         []string               `protobuf:"bytes,5,rep,name=using,proto3" json:"using,omitempty"`                  // USING (col, ...)
	Natural       bool                   `protobuf:"varint,6,opt,name=natural,proto3" json:"natural,omitempty"`             // NATURAL JOIN
	NodeId        string                 `protobuf:"bytes,21,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // stable host-assigned AST id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinClause) Reset() {
	*x = JoinClause{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClause) ProtoMessage() {}

func (x *JoinClause) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClause.ProtoReflect.Descriptor instead.
func (*JoinClause) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{23}
}

func (x *JoinClause) GetType() JoinType {
	if x != nil {
		return x.Type
	}
	return JoinType_JOIN_TYPE_UNSPECIFIED
}

func (x *JoinClause) GetLeft() *FromItem {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *JoinClause) GetRight() *FromItem {
	if x != nil {
		return x.Right
	}
	return nil
}

func (x *JoinClause) GetOn() *Expr {
	if x != nil {
		return x.On
	}
	return nil
}

func (x *JoinClause) GetUsing() []string {
	if x != nil {
		return x.Using
	}
	return nil
}

func (x *JoinClause) GetNatural() bool {
	if x != nil {
		return x.Natural
	}
	return false
}

func (x *JoinClause) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type FromItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*FromItem_Table
	//	*FromItem_Subquery
	//	*FromItem_Join
	//	*FromItem_Function
	//	*FromItem_Values
	Source        isFromItem_Source `protobuf_oneof:"source"`
	NodeId        string            `protobuf:"bytes,21,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // stable host-assigned AST id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FromItem) Reset() {
	*x = FromItem{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromItem) ProtoMessage() {}

func (x *FromItem) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromItem.ProtoReflect.Descriptor instead.
func (*FromItem) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{24}
}

func (x *FromItem) GetSource() isFromItem_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *FromItem) GetTable() *TableRef {
	if x != nil {
		if x, ok := x.Source.(*FromItem_Table); ok {
			return x.Table
		}
	}
	return nil
}

func (x *FromItem) GetSubquery() *SubqueryRef {
	if x != nil {
		if x, ok := x.Source.(*FromItem_Subquery); ok {
			return x.Subquery
		}
	}
	return nil
}

func (x *FromItem) GetJoin() *JoinClause {
	if x != nil {
		if x, ok := x.Source.(*FromItem_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *FromItem) GetFunction() *FunctionRef {
	if x != nil {
		if x, ok := x.Source.(*FromItem_Function); ok {
			return x.Function
		}
	}
	return nil
}

func (x *FromItem) GetValues() *ValuesRef {
	if x != nil {
		if x, ok := x.Source.(*FromItem_Values); ok {
			return x.Values
		}
	}
	return nil
}

func (x *FromItem) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type isFromItem_Source interface {
	isFromItem_Source()
}

type FromItem_Table struct {
	Table *TableRef `protobuf:"bytes,1,opt,name=table,proto3,oneof"`
}

type FromItem_Subquery struct {
	Subquery *SubqueryRef `protobuf:"bytes,2,opt,name=subquery,proto3,oneof"`
}

type FromItem_Join struct {
	Join *JoinClause `protobuf:"bytes,3,opt,name=join,proto3,oneof"`
}

type FromItem_Function struct {
	Function *FunctionRef `protobuf:"bytes,4,opt,name=function,proto3,oneof"`
}

type FromItem_Values struct {
	Values *ValuesRef `protobuf:"bytes,5,opt,name=values,proto3,oneof"`
}

func (*FromItem_Table) isFromItem_Source() {}

func (*FromItem_Subquery) isFromItem_Source() {}

func (*FromItem_Join) isFromItem_Source() {}

func (*FromItem_Function) isFromItem_Source() {}

func (*FromItem_Values) isFromItem_Source() {}

type ValuesRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Expr                `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValuesRow) Reset() {
	*x = ValuesRow{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValuesRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValuesRow) ProtoMessage() {}

func (x *ValuesRow) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValuesRow.ProtoReflect.Descriptor instead.
func (*ValuesRow) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{25}
}

func (x *ValuesRow) GetValues() []*Expr {
	if x != nil {
		return x.Values
	}
	return nil
}

type Values struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*ValuesRow           `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Values) Reset() {
	*x = Values{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Values) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Values) ProtoMessage() {}

func (x *Values) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Values.ProtoReflect.Descriptor instead.
func (*Values) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{26}
}

func (x *Values) GetRows() []*ValuesRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

// WindowSpec is an inline OVER (...) or a reference to a named window.
type WindowSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefName       string                 `protobuf:"bytes,1,opt,name=ref_name,json=refName,proto3" json:"ref_name,omitempty"` // OVER w (named window); empty if inline
	PartitionBy   []*Expr                `protobuf:"bytes,2,rep,name=partition_by,json=partitionBy,proto3" json:"partition_by,omitempty"`
	OrderBy       []*OrderByItem         `protobuf:"bytes,3,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Frame         string                 `protobuf:"bytes,4,opt,name=frame,proto3" json:"frame,omitempty"` // raw frame clause, e.g. "ROWS BETWEEN ..."
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowSpec) Reset() {
	*x = WindowSpec{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowSpec) ProtoMessage() {}

func (x *WindowSpec) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowSpec.ProtoReflect.Descriptor instead.
func (*WindowSpec) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{27}
}

func (x *WindowSpec) GetRefName() string {
	if x != nil {
		return x.RefName
	}
	return ""
}

func (x *WindowSpec) GetPartitionBy() []*Expr {
	if x != nil {
		return x.PartitionBy
	}
	return nil
}

func (x *WindowSpec) GetOrderBy() []*OrderByItem {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *WindowSpec) GetFrame() string {
	if x != nil {
		return x.Frame
	}
	return ""
}

// WindowDef is a named window in the WINDOW clause.
type WindowDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Spec          *WindowSpec            `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowDef) Reset() {
	*x = WindowDef{}
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowDef) ProtoMessage() {}

func (x *WindowDef) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_expr_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowDef.ProtoReflect.Descriptor instead.
func (*WindowDef) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_expr_proto_rawDescGZIP(), []int{28}
}

func (x *WindowDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WindowDef) GetSpec() *WindowSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

var File_sqld_v1_ir_expr_proto protoreflect.FileDescriptor

const file_sqld_v1_ir_expr_proto_rawDesc = "" +
	"\n" +
	"\x15sqld/v1/ir/expr.proto\x12\n" +
	"sqld.v1.ir\x1a\x17sqld/v1/ir/common.proto\x1a\x15sqld/v1/ir/type.proto\"\xf9\x04\n" +
	"\x04Expr\x12/\n" +
	"\aliteral\x18\x01 \x01(\v2\x13.sqld.v1.ir.LiteralH\x00R\aliteral\x126\n" +
	"\n" +
	"column_ref\x18\x02 \x01(\v2\x15.sqld.v1.ir.ColumnRefH\x00R\tcolumnRef\x128\n" +
	"\tparameter\x18\x03 \x01(\v2\x18.sqld.v1.ir.ParameterRefH\x00R\tparameter\x12?\n" +
	"\rfunction_call\x18\x04 \x01(\v2\x18.sqld.v1.ir.FunctionCallH\x00R\ffunctionCall\x126\n" +
	"\boperator\x18\x05 \x01(\v2\x18.sqld.v1.ir.OperatorExprH\x00R\boperator\x123\n" +
	"\tcase_expr\x18\x06 \x01(\v2\x14.sqld.v1.ir.CaseExprH\x00R\bcaseExpr\x12*\n" +
	"\x04cast\x18\a \x01(\v2\x14.sqld.v1.ir.CastExprH\x00R\x04cast\x126\n" +
	"\bsubquery\x18\b \x01(\v2\x18.sqld.v1.ir.SubqueryExprH\x00R\bsubquery\x12*\n" +
	"\x04list\x18\t \x01(\v2\x14.sqld.v1.ir.ListExprH\x00R\x04list\x12*\n" +
	"\x04star\x18\n" +
	" \x01(\v2\x14.sqld.v1.ir.StarExprH\x00R\x04star\x12\x19\n" +
	"\araw_sql\x18\v \x01(\tH\x00R\x06rawSql\x12(\n" +
	"\x04meta\x18\x14 \x01(\v2\x14.sqld.v1.ir.MetadataR\x04meta\x12\x17\n" +
	"\anode_id\x18\x15 \x01(\tR\x06nodeIdB\x06\n" +
	"\x04node\"\xae\x02\n" +
	"\aLiteral\x12\x1f\n" +
	"\n" +
	"null_value\x18\x01 \x01(\bH\x00R\tnullValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12!\n" +
	"\vfloat_value\x18\x03 \x01(\x01H\x00R\n" +
	"floatValue\x12%\n" +
	"\rnumeric_value\x18\x04 \x01(\tH\x00R\fnumericValue\x12#\n" +
	"\fstring_value\x18\x05 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x06 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vbytea_value\x18\a \x01(\fH\x00R\n" +
	"byteaValue\x12'\n" +
	"\x04type\x18\n" +
	" \x01(\v2\x13.sqld.v1.ir.TypeRefR\x04typeB\a\n" +
	"\x05value\"p\n" +
	"\tColumnRef\x12\x1c\n" +
	"\tqualifier\x18\x01 \x01(\tR\tqualifier\x12\x16\n" +
	"\x06column\x18\x02 \x01(\tR\x06column\x12-\n" +
	"\x06target\x18\x03 \x01(\v2\x15.sqld.v1.ir.ObjectRefR\x06target\">\n" +
	"\fParameterRef\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\rR\bposition\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xde\x02\n" +
	"\fFunctionCall\x12-\n" +
	"\x04name\x18\x01 \x01(\v2\x19.sqld.v1.ir.QualifiedNameR\x04name\x12-\n" +
	"\x06target\x18\x02 \x01(\v2\x15.sqld.v1.ir.ObjectRefR\x06target\x12.\n" +
	"\targuments\x18\x03 \x03(\v2\x10.sqld.v1.ir.ExprR\targuments\x12\x1a\n" +
	"\bdistinct\x18\x04 \x01(\bR\bdistinct\x122\n" +
	"\border_by\x18\x05 \x03(\v2\x17.sqld.v1.ir.OrderByItemR\aorderBy\x12(\n" +
	"\x06filter\x18\x06 \x01(\v2\x10.sqld.v1.ir.ExprR\x06filter\x12*\n" +
	"\x04over\x18\a \x01(\v2\x16.sqld.v1.ir.WindowSpecR\x04over\x12\x1a\n" +
	"\bvariadic\x18\b \x01(\bR\bvariadic\"T\n" +
	"\fOperatorExpr\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12,\n" +
	"\boperands\x18\x02 \x03(\v2\x10.sqld.v1.ir.ExprR\boperands\"d\n" +
	"\bCaseWhen\x12.\n" +
	"\tcondition\x18\x01 \x01(\v2\x10.sqld.v1.ir.ExprR\tcondition\x12(\n" +
	"\x06result\x18\x02 \x01(\v2\x10.sqld.v1.ir.ExprR\x06result\"\x95\x01\n" +
	"\bCaseExpr\x12*\n" +
	"\aoperand\x18\x01 \x01(\v2\x10.sqld.v1.ir.ExprR\aoperand\x12*\n" +
	"\x05whens\x18\x02 \x03(\v2\x14.sqld.v1.ir.CaseWhenR\x05whens\x121\n" +
	"\velse_result\x18\x03 \x01(\v2\x10.sqld.v1.ir.ExprR\n" +
	"elseResult\"f\n" +
	"\bCastExpr\x12$\n" +
	"\x04expr\x18\x01 \x01(\v2\x10.sqld.v1.ir.ExprR\x04expr\x124\n" +
	"\vtarget_type\x18\x02 \x01(\v2\x13.sqld.v1.ir.TypeRefR\n" +
	"targetType\"\xae\x01\n" +
	"\fSubqueryExpr\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.sqld.v1.ir.SubqueryKindR\x04kind\x12,\n" +
	"\x05query\x18\x02 \x01(\v2\x16.sqld.v1.ir.SelectStmtR\x05query\x12*\n" +
	"\aoperand\x18\x03 \x01(\v2\x10.sqld.v1.ir.ExprR\aoperand\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\"O\n" +
	"\bListExpr\x12,\n" +
	"\belements\x18\x01 \x03(\v2\x10.sqld.v1.ir.ExprR\belements\x12\x15\n" +
	"\x06is_row\x18\x02 \x01(\bR\x05isRow\"(\n" +
	"\bStarExpr\x12\x1c\n" +
	"\tqualifier\x18\x01 \x01(\tR\tqualifier\"\xce\x01\n" +
	"\vOrderByItem\x12$\n" +
	"\x04expr\x18\x01 \x01(\v2\x10.sqld.v1.ir.ExprR\x04expr\x12+\n" +
	"\x05order\x18\x02 \x01(\x0e2\x15.sqld.v1.ir.SortOrderR\x05order\x12,\n" +
	"\x05nulls\x18\x03 \x01(\x0e2\x16.sqld.v1.ir.NullsOrderR\x05nulls\x12%\n" +
	"\x0eusing_operator\x18\x04 \x01(\tR\rusingOperator\x12\x17\n" +
	"\anode_id\x18\x15 \x01(\tR\x06nodeId\"c\n" +
	"\fSelectTarget\x12$\n" +
	"\x04expr\x18\x01 \x01(\v2\x10.sqld.v1.ir.ExprR\x04expr\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x17\n" +
	"\anode_id\x18\x15 \x01(\tR\x06nodeId\"\xbe\x01\n" +
	"\fSetOperation\x12)\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x15.sqld.v1.ir.SetOpKindR\x04kind\x12\x10\n" +
	"\x03all\x18\x02 \x01(\bR\x03all\x12*\n" +
	"\x04left\x18\x03 \x01(\v2\x16.sqld.v1.ir.SelectStmtR\x04left\x12,\n" +
	"\x05right\x18\x04 \x01(\v2\x16.sqld.v1.ir.SelectStmtR\x05right\x12\x17\n" +
	"\anode_id\x18\x15 \x01(\tR\x06nodeId\"\xa6\x03\n" +
	"\fSimpleSelect\x12\x1a\n" +
	"\bdistinct\x18\x01 \x01(\bR\bdistinct\x121\n" +
	"\vdistinct_on\x18\x02 \x03(\v2\x10.sqld.v1.ir.ExprR\n" +
	"distinctOn\x122\n" +
	"\atargets\x18\x03 \x03(\v2\x18.sqld.v1.ir.SelectTargetR\atargets\x12(\n" +
	"\x04from\x18\x04 \x03(\v2\x14.sqld.v1.ir.FromItemR\x04from\x12&\n" +
	"\x05where\x18\x05 \x01(\v2\x10.sqld.v1.ir.ExprR\x05where\x12+\n" +
	"\bgroup_by\x18\x06 \x03(\v2\x10.sqld.v1.ir.ExprR\agroupBy\x12 \n" +
	"\fgroup_by_all\x18\a \x01(\bR\n" +
	"groupByAll\x12(\n" +
	"\x06having\x18\b \x01(\v2\x10.sqld.v1.ir.ExprR\x06having\x12/\n" +
	"\awindows\x18\t \x03(\v2\x15.sqld.v1.ir.WindowDefR\awindows\x12\x17\n" +
	"\anode_id\x18\x15 \x01(\tR\x06nodeId\"\xd0\x01\n" +
	"\x0fCommonTableExpr\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns\x12,\n" +
	"\x05query\x18\x03 \x01(\v2\x16.sqld.v1.ir.SelectStmtR\x05query\x12H\n" +
	"\x0fmaterialization\x18\x04 \x01(\x0e2\x1e.sqld.v1.ir.CteMaterializationR\x0fmaterialization\x12\x17\n" +
	"\anode_id\x18\x15 \x01(\tR\x06nodeId\"\xa9\x01\n" +
	"\rLockingClause\x124\n" +
	"\bstrength\x18\x01 \x01(\x0e2\x18.sqld.v1.ir.LockStrengthR\bstrength\x122\n" +
	"\tof_tables\x18\x02 \x03(\v2\x15.sqld.v1.ir.ObjectRefR\bofTables\x12.\n" +
	"\x04wait\x18\x03 \x01(\x0e2\x1a.sqld.v1.ir.LockWaitPolicyR\x04wait\"\xa6\x04\n" +
	"\n" +
	"SelectStmt\x12/\n" +
	"\x04with\x18\x01 \x03(\v2\x1b.sqld.v1.ir.CommonTableExprR\x04with\x12%\n" +
	"\x0ewith_recursive\x18\x02 \x01(\bR\rwithRecursive\x122\n" +
	"\x06select\x18\x03 \x01(\v2\x18.sqld.v1.ir.SimpleSelectH\x00R\x06select\x12?\n" +
	"\rset_operation\x18\x04 \x01(\v2\x18.sqld.v1.ir.SetOperationH\x00R\fsetOperation\x12,\n" +
	"\x06values\x18\x05 \x01(\v2\x12.sqld.v1.ir.ValuesH\x00R\x06values\x122\n" +
	"\border_by\x18\x06 \x03(\v2\x17.sqld.v1.ir.OrderByItemR\aorderBy\x12&\n" +
	"\x05limit\x18\a \x01(\v2\x10.sqld.v1.ir.ExprR\x05limit\x12(\n" +
	"\x06offset\x18\b \x01(\v2\x10.sqld.v1.ir.ExprR\x06offset\x123\n" +
	"\alocking\x18\t \x01(\v2\x19.sqld.v1.ir.LockingClauseR\alocking\x12\x17\n" +
	"\araw_sql\x18\x0f \x01(\tR\x06rawSql\x12(\n" +
	"\x04meta\x18\x10 \x01(\v2\x14.sqld.v1.ir.MetadataR\x04meta\x12\x17\n" +
	"\anode_id\x18\x15 \x01(\tR\x06nodeIdB\x06\n" +
	"\x04body\"\x90\x01\n" +
	"\bTableRef\x12+\n" +
	"\x05table\x18\x01 \x01(\v2\x15.sqld.v1.ir.ObjectRefR\x05table\x12-\n" +
	"\x04name\x18\x02 \x01(\v2\x19.sqld.v1.ir.QualifiedNameR\x04name\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12\x12\n" +
	"\x04only\x18\x04 \x01(\bR\x04only\"\x92\x01\n" +
	"\vSubqueryRef\x12,\n" +
	"\x05query\x18\x01 \x01(\v2\x16.sqld.v1.ir.SelectStmtR\x05query\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12%\n" +
	"\x0ecolumn_aliases\x18\x03 \x03(\tR\rcolumnAliases\x12\x18\n" +
	"\alateral\x18\x04 \x01(\bR\alateral\"\xb3\x01\n" +
	"\vFunctionRef\x12$\n" +
	"\x04call\x18\x01 \x01(\v2\x10.sqld.v1.ir.ExprR\x04call\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12%\n" +
	"\x0ecolumn_aliases\x18\x03 \x03(\tR\rcolumnAliases\x12\x18\n" +
	"\alateral\x18\x04 \x01(\bR\alateral\x12'\n" +
	"\x0fwith_ordinality\x18\x05 \x01(\bR\x0ewithOrdinality\"t\n" +
	"\tValuesRef\x12*\n" +
	"\x06values\x18\x01 \x01(\v2\x12.sqld.v1.ir.ValuesR\x06values\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12%\n" +
	"\x0ecolumn_aliases\x18\x03 \x03(\tR\rcolumnAliases\"\xf7\x01\n" +
	"\n" +
	"JoinClause\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.sqld.v1.ir.JoinTypeR\x04type\x12(\n" +
	"\x04left\x18\x02 \x01(\v2\x14.sqld.v1.ir.FromItemR\x04left\x12*\n" +
	"\x05right\x18\x03 \x01(\v2\x14.sqld.v1.ir.FromItemR\x05right\x12 \n" +
	"\x02on\x18\x04 \x01(\v2\x10.sqld.v1.ir.ExprR\x02on\x12\x14\n" +
	"\x05using\x18\x05 \x03(\tR\x05using\x12\x18\n" +
	"\anatural\x18\x06 \x01(\bR\anatural\x12\x17\n" +
	"\anode_id\x18\x15 \x01(\tR\x06nodeId\"\xa8\x02\n" +
	"\bFromItem\x12,\n" +
	"\x05table\x18\x01 \x01(\v2\x14.sqld.v1.ir.TableRefH\x00R\x05table\x125\n" +
	"\bsubquery\x18\x02 \x01(\v2\x17.sqld.v1.ir.SubqueryRefH\x00R\bsubquery\x12,\n" +
	"\x04join\x18\x03 \x01(\v2\x16.sqld.v1.ir.JoinClauseH\x00R\x04join\x125\n" +
	"\bfunction\x18\x04 \x01(\v2\x17.sqld.v1.ir.FunctionRefH\x00R\bfunction\x12/\n" +
	"\x06values\x18\x05 \x01(\v2\x15.sqld.v1.ir.ValuesRefH\x00R\x06values\x12\x17\n" +
	"\anode_id\x18\x15 \x01(\tR\x06nodeIdB\b\n" +
	"\x06source\"5\n" +
	"\tValuesRow\x12(\n" +
	"\x06values\x18\x01 \x03(\v2\x10.sqld.v1.ir.ExprR\x06values\"3\n" +
	"\x06Values\x12)\n" +
	"\x04rows\x18\x01 \x03(\v2\x15.sqld.v1.ir.ValuesRowR\x04rows\"\xa6\x01\n" +
	"\n" +
	"WindowSpec\x12\x19\n" +
	"\bref_name\x18\x01 \x01(\tR\arefName\x123\n" +
	"\fpartition_by\x18\x02 \x03(\v2\x10.sqld.v1.ir.ExprR\vpartitionBy\x122\n" +
	"\border_by\x18\x03 \x03(\v2\x17.sqld.v1.ir.OrderByItemR\aorderBy\x12\x14\n" +
	"\x05frame\x18\x04 \x01(\tR\x05frame\"K\n" +
	"\tWindowDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x04spec\x18\x02 \x01(\v2\x16.sqld.v1.ir.WindowSpecR\x04spec*\xa5\x01\n" +
	"\fSubqueryKind\x12\x1d\n" +
	"\x19SUBQUERY_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SUBQUERY_KIND_SCALAR\x10\x01\x12\x18\n" +
	"\x14SUBQUERY_KIND_EXISTS\x10\x02\x12\x14\n" +
	"\x10SUBQUERY_KIND_IN\x10\x03\x12\x15\n" +
	"\x11SUBQUERY_KIND_ANY\x10\x04\x12\x15\n" +
	"\x11SUBQUERY_KIND_ALL\x10\x05*P\n" +
	"\tSortOrder\x12\x1a\n" +
	"\x16SORT_ORDER_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSORT_ORDER_ASC\x10\x01\x12\x13\n" +
	"\x0fSORT_ORDER_DESC\x10\x02*V\n" +
	"\n" +
	"NullsOrder\x12\x1b\n" +
	"\x17NULLS_ORDER_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11NULLS_ORDER_FIRST\x10\x01\x12\x14\n" +
	"\x10NULLS_ORDER_LAST\x10\x02*r\n" +
	"\tSetOpKind\x12\x1b\n" +
	"\x17SET_OP_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SET_OP_KIND_UNION\x10\x01\x12\x19\n" +
	"\x15SET_OP_KIND_INTERSECT\x10\x02\x12\x16\n" +
	"\x12SET_OP_KIND_EXCEPT\x10\x03*\x89\x01\n" +
	"\x12CteMaterialization\x12#\n" +
	"\x1fCTE_MATERIALIZATION_UNSPECIFIED\x10\x00\x12$\n" +
	" CTE_MATERIALIZATION_MATERIALIZED\x10\x01\x12(\n" +
	"$CTE_MATERIALIZATION_NOT_MATERIALIZED\x10\x02*\x9e\x01\n" +
	"\fLockStrength\x12\x1d\n" +
	"\x19LOCK_STRENGTH_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14LOCK_STRENGTH_UPDATE\x10\x01\x12\x1f\n" +
	"\x1bLOCK_STRENGTH_NO_KEY_UPDATE\x10\x02\x12\x17\n" +
	"\x13LOCK_STRENGTH_SHARE\x10\x03\x12\x1b\n" +
	"\x17LOCK_STRENGTH_KEY_SHARE\x10\x04*q\n" +
	"\x0eLockWaitPolicy\x12 \n" +
	"\x1cLOCK_WAIT_POLICY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17LOCK_WAIT_POLICY_NOWAIT\x10\x01\x12 \n" +
	"\x1cLOCK_WAIT_POLICY_SKIP_LOCKED\x10\x02*\x8c\x01\n" +
	"\bJoinType\x12\x19\n" +
	"\x15JOIN_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fJOIN_TYPE_INNER\x10\x01\x12\x12\n" +
	"\x0eJOIN_TYPE_LEFT\x10\x02\x12\x13\n" +
	"\x0fJOIN_TYPE_RIGHT\x10\x03\x12\x12\n" +
	"\x0eJOIN_TYPE_FULL\x10\x04\x12\x13\n" +
	"\x0fJOIN_TYPE_CROSS\x10\x05B3Z1github.com/gopherex/sqld/pkg/proto/sqld/v1/ir;irv1b\x06proto3"

var (
	file_sqld_v1_ir_expr_proto_rawDescOnce sync.Once
	file_sqld_v1_ir_expr_proto_rawDescData []byte
)

func file_sqld_v1_ir_expr_proto_rawDescGZIP() []byte {
	file_sqld_v1_ir_expr_proto_rawDescOnce.Do(func() {
		file_sqld_v1_ir_expr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sqld_v1_ir_expr_proto_rawDesc), len(file_sqld_v1_ir_expr_proto_rawDesc)))
	})
	return file_sqld_v1_ir_expr_proto_rawDescData
}

var file_sqld_v1_ir_expr_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_sqld_v1_ir_expr_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_sqld_v1_ir_expr_proto_goTypes = []any{
	(SubqueryKind)(0),       // 0: sqld.v1.ir.SubqueryKind
	(SortOrder)(0),          // 1: sqld.v1.ir.SortOrder
	(NullsOrder)(0),         // 2: sqld.v1.ir.NullsOrder
	(SetOpKind)(0),          // 3: sqld.v1.ir.SetOpKind
	(CteMaterialization)(0), // 4: sqld.v1.ir.CteMaterialization
	(LockStrength)(0),       // 5: sqld.v1.ir.LockStrength
	(LockWaitPolicy)(0),     // 6: sqld.v1.ir.LockWaitPolicy
	(JoinType)(0),           // 7: sqld.v1.ir.JoinType
	(*Expr)(nil),            // 8: sqld.v1.ir.Expr
	(*Literal)(nil),         // 9: sqld.v1.ir.Literal
	(*ColumnRef)(nil),       // 10: sqld.v1.ir.ColumnRef
	(*ParameterRef)(nil),    // 11: sqld.v1.ir.ParameterRef
	(*FunctionCall)(nil),    // 12: sqld.v1.ir.FunctionCall
	(*OperatorExpr)(nil),    // 13: sqld.v1.ir.OperatorExpr
	(*CaseWhen)(nil),        // 14: sqld.v1.ir.CaseWhen
	(*CaseExpr)(nil),        // 15: sqld.v1.ir.CaseExpr
	(*CastExpr)(nil),        // 16: sqld.v1.ir.CastExpr
	(*SubqueryExpr)(nil),    // 17: sqld.v1.ir.SubqueryExpr
	(*ListExpr)(nil),        // 18: sqld.v1.ir.ListExpr
	(*StarExpr)(nil),        // 19: sqld.v1.ir.StarExpr
	(*OrderByItem)(nil),     // 20: sqld.v1.ir.OrderByItem
	(*SelectTarget)(nil),    // 21: sqld.v1.ir.SelectTarget
	(*SetOperation)(nil),    // 22: sqld.v1.ir.SetOperation
	(*SimpleSelect)(nil),    // 23: sqld.v1.ir.SimpleSelect
	(*CommonTableExpr)(nil), // 24: sqld.v1.ir.CommonTableExpr
	(*LockingClause)(nil),   // 25: sqld.v1.ir.LockingClause
	(*SelectStmt)(nil),      // 26: sqld.v1.ir.SelectStmt
	(*TableRef)(nil),        // 27: sqld.v1.ir.TableRef
	(*SubqueryRef)(nil),     // 28: sqld.v1.ir.SubqueryRef
	(*FunctionRef)(nil),     // 29: sqld.v1.ir.FunctionRef
	(*ValuesRef)(nil),       // 30: sqld.v1.ir.ValuesRef
	(*JoinClause)(nil),      // 31: sqld.v1.ir.JoinClause
	(*FromItem)(nil),        // 32: sqld.v1.ir.FromItem
	(*ValuesRow)(nil),       // 33: sqld.v1.ir.ValuesRow
	(*Values)(nil),          // 34: sqld.v1.ir.Values
	(*WindowSpec)(nil),      // 35: sqld.v1.ir.WindowSpec
	(*WindowDef)(nil),       // 36: sqld.v1.ir.WindowDef
	(*Metadata)(nil),        // 37: sqld.v1.ir.Metadata
	(*TypeRef)(nil),         // 38: sqld.v1.ir.TypeRef
	(*ObjectRef)(nil),       // 39: sqld.v1.ir.ObjectRef
	(*QualifiedName)(nil),   // 40: sqld.v1.ir.QualifiedName
}
var file_sqld_v1_ir_expr_proto_depIdxs = []int32{
	9,  // 0: sqld.v1.ir.Expr.literal:type_name -> sqld.v1.ir.Literal
	10, // 1: sqld.v1.ir.Expr.column_ref:type_name -> sqld.v1.ir.ColumnRef
	11, // 2: sqld.v1.ir.Expr.parameter:type_name -> sqld.v1.ir.ParameterRef
	12, // 3: sqld.v1.ir.Expr.function_call:type_name -> sqld.v1.ir.FunctionCall
	13, // 4: sqld.v1.ir.Expr.operator:type_name -> sqld.v1.ir.OperatorExpr
	15, // 5: sqld.v1.ir.Expr.case_expr:type_name -> sqld.v1.ir.CaseExpr
	16, // 6: sqld.v1.ir.Expr.cast:type_name -> sqld.v1.ir.CastExpr
	17, // 7: sqld.v1.ir.Expr.subquery:type_name -> sqld.v1.ir.SubqueryExpr
	18, // 8: sqld.v1.ir.Expr.list:type_name -> sqld.v1.ir.ListExpr
	19, // 9: sqld.v1.ir.Expr.star:type_name -> sqld.v1.ir.StarExpr
	37, // 10: sqld.v1.ir.Expr.meta:type_name -> sqld.v1.ir.Metadata
	38, // 11: sqld.v1.ir.Literal.type:type_name -> sqld.v1.ir.TypeRef
	39, // 12: sqld.v1.ir.ColumnRef.target:type_name -> sqld.v1.ir.ObjectRef
	40, // 13: sqld.v1.ir.FunctionCall.name:type_name -> sqld.v1.ir.QualifiedName
	39, // 14: sqld.v1.ir.FunctionCall.target:type_name -> sqld.v1.ir.ObjectRef
	8,  // 15: sqld.v1.ir.FunctionCall.arguments:type_name -> sqld.v1.ir.Expr
	20, // 16: sqld.v1.ir.FunctionCall.order_by:type_name -> sqld.v1.ir.OrderByItem
	8,  // 17: sqld.v1.ir.FunctionCall.filter:type_name -> sqld.v1.ir.Expr
	35, // 18: sqld.v1.ir.FunctionCall.over:type_name -> sqld.v1.ir.WindowSpec
	8,  // 19: sqld.v1.ir.OperatorExpr.operands:type_name -> sqld.v1.ir.Expr
	8,  // 20: sqld.v1.ir.CaseWhen.condition:type_name -> sqld.v1.ir.Expr
	8,  // 21: sqld.v1.ir.CaseWhen.result:type_name -> sqld.v1.ir.Expr
	8,  // 22: sqld.v1.ir.CaseExpr.operand:type_name -> sqld.v1.ir.Expr
	14, // 23: sqld.v1.ir.CaseExpr.whens:type_name -> sqld.v1.ir.CaseWhen
	8,  // 24: sqld.v1.ir.CaseExpr.else_result:type_name -> sqld.v1.ir.Expr
	8,  // 25: sqld.v1.ir.CastExpr.expr:type_name -> sqld.v1.ir.Expr
	38, // 26: sqld.v1.ir.CastExpr.target_type:type_name -> sqld.v1.ir.TypeRef
	0,  // 27: sqld.v1.ir.SubqueryExpr.kind:type_name -> sqld.v1.ir.SubqueryKind
	26, // 28: sqld.v1.ir.SubqueryExpr.query:type_name -> sqld.v1.ir.SelectStmt
	8,  // 29: sqld.v1.ir.SubqueryExpr.operand:type_name -> sqld.v1.ir.Expr
	8,  // 30: sqld.v1.ir.ListExpr.elements:type_name -> sqld.v1.ir.Expr
	8,  // 31: sqld.v1.ir.OrderByItem.expr:type_name -> sqld.v1.ir.Expr
	1,  // 32: sqld.v1.ir.OrderByItem.order:type_name -> sqld.v1.ir.SortOrder
	2,  // 33: sqld.v1.ir.OrderByItem.nulls:type_name -> sqld.v1.ir.NullsOrder
	8,  // 34: sqld.v1.ir.SelectTarget.expr:type_name -> sqld.v1.ir.Expr
	3,  // 35: sqld.v1.ir.SetOperation.kind:type_name -> sqld.v1.ir.SetOpKind
	26, // 36: sqld.v1.ir.SetOperation.left:type_name -> sqld.v1.ir.SelectStmt
	26, // 37: sqld.v1.ir.SetOperation.right:type_name -> sqld.v1.ir.SelectStmt
	8,  // 38: sqld.v1.ir.SimpleSelect.distinct_on:type_name -> sqld.v1.ir.Expr
	21, // 39: sqld.v1.ir.SimpleSelect.targets:type_name -> sqld.v1.ir.SelectTarget
	32, // 40: sqld.v1.ir.SimpleSelect.from:type_name -> sqld.v1.ir.FromItem
	8,  // 41: sqld.v1.ir.SimpleSelect.where:type_name -> sqld.v1.ir.Expr
	8,  // 42: sqld.v1.ir.SimpleSelect.group_by:type_name -> sqld.v1.ir.Expr
	8,  // 43: sqld.v1.ir.SimpleSelect.having:type_name -> sqld.v1.ir.Expr
	36, // 44: sqld.v1.ir.SimpleSelect.windows:type_name -> sqld.v1.ir.WindowDef
	26, // 45: sqld.v1.ir.CommonTableExpr.query:type_name -> sqld.v1.ir.SelectStmt
	4,  // 46: sqld.v1.ir.CommonTableExpr.materialization:type_name -> sqld.v1.ir.CteMaterialization
	5,  // 47: sqld.v1.ir.LockingClause.strength:type_name -> sqld.v1.ir.LockStrength
	39, // 48: sqld.v1.ir.LockingClause.of_tables:type_name -> sqld.v1.ir.ObjectRef
	6,  // 49: sqld.v1.ir.LockingClause.wait:type_name -> sqld.v1.ir.LockWaitPolicy
	24, // 50: sqld.v1.ir.SelectStmt.with:type_name -> sqld.v1.ir.CommonTableExpr
	23, // 51: sqld.v1.ir.SelectStmt.select:type_name -> sqld.v1.ir.SimpleSelect
	22, // 52: sqld.v1.ir.SelectStmt.set_operation:type_name -> sqld.v1.ir.SetOperation
	34, // 53: sqld.v1.ir.SelectStmt.values:type_name -> sqld.v1.ir.Values
	20, // 54: sqld.v1.ir.SelectStmt.order_by:type_name -> sqld.v1.ir.OrderByItem
	8,  // 55: sqld.v1.ir.SelectStmt.limit:type_name -> sqld.v1.ir.Expr
	8,  // 56: sqld.v1.ir.SelectStmt.offset:type_name -> sqld.v1.ir.Expr
	25, // 57: sqld.v1.ir.SelectStmt.locking:type_name -> sqld.v1.ir.LockingClause
	37, // 58: sqld.v1.ir.SelectStmt.meta:type_name -> sqld.v1.ir.Metadata
	39, // 59: sqld.v1.ir.TableRef.table:type_name -> sqld.v1.ir.ObjectRef
	40, // 60: sqld.v1.ir.TableRef.name:type_name -> sqld.v1.ir.QualifiedName
	26, // 61: sqld.v1.ir.SubqueryRef.query:type_name -> sqld.v1.ir.SelectStmt
	8,  // 62: sqld.v1.ir.FunctionRef.call:type_name -> sqld.v1.ir.Expr
	34, // 63: sqld.v1.ir.ValuesRef.values:type_name -> sqld.v1.ir.Values
	7,  // 64: sqld.v1.ir.JoinClause.type:type_name -> sqld.v1.ir.JoinType
	32, // 65: sqld.v1.ir.JoinClause.left:type_name -> sqld.v1.ir.FromItem
	32, // 66: sqld.v1.ir.JoinClause.right:type_name -> sqld.v1.ir.FromItem
	8,  // 67: sqld.v1.ir.JoinClause.on:type_name -> sqld.v1.ir.Expr
	27, // 68: sqld.v1.ir.FromItem.table:type_name -> sqld.v1.ir.TableRef
	28, // 69: sqld.v1.ir.FromItem.subquery:type_name -> sqld.v1.ir.SubqueryRef
	31, // 70: sqld.v1.ir.FromItem.join:type_name -> sqld.v1.ir.JoinClause
	29, // 71: sqld.v1.ir.FromItem.function:type_name -> sqld.v1.ir.FunctionRef
	30, // 72: sqld.v1.ir.FromItem.values:type_name -> sqld.v1.ir.ValuesRef
	8,  // 73: sqld.v1.ir.ValuesRow.values:type_name -> sqld.v1.ir.Expr
	33, // 74: sqld.v1.ir.Values.rows:type_name -> sqld.v1.ir.ValuesRow
	8,  // 75: sqld.v1.ir.WindowSpec.partition_by:type_name -> sqld.v1.ir.Expr
	20, // 76: sqld.v1.ir.WindowSpec.order_by:type_name -> sqld.v1.ir.OrderByItem
	35, // 77: sqld.v1.ir.WindowDef.spec:type_name -> sqld.v1.ir.WindowSpec
	78, // [78:78] is the sub-list for method output_type
	78, // [78:78] is the sub-list for method input_type
	78, // [78:78] is the sub-list for extension type_name
	78, // [78:78] is the sub-list for extension extendee
	0,  // [0:78] is the sub-list for field type_name
}

func init() { file_sqld_v1_ir_expr_proto_init() }
func file_sqld_v1_ir_expr_proto_init() {
	if File_sqld_v1_ir_expr_proto != nil {
		return
	}
	file_sqld_v1_ir_common_proto_init()
	file_sqld_v1_ir_type_proto_init()
	file_sqld_v1_ir_expr_proto_msgTypes[0].OneofWrappers = []any{
		(*Expr_Literal)(nil),
		(*Expr_ColumnRef)(nil),
		(*Expr_Parameter)(nil),
		(*Expr_FunctionCall)(nil),
		(*Expr_Operator)(nil),
		(*Expr_CaseExpr)(nil),
		(*Expr_Cast)(nil),
		(*Expr_Subquery)(nil),
		(*Expr_List)(nil),
		(*Expr_Star)(nil),
		(*Expr_RawSql)(nil),
	}
	file_sqld_v1_ir_expr_proto_msgTypes[1].OneofWrappers = []any{
		(*Literal_NullValue)(nil),
		(*Literal_IntValue)(nil),
		(*Literal_FloatValue)(nil),
		(*Literal_NumericValue)(nil),
		(*Literal_StringValue)(nil),
		(*Literal_BoolValue)(nil),
		(*Literal_ByteaValue)(nil),
	}
	file_sqld_v1_ir_expr_proto_msgTypes[18].OneofWrappers = []any{
		(*SelectStmt_Select)(nil),
		(*SelectStmt_SetOperation)(nil),
		(*SelectStmt_Values)(nil),
	}
	file_sqld_v1_ir_expr_proto_msgTypes[24].OneofWrappers = []any{
		(*FromItem_Table)(nil),
		(*FromItem_Subquery)(nil),
		(*FromItem_Join)(nil),
		(*FromItem_Function)(nil),
		(*FromItem_Values)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sqld_v1_ir_expr_proto_rawDesc), len(file_sqld_v1_ir_expr_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sqld_v1_ir_expr_proto_goTypes,
		DependencyIndexes: file_sqld_v1_ir_expr_proto_depIdxs,
		EnumInfos:         file_sqld_v1_ir_expr_proto_enumTypes,
		MessageInfos:      file_sqld_v1_ir_expr_proto_msgTypes,
	}.Build()
	File_sqld_v1_ir_expr_proto = out.File
	file_sqld_v1_ir_expr_proto_goTypes = nil
	file_sqld_v1_ir_expr_proto_depIdxs = nil
}
