// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: sqld/v1/ir/relation.proto

package irv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelationshipKind int32

const (
	RelationshipKind_RELATIONSHIP_KIND_UNSPECIFIED  RelationshipKind = 0
	RelationshipKind_RELATIONSHIP_KIND_ONE_TO_ONE   RelationshipKind = 1 // FK columns are unique
	RelationshipKind_RELATIONSHIP_KIND_ONE_TO_MANY  RelationshipKind = 2 // viewed from the referenced side
	RelationshipKind_RELATIONSHIP_KIND_MANY_TO_ONE  RelationshipKind = 3 // viewed from the referencing side
	RelationshipKind_RELATIONSHIP_KIND_MANY_TO_MANY RelationshipKind = 4 // resolved through a join table
)

// Enum value maps for RelationshipKind.
var (
	RelationshipKind_name = map[int32]string{
		0: "RELATIONSHIP_KIND_UNSPECIFIED",
		1: "RELATIONSHIP_KIND_ONE_TO_ONE",
		2: "RELATIONSHIP_KIND_ONE_TO_MANY",
		3: "RELATIONSHIP_KIND_MANY_TO_ONE",
		4: "RELATIONSHIP_KIND_MANY_TO_MANY",
	}
	RelationshipKind_value = map[string]int32{
		"RELATIONSHIP_KIND_UNSPECIFIED":  0,
		"RELATIONSHIP_KIND_ONE_TO_ONE":   1,
		"RELATIONSHIP_KIND_ONE_TO_MANY":  2,
		"RELATIONSHIP_KIND_MANY_TO_ONE":  3,
		"RELATIONSHIP_KIND_MANY_TO_MANY": 4,
	}
)

func (x RelationshipKind) Enum() *RelationshipKind {
	p := new(RelationshipKind)
	*p = x
	return p
}

func (x RelationshipKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelationshipKind) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_relation_proto_enumTypes[0].Descriptor()
}

func (RelationshipKind) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_relation_proto_enumTypes[0]
}

func (x RelationshipKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelationshipKind.Descriptor instead.
func (RelationshipKind) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_relation_proto_rawDescGZIP(), []int{0}
}

// JoinTable describes the link table of a many-to-many relationship.
type JoinTable struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Table          *ObjectRef             `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	FromColumns    []string               `protobuf:"bytes,2,rep,name=from_columns,json=fromColumns,proto3" json:"from_columns,omitempty"`          // join-table cols referencing `from`
	FromConstraint *ObjectRef             `protobuf:"bytes,3,opt,name=from_constraint,json=fromConstraint,proto3" json:"from_constraint,omitempty"` // FK to the `from` table
	ToColumns      []string               `protobuf:"bytes,4,rep,name=to_columns,json=toColumns,proto3" json:"to_columns,omitempty"`                // join-table cols referencing `to`
	ToConstraint   *ObjectRef             `protobuf:"bytes,5,opt,name=to_constraint,json=toConstraint,proto3" json:"to_constraint,omitempty"`       // FK to the `to` table
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JoinTable) Reset() {
	*x = JoinTable{}
	mi := &file_sqld_v1_ir_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTable) ProtoMessage() {}

func (x *JoinTable) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTable.ProtoReflect.Descriptor instead.
func (*JoinTable) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_relation_proto_rawDescGZIP(), []int{0}
}

func (x *JoinTable) GetTable() *ObjectRef {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *JoinTable) GetFromColumns() []string {
	if x != nil {
		return x.FromColumns
	}
	return nil
}

func (x *JoinTable) GetFromConstraint() *ObjectRef {
	if x != nil {
		return x.FromConstraint
	}
	return nil
}

func (x *JoinTable) GetToColumns() []string {
	if x != nil {
		return x.ToColumns
	}
	return nil
}

func (x *JoinTable) GetToConstraint() *ObjectRef {
	if x != nil {
		return x.ToConstraint
	}
	return nil
}

// Relationship is one directional edge derived from foreign-key metadata.
type Relationship struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind  RelationshipKind       `protobuf:"varint,2,opt,name=kind,proto3,enum=sqld.v1.ir.RelationshipKind" json:"kind,omitempty"`
	// The referencing/owning side.
	FromTable   *ObjectRef `protobuf:"bytes,3,opt,name=from_table,json=fromTable,proto3" json:"from_table,omitempty"`
	FromColumns []string   `protobuf:"bytes,4,rep,name=from_columns,json=fromColumns,proto3" json:"from_columns,omitempty"`
	// The referenced/target side.
	ToTable       *ObjectRef `protobuf:"bytes,5,opt,name=to_table,json=toTable,proto3" json:"to_table,omitempty"`
	ToColumns     []string   `protobuf:"bytes,6,rep,name=to_columns,json=toColumns,proto3" json:"to_columns,omitempty"`
	ViaConstraint *ObjectRef `protobuf:"bytes,7,opt,name=via_constraint,json=viaConstraint,proto3" json:"via_constraint,omitempty"`  // source FK constraint (empty for many-to-many)
	JoinTable     *JoinTable `protobuf:"bytes,8,opt,name=join_table,json=joinTable,proto3" json:"join_table,omitempty"`              // set only for MANY_TO_MANY
	Optional      bool       `protobuf:"varint,9,opt,name=optional,proto3" json:"optional,omitempty"`                                // true if the FK columns are nullable
	SuggestedName string     `protobuf:"bytes,10,opt,name=suggested_name,json=suggestedName,proto3" json:"suggested_name,omitempty"` // generator-friendly association name
	Meta          *Metadata  `protobuf:"bytes,15,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relationship) Reset() {
	*x = Relationship{}
	mi := &file_sqld_v1_ir_relation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relationship) ProtoMessage() {}

func (x *Relationship) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_relation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relationship.ProtoReflect.Descriptor instead.
func (*Relationship) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_relation_proto_rawDescGZIP(), []int{1}
}

func (x *Relationship) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Relationship) GetKind() RelationshipKind {
	if x != nil {
		return x.Kind
	}
	return RelationshipKind_RELATIONSHIP_KIND_UNSPECIFIED
}

func (x *Relationship) GetFromTable() *ObjectRef {
	if x != nil {
		return x.FromTable
	}
	return nil
}

func (x *Relationship) GetFromColumns() []string {
	if x != nil {
		return x.FromColumns
	}
	return nil
}

func (x *Relationship) GetToTable() *ObjectRef {
	if x != nil {
		return x.ToTable
	}
	return nil
}

func (x *Relationship) GetToColumns() []string {
	if x != nil {
		return x.ToColumns
	}
	return nil
}

func (x *Relationship) GetViaConstraint() *ObjectRef {
	if x != nil {
		return x.ViaConstraint
	}
	return nil
}

func (x *Relationship) GetJoinTable() *JoinTable {
	if x != nil {
		return x.JoinTable
	}
	return nil
}

func (x *Relationship) GetOptional() bool {
	if x != nil {
		return x.Optional
	}
	return false
}

func (x *Relationship) GetSuggestedName() string {
	if x != nil {
		return x.SuggestedName
	}
	return ""
}

func (x *Relationship) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_sqld_v1_ir_relation_proto protoreflect.FileDescriptor

const file_sqld_v1_ir_relation_proto_rawDesc = "" +
	"\n" +
	"\x19sqld/v1/ir/relation.proto\x12\n" +
	"sqld.v1.ir\x1a\x17sqld/v1/ir/common.proto\"\xf6\x01\n" +
	"\tJoinTable\x12+\n" +
	"\x05table\x18\x01 \x01(\v2\x15.sqld.v1.ir.ObjectRefR\x05table\x12!\n" +
	"\ffrom_columns\x18\x02 \x03(\tR\vfromColumns\x12>\n" +
	"\x0ffrom_constraint\x18\x03 \x01(\v2\x15.sqld.v1.ir.ObjectRefR\x0efromConstraint\x12\x1d\n" +
	"\n" +
	"to_columns\x18\x04 \x03(\tR\ttoColumns\x12:\n" +
	"\rto_constraint\x18\x05 \x01(\v2\x15.sqld.v1.ir.ObjectRefR\ftoConstraint\"\xdb\x03\n" +
	"\fRelationship\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1c.sqld.v1.ir.RelationshipKindR\x04kind\x124\n" +
	"\n" +
	"from_table\x18\x03 \x01(\v2\x15.sqld.v1.ir.ObjectRefR\tfromTable\x12!\n" +
	"\ffrom_columns\x18\x04 \x03(\tR\vfromColumns\x120\n" +
	"\bto_table\x18\x05 \x01(\v2\x15.sqld.v1.ir.ObjectRefR\atoTable\x12\x1d\n" +
	"\n" +
	"to_columns\x18\x06 \x03(\tR\ttoColumns\x12<\n" +
	"\x0evia_constraint\x18\a \x01(\v2\x15.sqld.v1.ir.ObjectRefR\rviaConstraint\x124\n" +
	"\n" +
	"join_table\x18\b \x01(\v2\x15.sqld.v1.ir.JoinTableR\tjoinTable\x12\x1a\n" +
	"\boptional\x18\t \x01(\bR\boptional\x12%\n" +
	"\x0esuggested_name\x18\n" +
	" \x01(\tR\rsuggestedName\x12(\n" +
	"\x04meta\x18\x0f \x01(\v2\x14.sqld.v1.ir.MetadataR\x04meta*\xc1\x01\n" +
	"\x10RelationshipKind\x12!\n" +
	"\x1dRELATIONSHIP_KIND_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cRELATIONSHIP_KIND_ONE_TO_ONE\x10\x01\x12!\n" +
	"\x1dRELATIONSHIP_KIND_ONE_TO_MANY\x10\x02\x12!\n" +
	"\x1dRELATIONSHIP_KIND_MANY_TO_ONE\x10\x03\x12\"\n" +
	"\x1eRELATIONSHIP_KIND_MANY_TO_MANY\x10\x04B4Z2github.com/gopherex/sqld/pkg/proto/sqld/v1/ir;irv1b\x06proto3"

var (
	file_sqld_v1_ir_relation_proto_rawDescOnce sync.Once
	file_sqld_v1_ir_relation_proto_rawDescData []byte
)

func file_sqld_v1_ir_relation_proto_rawDescGZIP() []byte {
	file_sqld_v1_ir_relation_proto_rawDescOnce.Do(func() {
		file_sqld_v1_ir_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sqld_v1_ir_relation_proto_rawDesc), len(file_sqld_v1_ir_relation_proto_rawDesc)))
	})
	return file_sqld_v1_ir_relation_proto_rawDescData
}

var file_sqld_v1_ir_relation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sqld_v1_ir_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sqld_v1_ir_relation_proto_goTypes = []any{
	(RelationshipKind)(0), // 0: sqld.v1.ir.RelationshipKind
	(*JoinTable)(nil),     // 1: sqld.v1.ir.JoinTable
	(*Relationship)(nil),  // 2: sqld.v1.ir.Relationship
	(*ObjectRef)(nil),     // 3: sqld.v1.ir.ObjectRef
	(*Metadata)(nil),      // 4: sqld.v1.ir.Metadata
}
var file_sqld_v1_ir_relation_proto_depIdxs = []int32{
	3, // 0: sqld.v1.ir.JoinTable.table:type_name -> sqld.v1.ir.ObjectRef
	3, // 1: sqld.v1.ir.JoinTable.from_constraint:type_name -> sqld.v1.ir.ObjectRef
	3, // 2: sqld.v1.ir.JoinTable.to_constraint:type_name -> sqld.v1.ir.ObjectRef
	0, // 3: sqld.v1.ir.Relationship.kind:type_name -> sqld.v1.ir.RelationshipKind
	3, // 4: sqld.v1.ir.Relationship.from_table:type_name -> sqld.v1.ir.ObjectRef
	3, // 5: sqld.v1.ir.Relationship.to_table:type_name -> sqld.v1.ir.ObjectRef
	3, // 6: sqld.v1.ir.Relationship.via_constraint:type_name -> sqld.v1.ir.ObjectRef
	1, // 7: sqld.v1.ir.Relationship.join_table:type_name -> sqld.v1.ir.JoinTable
	4, // 8: sqld.v1.ir.Relationship.meta:type_name -> sqld.v1.ir.Metadata
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_sqld_v1_ir_relation_proto_init() }
func file_sqld_v1_ir_relation_proto_init() {
	if File_sqld_v1_ir_relation_proto != nil {
		return
	}
	file_sqld_v1_ir_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sqld_v1_ir_relation_proto_rawDesc), len(file_sqld_v1_ir_relation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sqld_v1_ir_relation_proto_goTypes,
		DependencyIndexes: file_sqld_v1_ir_relation_proto_depIdxs,
		EnumInfos:         file_sqld_v1_ir_relation_proto_enumTypes,
		MessageInfos:      file_sqld_v1_ir_relation_proto_msgTypes,
	}.Build()
	File_sqld_v1_ir_relation_proto = out.File
	file_sqld_v1_ir_relation_proto_goTypes = nil
	file_sqld_v1_ir_relation_proto_depIdxs = nil
}
