// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: sqld/v1/ir/routine.proto

package irv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckOption int32

const (
	CheckOption_CHECK_OPTION_UNSPECIFIED CheckOption = 0 // no WITH CHECK OPTION
	CheckOption_CHECK_OPTION_LOCAL       CheckOption = 1
	CheckOption_CHECK_OPTION_CASCADED    CheckOption = 2
)

// Enum value maps for CheckOption.
var (
	CheckOption_name = map[int32]string{
		0: "CHECK_OPTION_UNSPECIFIED",
		1: "CHECK_OPTION_LOCAL",
		2: "CHECK_OPTION_CASCADED",
	}
	CheckOption_value = map[string]int32{
		"CHECK_OPTION_UNSPECIFIED": 0,
		"CHECK_OPTION_LOCAL":       1,
		"CHECK_OPTION_CASCADED":    2,
	}
)

func (x CheckOption) Enum() *CheckOption {
	p := new(CheckOption)
	*p = x
	return p
}

func (x CheckOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckOption) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_routine_proto_enumTypes[0].Descriptor()
}

func (CheckOption) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_routine_proto_enumTypes[0]
}

func (x CheckOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckOption.Descriptor instead.
func (CheckOption) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{0}
}

type ArgMode int32

const (
	ArgMode_ARG_MODE_UNSPECIFIED ArgMode = 0 // IN (default)
	ArgMode_ARG_MODE_IN          ArgMode = 1
	ArgMode_ARG_MODE_OUT         ArgMode = 2
	ArgMode_ARG_MODE_INOUT       ArgMode = 3
	ArgMode_ARG_MODE_VARIADIC    ArgMode = 4
)

// Enum value maps for ArgMode.
var (
	ArgMode_name = map[int32]string{
		0: "ARG_MODE_UNSPECIFIED",
		1: "ARG_MODE_IN",
		2: "ARG_MODE_OUT",
		3: "ARG_MODE_INOUT",
		4: "ARG_MODE_VARIADIC",
	}
	ArgMode_value = map[string]int32{
		"ARG_MODE_UNSPECIFIED": 0,
		"ARG_MODE_IN":          1,
		"ARG_MODE_OUT":         2,
		"ARG_MODE_INOUT":       3,
		"ARG_MODE_VARIADIC":    4,
	}
)

func (x ArgMode) Enum() *ArgMode {
	p := new(ArgMode)
	*p = x
	return p
}

func (x ArgMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArgMode) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_routine_proto_enumTypes[1].Descriptor()
}

func (ArgMode) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_routine_proto_enumTypes[1]
}

func (x ArgMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArgMode.Descriptor instead.
func (ArgMode) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{1}
}

type Volatility int32

const (
	Volatility_VOLATILITY_UNSPECIFIED Volatility = 0 // VOLATILE (default)
	Volatility_VOLATILITY_VOLATILE    Volatility = 1
	Volatility_VOLATILITY_STABLE      Volatility = 2
	Volatility_VOLATILITY_IMMUTABLE   Volatility = 3
)

// Enum value maps for Volatility.
var (
	Volatility_name = map[int32]string{
		0: "VOLATILITY_UNSPECIFIED",
		1: "VOLATILITY_VOLATILE",
		2: "VOLATILITY_STABLE",
		3: "VOLATILITY_IMMUTABLE",
	}
	Volatility_value = map[string]int32{
		"VOLATILITY_UNSPECIFIED": 0,
		"VOLATILITY_VOLATILE":    1,
		"VOLATILITY_STABLE":      2,
		"VOLATILITY_IMMUTABLE":   3,
	}
)

func (x Volatility) Enum() *Volatility {
	p := new(Volatility)
	*p = x
	return p
}

func (x Volatility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Volatility) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_routine_proto_enumTypes[2].Descriptor()
}

func (Volatility) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_routine_proto_enumTypes[2]
}

func (x Volatility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Volatility.Descriptor instead.
func (Volatility) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{2}
}

type ParallelSafety int32

const (
	ParallelSafety_PARALLEL_SAFETY_UNSPECIFIED ParallelSafety = 0 // UNSAFE (default)
	ParallelSafety_PARALLEL_SAFETY_UNSAFE      ParallelSafety = 1
	ParallelSafety_PARALLEL_SAFETY_RESTRICTED  ParallelSafety = 2
	ParallelSafety_PARALLEL_SAFETY_SAFE        ParallelSafety = 3
)

// Enum value maps for ParallelSafety.
var (
	ParallelSafety_name = map[int32]string{
		0: "PARALLEL_SAFETY_UNSPECIFIED",
		1: "PARALLEL_SAFETY_UNSAFE",
		2: "PARALLEL_SAFETY_RESTRICTED",
		3: "PARALLEL_SAFETY_SAFE",
	}
	ParallelSafety_value = map[string]int32{
		"PARALLEL_SAFETY_UNSPECIFIED": 0,
		"PARALLEL_SAFETY_UNSAFE":      1,
		"PARALLEL_SAFETY_RESTRICTED":  2,
		"PARALLEL_SAFETY_SAFE":        3,
	}
)

func (x ParallelSafety) Enum() *ParallelSafety {
	p := new(ParallelSafety)
	*p = x
	return p
}

func (x ParallelSafety) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParallelSafety) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_routine_proto_enumTypes[3].Descriptor()
}

func (ParallelSafety) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_routine_proto_enumTypes[3]
}

func (x ParallelSafety) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParallelSafety.Descriptor instead.
func (ParallelSafety) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{3}
}

type NullInputBehavior int32

const (
	NullInputBehavior_NULL_INPUT_BEHAVIOR_UNSPECIFIED NullInputBehavior = 0 // CALLED ON NULL INPUT (default)
	NullInputBehavior_NULL_INPUT_BEHAVIOR_CALLED      NullInputBehavior = 1
	NullInputBehavior_NULL_INPUT_BEHAVIOR_STRICT      NullInputBehavior = 2 // RETURNS NULL ON NULL INPUT
)

// Enum value maps for NullInputBehavior.
var (
	NullInputBehavior_name = map[int32]string{
		0: "NULL_INPUT_BEHAVIOR_UNSPECIFIED",
		1: "NULL_INPUT_BEHAVIOR_CALLED",
		2: "NULL_INPUT_BEHAVIOR_STRICT",
	}
	NullInputBehavior_value = map[string]int32{
		"NULL_INPUT_BEHAVIOR_UNSPECIFIED": 0,
		"NULL_INPUT_BEHAVIOR_CALLED":      1,
		"NULL_INPUT_BEHAVIOR_STRICT":      2,
	}
)

func (x NullInputBehavior) Enum() *NullInputBehavior {
	p := new(NullInputBehavior)
	*p = x
	return p
}

func (x NullInputBehavior) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NullInputBehavior) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_routine_proto_enumTypes[4].Descriptor()
}

func (NullInputBehavior) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_routine_proto_enumTypes[4]
}

func (x NullInputBehavior) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NullInputBehavior.Descriptor instead.
func (NullInputBehavior) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{4}
}

type TriggerTiming int32

const (
	TriggerTiming_TRIGGER_TIMING_UNSPECIFIED TriggerTiming = 0
	TriggerTiming_TRIGGER_TIMING_BEFORE      TriggerTiming = 1
	TriggerTiming_TRIGGER_TIMING_AFTER       TriggerTiming = 2
	TriggerTiming_TRIGGER_TIMING_INSTEAD_OF  TriggerTiming = 3
)

// Enum value maps for TriggerTiming.
var (
	TriggerTiming_name = map[int32]string{
		0: "TRIGGER_TIMING_UNSPECIFIED",
		1: "TRIGGER_TIMING_BEFORE",
		2: "TRIGGER_TIMING_AFTER",
		3: "TRIGGER_TIMING_INSTEAD_OF",
	}
	TriggerTiming_value = map[string]int32{
		"TRIGGER_TIMING_UNSPECIFIED": 0,
		"TRIGGER_TIMING_BEFORE":      1,
		"TRIGGER_TIMING_AFTER":       2,
		"TRIGGER_TIMING_INSTEAD_OF":  3,
	}
)

func (x TriggerTiming) Enum() *TriggerTiming {
	p := new(TriggerTiming)
	*p = x
	return p
}

func (x TriggerTiming) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TriggerTiming) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_routine_proto_enumTypes[5].Descriptor()
}

func (TriggerTiming) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_routine_proto_enumTypes[5]
}

func (x TriggerTiming) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TriggerTiming.Descriptor instead.
func (TriggerTiming) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{5}
}

type TriggerEvent int32

const (
	TriggerEvent_TRIGGER_EVENT_UNSPECIFIED TriggerEvent = 0
	TriggerEvent_TRIGGER_EVENT_INSERT      TriggerEvent = 1
	TriggerEvent_TRIGGER_EVENT_UPDATE      TriggerEvent = 2
	TriggerEvent_TRIGGER_EVENT_DELETE      TriggerEvent = 3
	TriggerEvent_TRIGGER_EVENT_TRUNCATE    TriggerEvent = 4
)

// Enum value maps for TriggerEvent.
var (
	TriggerEvent_name = map[int32]string{
		0: "TRIGGER_EVENT_UNSPECIFIED",
		1: "TRIGGER_EVENT_INSERT",
		2: "TRIGGER_EVENT_UPDATE",
		3: "TRIGGER_EVENT_DELETE",
		4: "TRIGGER_EVENT_TRUNCATE",
	}
	TriggerEvent_value = map[string]int32{
		"TRIGGER_EVENT_UNSPECIFIED": 0,
		"TRIGGER_EVENT_INSERT":      1,
		"TRIGGER_EVENT_UPDATE":      2,
		"TRIGGER_EVENT_DELETE":      3,
		"TRIGGER_EVENT_TRUNCATE":    4,
	}
)

func (x TriggerEvent) Enum() *TriggerEvent {
	p := new(TriggerEvent)
	*p = x
	return p
}

func (x TriggerEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TriggerEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_routine_proto_enumTypes[6].Descriptor()
}

func (TriggerEvent) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_routine_proto_enumTypes[6]
}

func (x TriggerEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TriggerEvent.Descriptor instead.
func (TriggerEvent) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{6}
}

type TriggerLevel int32

const (
	TriggerLevel_TRIGGER_LEVEL_UNSPECIFIED TriggerLevel = 0
	TriggerLevel_TRIGGER_LEVEL_ROW         TriggerLevel = 1 // FOR EACH ROW
	TriggerLevel_TRIGGER_LEVEL_STATEMENT   TriggerLevel = 2 // FOR EACH STATEMENT
)

// Enum value maps for TriggerLevel.
var (
	TriggerLevel_name = map[int32]string{
		0: "TRIGGER_LEVEL_UNSPECIFIED",
		1: "TRIGGER_LEVEL_ROW",
		2: "TRIGGER_LEVEL_STATEMENT",
	}
	TriggerLevel_value = map[string]int32{
		"TRIGGER_LEVEL_UNSPECIFIED": 0,
		"TRIGGER_LEVEL_ROW":         1,
		"TRIGGER_LEVEL_STATEMENT":   2,
	}
)

func (x TriggerLevel) Enum() *TriggerLevel {
	p := new(TriggerLevel)
	*p = x
	return p
}

func (x TriggerLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TriggerLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_routine_proto_enumTypes[7].Descriptor()
}

func (TriggerLevel) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_routine_proto_enumTypes[7]
}

func (x TriggerLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TriggerLevel.Descriptor instead.
func (TriggerLevel) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{7}
}

type EnumType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *QualifiedName         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Labels        []string               `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"` // ordered
	Meta          *Metadata              `protobuf:"bytes,15,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumType) Reset() {
	*x = EnumType{}
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumType) ProtoMessage() {}

func (x *EnumType) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumType.ProtoReflect.Descriptor instead.
func (*EnumType) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{0}
}

func (x *EnumType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EnumType) GetName() *QualifiedName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *EnumType) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *EnumType) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type DomainConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Check         *Expr                  `protobuf:"bytes,2,opt,name=check,proto3" json:"check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainConstraint) Reset() {
	*x = DomainConstraint{}
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainConstraint) ProtoMessage() {}

func (x *DomainConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainConstraint.ProtoReflect.Descriptor instead.
func (*DomainConstraint) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{1}
}

func (x *DomainConstraint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DomainConstraint) GetCheck() *Expr {
	if x != nil {
		return x.Check
	}
	return nil
}

type DomainType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *QualifiedName         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BaseType      *TypeRef               `protobuf:"bytes,3,opt,name=base_type,json=baseType,proto3" json:"base_type,omitempty"`
	Nullable      bool                   `protobuf:"varint,4,opt,name=nullable,proto3" json:"nullable,omitempty"` // false => NOT NULL
	DefaultExpr   *Expr                  `protobuf:"bytes,5,opt,name=default_expr,json=defaultExpr,proto3" json:"default_expr,omitempty"`
	Collation     string                 `protobuf:"bytes,6,opt,name=collation,proto3" json:"collation,omitempty"`
	Constraints   []*DomainConstraint    `protobuf:"bytes,7,rep,name=constraints,proto3" json:"constraints,omitempty"`
	Meta          *Metadata              `protobuf:"bytes,15,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainType) Reset() {
	*x = DomainType{}
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainType) ProtoMessage() {}

func (x *DomainType) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainType.ProtoReflect.Descriptor instead.
func (*DomainType) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{2}
}

func (x *DomainType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DomainType) GetName() *QualifiedName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *DomainType) GetBaseType() *TypeRef {
	if x != nil {
		return x.BaseType
	}
	return nil
}

func (x *DomainType) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *DomainType) GetDefaultExpr() *Expr {
	if x != nil {
		return x.DefaultExpr
	}
	return nil
}

func (x *DomainType) GetCollation() string {
	if x != nil {
		return x.Collation
	}
	return ""
}

func (x *DomainType) GetConstraints() []*DomainConstraint {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *DomainType) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type CompositeField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          *TypeRef               `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Collation     string                 `protobuf:"bytes,3,opt,name=collation,proto3" json:"collation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompositeField) Reset() {
	*x = CompositeField{}
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositeField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositeField) ProtoMessage() {}

func (x *CompositeField) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositeField.ProtoReflect.Descriptor instead.
func (*CompositeField) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{3}
}

func (x *CompositeField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompositeField) GetType() *TypeRef {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *CompositeField) GetCollation() string {
	if x != nil {
		return x.Collation
	}
	return ""
}

type CompositeType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *QualifiedName         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Fields        []*CompositeField      `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Meta          *Metadata              `protobuf:"bytes,15,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompositeType) Reset() {
	*x = CompositeType{}
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositeType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositeType) ProtoMessage() {}

func (x *CompositeType) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositeType.ProtoReflect.Descriptor instead.
func (*CompositeType) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{4}
}

func (x *CompositeType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompositeType) GetName() *QualifiedName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *CompositeType) GetFields() []*CompositeField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *CompositeType) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type RangeType struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           *QualifiedName         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subtype        *TypeRef               `protobuf:"bytes,3,opt,name=subtype,proto3" json:"subtype,omitempty"`
	SubtypeOpclass string                 `protobuf:"bytes,4,opt,name=subtype_opclass,json=subtypeOpclass,proto3" json:"subtype_opclass,omitempty"`
	Collation      string                 `protobuf:"bytes,5,opt,name=collation,proto3" json:"collation,omitempty"`
	Canonical      string                 `protobuf:"bytes,6,opt,name=canonical,proto3" json:"canonical,omitempty"`                        // canonical function name
	SubtypeDiff    string                 `protobuf:"bytes,7,opt,name=subtype_diff,json=subtypeDiff,proto3" json:"subtype_diff,omitempty"` // subtype_diff function name
	Multirange     string                 `protobuf:"bytes,8,opt,name=multirange,proto3" json:"multirange,omitempty"`                      // associated multirange type name (PG 14+)
	Meta           *Metadata              `protobuf:"bytes,15,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RangeType) Reset() {
	*x = RangeType{}
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeType) ProtoMessage() {}

func (x *RangeType) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeType.ProtoReflect.Descriptor instead.
func (*RangeType) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{5}
}

func (x *RangeType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RangeType) GetName() *QualifiedName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *RangeType) GetSubtype() *TypeRef {
	if x != nil {
		return x.Subtype
	}
	return nil
}

func (x *RangeType) GetSubtypeOpclass() string {
	if x != nil {
		return x.SubtypeOpclass
	}
	return ""
}

func (x *RangeType) GetCollation() string {
	if x != nil {
		return x.Collation
	}
	return ""
}

func (x *RangeType) GetCanonical() string {
	if x != nil {
		return x.Canonical
	}
	return ""
}

func (x *RangeType) GetSubtypeDiff() string {
	if x != nil {
		return x.SubtypeDiff
	}
	return ""
}

func (x *RangeType) GetMultirange() string {
	if x != nil {
		return x.Multirange
	}
	return ""
}

func (x *RangeType) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type View struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            *QualifiedName         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Columns         []string               `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"` // explicit column list, if given
	Query           *SelectStmt            `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	CheckOption     CheckOption            `protobuf:"varint,5,opt,name=check_option,json=checkOption,proto3,enum=sqld.v1.ir.CheckOption" json:"check_option,omitempty"`
	SecurityBarrier bool                   `protobuf:"varint,6,opt,name=security_barrier,json=securityBarrier,proto3" json:"security_barrier,omitempty"`
	Meta            *Metadata              `protobuf:"bytes,15,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *View) Reset() {
	*x = View{}
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *View) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*View) ProtoMessage() {}

func (x *View) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use View.ProtoReflect.Descriptor instead.
func (*View) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{6}
}

func (x *View) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *View) GetName() *QualifiedName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *View) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *View) GetQuery() *SelectStmt {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *View) GetCheckOption() CheckOption {
	if x != nil {
		return x.CheckOption
	}
	return CheckOption_CHECK_OPTION_UNSPECIFIED
}

func (x *View) GetSecurityBarrier() bool {
	if x != nil {
		return x.SecurityBarrier
	}
	return false
}

func (x *View) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type MaterializedView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *QualifiedName         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Columns       []string               `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
	Query         *SelectStmt            `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	WithData      bool                   `protobuf:"varint,5,opt,name=with_data,json=withData,proto3" json:"with_data,omitempty"` // WITH DATA vs WITH NO DATA
	Indexes       []*Index               `protobuf:"bytes,6,rep,name=indexes,proto3" json:"indexes,omitempty"`
	Tablespace    string                 `protobuf:"bytes,7,opt,name=tablespace,proto3" json:"tablespace,omitempty"`
	Meta          *Metadata              `protobuf:"bytes,15,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterializedView) Reset() {
	*x = MaterializedView{}
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializedView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializedView) ProtoMessage() {}

func (x *MaterializedView) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializedView.ProtoReflect.Descriptor instead.
func (*MaterializedView) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{7}
}

func (x *MaterializedView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MaterializedView) GetName() *QualifiedName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *MaterializedView) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *MaterializedView) GetQuery() *SelectStmt {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *MaterializedView) GetWithData() bool {
	if x != nil {
		return x.WithData
	}
	return false
}

func (x *MaterializedView) GetIndexes() []*Index {
	if x != nil {
		return x.Indexes
	}
	return nil
}

func (x *MaterializedView) GetTablespace() string {
	if x != nil {
		return x.Tablespace
	}
	return ""
}

func (x *MaterializedView) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type Argument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // may be empty for positional-only
	Type          *TypeRef               `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Mode          ArgMode                `protobuf:"varint,3,opt,name=mode,proto3,enum=sqld.v1.ir.ArgMode" json:"mode,omitempty"`
	DefaultValue  *Expr                  `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"` // DEFAULT expr
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Argument) Reset() {
	*x = Argument{}
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Argument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Argument) ProtoMessage() {}

func (x *Argument) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Argument.ProtoReflect.Descriptor instead.
func (*Argument) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{8}
}

func (x *Argument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Argument) GetType() *TypeRef {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Argument) GetMode() ArgMode {
	if x != nil {
		return x.Mode
	}
	return ArgMode_ARG_MODE_UNSPECIFIED
}

func (x *Argument) GetDefaultValue() *Expr {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

type SetofType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *TypeRef               `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // RETURNS SETOF <type>
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetofType) Reset() {
	*x = SetofType{}
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetofType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetofType) ProtoMessage() {}

func (x *SetofType) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetofType.ProtoReflect.Descriptor instead.
func (*SetofType) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{9}
}

func (x *SetofType) GetType() *TypeRef {
	if x != nil {
		return x.Type
	}
	return nil
}

type TableColumn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          *TypeRef               `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableColumn) Reset() {
	*x = TableColumn{}
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableColumn) ProtoMessage() {}

func (x *TableColumn) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableColumn.ProtoReflect.Descriptor instead.
func (*TableColumn) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{10}
}

func (x *TableColumn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableColumn) GetType() *TypeRef {
	if x != nil {
		return x.Type
	}
	return nil
}

type TableReturn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []*TableColumn         `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"` // RETURNS TABLE(col type, ...)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableReturn) Reset() {
	*x = TableReturn{}
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableReturn) ProtoMessage() {}

func (x *TableReturn) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableReturn.ProtoReflect.Descriptor instead.
func (*TableReturn) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{11}
}

func (x *TableReturn) GetColumns() []*TableColumn {
	if x != nil {
		return x.Columns
	}
	return nil
}

type ReturnType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ReturnType_Scalar
	//	*ReturnType_Setof
	//	*ReturnType_Table
	//	*ReturnType_VoidValue
	//	*ReturnType_TriggerValue
	Kind          isReturnType_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnType) Reset() {
	*x = ReturnType{}
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnType) ProtoMessage() {}

func (x *ReturnType) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnType.ProtoReflect.Descriptor instead.
func (*ReturnType) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{12}
}

func (x *ReturnType) GetKind() isReturnType_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ReturnType) GetScalar() *TypeRef {
	if x != nil {
		if x, ok := x.Kind.(*ReturnType_Scalar); ok {
			return x.Scalar
		}
	}
	return nil
}

func (x *ReturnType) GetSetof() *SetofType {
	if x != nil {
		if x, ok := x.Kind.(*ReturnType_Setof); ok {
			return x.Setof
		}
	}
	return nil
}

func (x *ReturnType) GetTable() *TableReturn {
	if x != nil {
		if x, ok := x.Kind.(*ReturnType_Table); ok {
			return x.Table
		}
	}
	return nil
}

func (x *ReturnType) GetVoidValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*ReturnType_VoidValue); ok {
			return x.VoidValue
		}
	}
	return false
}

func (x *ReturnType) GetTriggerValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*ReturnType_TriggerValue); ok {
			return x.TriggerValue
		}
	}
	return false
}

type isReturnType_Kind interface {
	isReturnType_Kind()
}

type ReturnType_Scalar struct {
	Scalar *TypeRef `protobuf:"bytes,1,opt,name=scalar,proto3,oneof"`
}

type ReturnType_Setof struct {
	Setof *SetofType `protobuf:"bytes,2,opt,name=setof,proto3,oneof"`
}

type ReturnType_Table struct {
	Table *TableReturn `protobuf:"bytes,3,opt,name=table,proto3,oneof"`
}

type ReturnType_VoidValue struct {
	VoidValue bool `protobuf:"varint,4,opt,name=void_value,json=voidValue,proto3,oneof"` // RETURNS void
}

type ReturnType_TriggerValue struct {
	TriggerValue bool `protobuf:"varint,5,opt,name=trigger_value,json=triggerValue,proto3,oneof"` // RETURNS trigger
}

func (*ReturnType_Scalar) isReturnType_Kind() {}

func (*ReturnType_Setof) isReturnType_Kind() {}

func (*ReturnType_Table) isReturnType_Kind() {}

func (*ReturnType_VoidValue) isReturnType_Kind() {}

func (*ReturnType_TriggerValue) isReturnType_Kind() {}

type Function struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            *QualifiedName         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Arguments       []*Argument            `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	Returns         *ReturnType            `protobuf:"bytes,4,opt,name=returns,proto3" json:"returns,omitempty"`
	Language        string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"` // sql, plpgsql, c, ...
	Volatility      Volatility             `protobuf:"varint,6,opt,name=volatility,proto3,enum=sqld.v1.ir.Volatility" json:"volatility,omitempty"`
	NullInput       NullInputBehavior      `protobuf:"varint,7,opt,name=null_input,json=nullInput,proto3,enum=sqld.v1.ir.NullInputBehavior" json:"null_input,omitempty"`
	SecurityDefiner bool                   `protobuf:"varint,8,opt,name=security_definer,json=securityDefiner,proto3" json:"security_definer,omitempty"` // false => SECURITY INVOKER
	Leakproof       bool                   `protobuf:"varint,9,opt,name=leakproof,proto3" json:"leakproof,omitempty"`
	Parallel        ParallelSafety         `protobuf:"varint,10,opt,name=parallel,proto3,enum=sqld.v1.ir.ParallelSafety" json:"parallel,omitempty"`
	EstimatedCost   int32                  `protobuf:"varint,11,opt,name=estimated_cost,json=estimatedCost,proto3" json:"estimated_cost,omitempty"`
	EstimatedRows   int32                  `protobuf:"varint,12,opt,name=estimated_rows,json=estimatedRows,proto3" json:"estimated_rows,omitempty"`
	Body            string                 `protobuf:"bytes,13,opt,name=body,proto3" json:"body,omitempty"`                      // routine body source (AS '...')
	SqlBody         []*SelectStmt          `protobuf:"bytes,14,rep,name=sql_body,json=sqlBody,proto3" json:"sql_body,omitempty"` // standard SQL-body (BEGIN ATOMIC ...)
	Meta            *Metadata              `protobuf:"bytes,20,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{13}
}

func (x *Function) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Function) GetName() *QualifiedName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Function) GetArguments() []*Argument {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *Function) GetReturns() *ReturnType {
	if x != nil {
		return x.Returns
	}
	return nil
}

func (x *Function) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Function) GetVolatility() Volatility {
	if x != nil {
		return x.Volatility
	}
	return Volatility_VOLATILITY_UNSPECIFIED
}

func (x *Function) GetNullInput() NullInputBehavior {
	if x != nil {
		return x.NullInput
	}
	return NullInputBehavior_NULL_INPUT_BEHAVIOR_UNSPECIFIED
}

func (x *Function) GetSecurityDefiner() bool {
	if x != nil {
		return x.SecurityDefiner
	}
	return false
}

func (x *Function) GetLeakproof() bool {
	if x != nil {
		return x.Leakproof
	}
	return false
}

func (x *Function) GetParallel() ParallelSafety {
	if x != nil {
		return x.Parallel
	}
	return ParallelSafety_PARALLEL_SAFETY_UNSPECIFIED
}

func (x *Function) GetEstimatedCost() int32 {
	if x != nil {
		return x.EstimatedCost
	}
	return 0
}

func (x *Function) GetEstimatedRows() int32 {
	if x != nil {
		return x.EstimatedRows
	}
	return 0
}

func (x *Function) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Function) GetSqlBody() []*SelectStmt {
	if x != nil {
		return x.SqlBody
	}
	return nil
}

func (x *Function) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type Procedure struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            *QualifiedName         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Arguments       []*Argument            `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	Language        string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	SecurityDefiner bool                   `protobuf:"varint,5,opt,name=security_definer,json=securityDefiner,proto3" json:"security_definer,omitempty"`
	Body            string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	SqlBody         []*SelectStmt          `protobuf:"bytes,7,rep,name=sql_body,json=sqlBody,proto3" json:"sql_body,omitempty"`
	Meta            *Metadata              `protobuf:"bytes,15,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Procedure) Reset() {
	*x = Procedure{}
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Procedure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Procedure) ProtoMessage() {}

func (x *Procedure) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Procedure.ProtoReflect.Descriptor instead.
func (*Procedure) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{14}
}

func (x *Procedure) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Procedure) GetName() *QualifiedName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Procedure) GetArguments() []*Argument {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *Procedure) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Procedure) GetSecurityDefiner() bool {
	if x != nil {
		return x.SecurityDefiner
	}
	return false
}

func (x *Procedure) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Procedure) GetSqlBody() []*SelectStmt {
	if x != nil {
		return x.SqlBody
	}
	return nil
}

func (x *Procedure) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type Trigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Table         *ObjectRef             `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"` // table the trigger is attached to
	Timing        TriggerTiming          `protobuf:"varint,4,opt,name=timing,proto3,enum=sqld.v1.ir.TriggerTiming" json:"timing,omitempty"`
	Events        []TriggerEvent         `protobuf:"varint,5,rep,packed,name=events,proto3,enum=sqld.v1.ir.TriggerEvent" json:"events,omitempty"`
	UpdateColumns []string               `protobuf:"bytes,6,rep,name=update_columns,json=updateColumns,proto3" json:"update_columns,omitempty"` // UPDATE OF col, ...
	Level         TriggerLevel           `protobuf:"varint,7,opt,name=level,proto3,enum=sqld.v1.ir.TriggerLevel" json:"level,omitempty"`
	Constraint    bool                   `protobuf:"varint,8,opt,name=constraint,proto3" json:"constraint,omitempty"` // CONSTRAINT TRIGGER
	When          *Expr                  `protobuf:"bytes,9,opt,name=when,proto3" json:"when,omitempty"`              // WHEN (condition)
	Function      *ObjectRef             `protobuf:"bytes,10,opt,name=function,proto3" json:"function,omitempty"`     // EXECUTE FUNCTION ...
	Arguments     []string               `protobuf:"bytes,11,rep,name=arguments,proto3" json:"arguments,omitempty"`   // function arguments
	Meta          *Metadata              `protobuf:"bytes,15,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trigger) Reset() {
	*x = Trigger{}
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trigger) ProtoMessage() {}

func (x *Trigger) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_routine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trigger.ProtoReflect.Descriptor instead.
func (*Trigger) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_routine_proto_rawDescGZIP(), []int{15}
}

func (x *Trigger) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trigger) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Trigger) GetTable() *ObjectRef {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *Trigger) GetTiming() TriggerTiming {
	if x != nil {
		return x.Timing
	}
	return TriggerTiming_TRIGGER_TIMING_UNSPECIFIED
}

func (x *Trigger) GetEvents() []TriggerEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Trigger) GetUpdateColumns() []string {
	if x != nil {
		return x.UpdateColumns
	}
	return nil
}

func (x *Trigger) GetLevel() TriggerLevel {
	if x != nil {
		return x.Level
	}
	return TriggerLevel_TRIGGER_LEVEL_UNSPECIFIED
}

func (x *Trigger) GetConstraint() bool {
	if x != nil {
		return x.Constraint
	}
	return false
}

func (x *Trigger) GetWhen() *Expr {
	if x != nil {
		return x.When
	}
	return nil
}

func (x *Trigger) GetFunction() *ObjectRef {
	if x != nil {
		return x.Function
	}
	return nil
}

func (x *Trigger) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *Trigger) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_sqld_v1_ir_routine_proto protoreflect.FileDescriptor

const file_sqld_v1_ir_routine_proto_rawDesc = "" +
	"\n" +
	"\x18sqld/v1/ir/routine.proto\x12\n" +
	"sqld.v1.ir\x1a\x17sqld/v1/ir/common.proto\x1a\x15sqld/v1/ir/type.proto\x1a\x15sqld/v1/ir/expr.proto\x1a\x17sqld/v1/ir/schema.proto\"\x8b\x01\n" +
	"\bEnumType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04name\x18\x02 \x01(\v2\x19.sqld.v1.ir.QualifiedNameR\x04name\x12\x16\n" +
	"\x06labels\x18\x03 \x03(\tR\x06labels\x12(\n" +
	"\x04meta\x18\x0f \x01(\v2\x14.sqld.v1.ir.MetadataR\x04meta\"N\n" +
	"\x10DomainConstraint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x05check\x18\x02 \x01(\v2\x10.sqld.v1.ir.ExprR\x05check\"\xd6\x02\n" +
	"\n" +
	"DomainType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04name\x18\x02 \x01(\v2\x19.sqld.v1.ir.QualifiedNameR\x04name\x120\n" +
	"\tbase_type\x18\x03 \x01(\v2\x13.sqld.v1.ir.TypeRefR\bbaseType\x12\x1a\n" +
	"\bnullable\x18\x04 \x01(\bR\bnullable\x123\n" +
	"\fdefault_expr\x18\x05 \x01(\v2\x10.sqld.v1.ir.ExprR\vdefaultExpr\x12\x1c\n" +
	"\tcollation\x18\x06 \x01(\tR\tcollation\x12>\n" +
	"\vconstraints\x18\a \x03(\v2\x1c.sqld.v1.ir.DomainConstraintR\vconstraints\x12(\n" +
	"\x04meta\x18\x0f \x01(\v2\x14.sqld.v1.ir.MetadataR\x04meta\"k\n" +
	"\x0eCompositeField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x04type\x18\x02 \x01(\v2\x13.sqld.v1.ir.TypeRefR\x04type\x12\x1c\n" +
	"\tcollation\x18\x03 \x01(\tR\tcollation\"\xac\x01\n" +
	"\rCompositeType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04name\x18\x02 \x01(\v2\x19.sqld.v1.ir.QualifiedNameR\x04name\x122\n" +
	"\x06fields\x18\x03 \x03(\v2\x1a.sqld.v1.ir.CompositeFieldR\x06fields\x12(\n" +
	"\x04meta\x18\x0f \x01(\v2\x14.sqld.v1.ir.MetadataR\x04meta\"\xcb\x02\n" +
	"\tRangeType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04name\x18\x02 \x01(\v2\x19.sqld.v1.ir.QualifiedNameR\x04name\x12-\n" +
	"\asubtype\x18\x03 \x01(\v2\x13.sqld.v1.ir.TypeRefR\asubtype\x12'\n" +
	"\x0fsubtype_opclass\x18\x04 \x01(\tR\x0esubtypeOpclass\x12\x1c\n" +
	"\tcollation\x18\x05 \x01(\tR\tcollation\x12\x1c\n" +
	"\tcanonical\x18\x06 \x01(\tR\tcanonical\x12!\n" +
	"\fsubtype_diff\x18\a \x01(\tR\vsubtypeDiff\x12\x1e\n" +
	"\n" +
	"multirange\x18\b \x01(\tR\n" +
	"multirange\x12(\n" +
	"\x04meta\x18\x0f \x01(\v2\x14.sqld.v1.ir.MetadataR\x04meta\"\x9e\x02\n" +
	"\x04View\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04name\x18\x02 \x01(\v2\x19.sqld.v1.ir.QualifiedNameR\x04name\x12\x18\n" +
	"\acolumns\x18\x03 \x03(\tR\acolumns\x12,\n" +
	"\x05query\x18\x04 \x01(\v2\x16.sqld.v1.ir.SelectStmtR\x05query\x12:\n" +
	"\fcheck_option\x18\x05 \x01(\x0e2\x17.sqld.v1.ir.CheckOptionR\vcheckOption\x12)\n" +
	"\x10security_barrier\x18\x06 \x01(\bR\x0fsecurityBarrier\x12(\n" +
	"\x04meta\x18\x0f \x01(\v2\x14.sqld.v1.ir.MetadataR\x04meta\"\xad\x02\n" +
	"\x10MaterializedView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04name\x18\x02 \x01(\v2\x19.sqld.v1.ir.QualifiedNameR\x04name\x12\x18\n" +
	"\acolumns\x18\x03 \x03(\tR\acolumns\x12,\n" +
	"\x05query\x18\x04 \x01(\v2\x16.sqld.v1.ir.SelectStmtR\x05query\x12\x1b\n" +
	"\twith_data\x18\x05 \x01(\bR\bwithData\x12+\n" +
	"\aindexes\x18\x06 \x03(\v2\x11.sqld.v1.ir.IndexR\aindexes\x12\x1e\n" +
	"\n" +
	"tablespace\x18\a \x01(\tR\n" +
	"tablespace\x12(\n" +
	"\x04meta\x18\x0f \x01(\v2\x14.sqld.v1.ir.MetadataR\x04meta\"\xa7\x01\n" +
	"\bArgument\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x04type\x18\x02 \x01(\v2\x13.sqld.v1.ir.TypeRefR\x04type\x12'\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x13.sqld.v1.ir.ArgModeR\x04mode\x125\n" +
	"\rdefault_value\x18\x04 \x01(\v2\x10.sqld.v1.ir.ExprR\fdefaultValue\"4\n" +
	"\tSetofType\x12'\n" +
	"\x04type\x18\x01 \x01(\v2\x13.sqld.v1.ir.TypeRefR\x04type\"J\n" +
	"\vTableColumn\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x04type\x18\x02 \x01(\v2\x13.sqld.v1.ir.TypeRefR\x04type\"@\n" +
	"\vTableReturn\x121\n" +
	"\acolumns\x18\x01 \x03(\v2\x17.sqld.v1.ir.TableColumnR\acolumns\"\xeb\x01\n" +
	"\n" +
	"ReturnType\x12-\n" +
	"\x06scalar\x18\x01 \x01(\v2\x13.sqld.v1.ir.TypeRefH\x00R\x06scalar\x12-\n" +
	"\x05setof\x18\x02 \x01(\v2\x15.sqld.v1.ir.SetofTypeH\x00R\x05setof\x12/\n" +
	"\x05table\x18\x03 \x01(\v2\x17.sqld.v1.ir.TableReturnH\x00R\x05table\x12\x1f\n" +
	"\n" +
	"void_value\x18\x04 \x01(\bH\x00R\tvoidValue\x12%\n" +
	"\rtrigger_value\x18\x05 \x01(\bH\x00R\ftriggerValueB\x06\n" +
	"\x04kind\"\x81\x05\n" +
	"\bFunction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04name\x18\x02 \x01(\v2\x19.sqld.v1.ir.QualifiedNameR\x04name\x122\n" +
	"\targuments\x18\x03 \x03(\v2\x14.sqld.v1.ir.ArgumentR\targuments\x120\n" +
	"\areturns\x18\x04 \x01(\v2\x16.sqld.v1.ir.ReturnTypeR\areturns\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x126\n" +
	"\n" +
	"volatility\x18\x06 \x01(\x0e2\x16.sqld.v1.ir.VolatilityR\n" +
	"volatility\x12<\n" +
	"\n" +
	"null_input\x18\a \x01(\x0e2\x1d.sqld.v1.ir.NullInputBehaviorR\tnullInput\x12)\n" +
	"\x10security_definer\x18\b \x01(\bR\x0fsecurityDefiner\x12\x1c\n" +
	"\tleakproof\x18\t \x01(\bR\tleakproof\x126\n" +
	"\bparallel\x18\n" +
	" \x01(\x0e2\x1a.sqld.v1.ir.ParallelSafetyR\bparallel\x12%\n" +
	"\x0eestimated_cost\x18\v \x01(\x05R\restimatedCost\x12%\n" +
	"\x0eestimated_rows\x18\f \x01(\x05R\restimatedRows\x12\x12\n" +
	"\x04body\x18\r \x01(\tR\x04body\x121\n" +
	"\bsql_body\x18\x0e \x03(\v2\x16.sqld.v1.ir.SelectStmtR\asqlBody\x12(\n" +
	"\x04meta\x18\x14 \x01(\v2\x14.sqld.v1.ir.MetadataR\x04meta\"\xb6\x02\n" +
	"\tProcedure\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04name\x18\x02 \x01(\v2\x19.sqld.v1.ir.QualifiedNameR\x04name\x122\n" +
	"\targuments\x18\x03 \x03(\v2\x14.sqld.v1.ir.ArgumentR\targuments\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12)\n" +
	"\x10security_definer\x18\x05 \x01(\bR\x0fsecurityDefiner\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x121\n" +
	"\bsql_body\x18\a \x03(\v2\x16.sqld.v1.ir.SelectStmtR\asqlBody\x12(\n" +
	"\x04meta\x18\x0f \x01(\v2\x14.sqld.v1.ir.MetadataR\x04meta\"\xd7\x03\n" +
	"\aTrigger\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\x05table\x18\x03 \x01(\v2\x15.sqld.v1.ir.ObjectRefR\x05table\x121\n" +
	"\x06timing\x18\x04 \x01(\x0e2\x19.sqld.v1.ir.TriggerTimingR\x06timing\x120\n" +
	"\x06events\x18\x05 \x03(\x0e2\x18.sqld.v1.ir.TriggerEventR\x06events\x12%\n" +
	"\x0eupdate_columns\x18\x06 \x03(\tR\rupdateColumns\x12.\n" +
	"\x05level\x18\a \x01(\x0e2\x18.sqld.v1.ir.TriggerLevelR\x05level\x12\x1e\n" +
	"\n" +
	"constraint\x18\b \x01(\bR\n" +
	"constraint\x12$\n" +
	"\x04when\x18\t \x01(\v2\x10.sqld.v1.ir.ExprR\x04when\x121\n" +
	"\bfunction\x18\n" +
	" \x01(\v2\x15.sqld.v1.ir.ObjectRefR\bfunction\x12\x1c\n" +
	"\targuments\x18\v \x03(\tR\targuments\x12(\n" +
	"\x04meta\x18\x0f \x01(\v2\x14.sqld.v1.ir.MetadataR\x04meta*^\n" +
	"\vCheckOption\x12\x1c\n" +
	"\x18CHECK_OPTION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CHECK_OPTION_LOCAL\x10\x01\x12\x19\n" +
	"\x15CHECK_OPTION_CASCADED\x10\x02*q\n" +
	"\aArgMode\x12\x18\n" +
	"\x14ARG_MODE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vARG_MODE_IN\x10\x01\x12\x10\n" +
	"\fARG_MODE_OUT\x10\x02\x12\x12\n" +
	"\x0eARG_MODE_INOUT\x10\x03\x12\x15\n" +
	"\x11ARG_MODE_VARIADIC\x10\x04*r\n" +
	"\n" +
	"Volatility\x12\x1a\n" +
	"\x16VOLATILITY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13VOLATILITY_VOLATILE\x10\x01\x12\x15\n" +
	"\x11VOLATILITY_STABLE\x10\x02\x12\x18\n" +
	"\x14VOLATILITY_IMMUTABLE\x10\x03*\x87\x01\n" +
	"\x0eParallelSafety\x12\x1f\n" +
	"\x1bPARALLEL_SAFETY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PARALLEL_SAFETY_UNSAFE\x10\x01\x12\x1e\n" +
	"\x1aPARALLEL_SAFETY_RESTRICTED\x10\x02\x12\x18\n" +
	"\x14PARALLEL_SAFETY_SAFE\x10\x03*x\n" +
	"\x11NullInputBehavior\x12#\n" +
	"\x1fNULL_INPUT_BEHAVIOR_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aNULL_INPUT_BEHAVIOR_CALLED\x10\x01\x12\x1e\n" +
	"\x1aNULL_INPUT_BEHAVIOR_STRICT\x10\x02*\x83\x01\n" +
	"\rTriggerTiming\x12\x1e\n" +
	"\x1aTRIGGER_TIMING_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TRIGGER_TIMING_BEFORE\x10\x01\x12\x18\n" +
	"\x14TRIGGER_TIMING_AFTER\x10\x02\x12\x1d\n" +
	"\x19TRIGGER_TIMING_INSTEAD_OF\x10\x03*\x97\x01\n" +
	"\fTriggerEvent\x12\x1d\n" +
	"\x19TRIGGER_EVENT_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TRIGGER_EVENT_INSERT\x10\x01\x12\x18\n" +
	"\x14TRIGGER_EVENT_UPDATE\x10\x02\x12\x18\n" +
	"\x14TRIGGER_EVENT_DELETE\x10\x03\x12\x1a\n" +
	"\x16TRIGGER_EVENT_TRUNCATE\x10\x04*a\n" +
	"\fTriggerLevel\x12\x1d\n" +
	"\x19TRIGGER_LEVEL_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TRIGGER_LEVEL_ROW\x10\x01\x12\x1b\n" +
	"\x17TRIGGER_LEVEL_STATEMENT\x10\x02B4Z2github.com/gopherex/sqld/pkg/proto/sqld/v1/ir;irv1b\x06proto3"

var (
	file_sqld_v1_ir_routine_proto_rawDescOnce sync.Once
	file_sqld_v1_ir_routine_proto_rawDescData []byte
)

func file_sqld_v1_ir_routine_proto_rawDescGZIP() []byte {
	file_sqld_v1_ir_routine_proto_rawDescOnce.Do(func() {
		file_sqld_v1_ir_routine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sqld_v1_ir_routine_proto_rawDesc), len(file_sqld_v1_ir_routine_proto_rawDesc)))
	})
	return file_sqld_v1_ir_routine_proto_rawDescData
}

var file_sqld_v1_ir_routine_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_sqld_v1_ir_routine_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_sqld_v1_ir_routine_proto_goTypes = []any{
	(CheckOption)(0),         // 0: sqld.v1.ir.CheckOption
	(ArgMode)(0),             // 1: sqld.v1.ir.ArgMode
	(Volatility)(0),          // 2: sqld.v1.ir.Volatility
	(ParallelSafety)(0),      // 3: sqld.v1.ir.ParallelSafety
	(NullInputBehavior)(0),   // 4: sqld.v1.ir.NullInputBehavior
	(TriggerTiming)(0),       // 5: sqld.v1.ir.TriggerTiming
	(TriggerEvent)(0),        // 6: sqld.v1.ir.TriggerEvent
	(TriggerLevel)(0),        // 7: sqld.v1.ir.TriggerLevel
	(*EnumType)(nil),         // 8: sqld.v1.ir.EnumType
	(*DomainConstraint)(nil), // 9: sqld.v1.ir.DomainConstraint
	(*DomainType)(nil),       // 10: sqld.v1.ir.DomainType
	(*CompositeField)(nil),   // 11: sqld.v1.ir.CompositeField
	(*CompositeType)(nil),    // 12: sqld.v1.ir.CompositeType
	(*RangeType)(nil),        // 13: sqld.v1.ir.RangeType
	(*View)(nil),             // 14: sqld.v1.ir.View
	(*MaterializedView)(nil), // 15: sqld.v1.ir.MaterializedView
	(*Argument)(nil),         // 16: sqld.v1.ir.Argument
	(*SetofType)(nil),        // 17: sqld.v1.ir.SetofType
	(*TableColumn)(nil),      // 18: sqld.v1.ir.TableColumn
	(*TableReturn)(nil),      // 19: sqld.v1.ir.TableReturn
	(*ReturnType)(nil),       // 20: sqld.v1.ir.ReturnType
	(*Function)(nil),         // 21: sqld.v1.ir.Function
	(*Procedure)(nil),        // 22: sqld.v1.ir.Procedure
	(*Trigger)(nil),          // 23: sqld.v1.ir.Trigger
	(*QualifiedName)(nil),    // 24: sqld.v1.ir.QualifiedName
	(*Metadata)(nil),         // 25: sqld.v1.ir.Metadata
	(*Expr)(nil),             // 26: sqld.v1.ir.Expr
	(*TypeRef)(nil),          // 27: sqld.v1.ir.TypeRef
	(*SelectStmt)(nil),       // 28: sqld.v1.ir.SelectStmt
	(*Index)(nil),            // 29: sqld.v1.ir.Index
	(*ObjectRef)(nil),        // 30: sqld.v1.ir.ObjectRef
}
var file_sqld_v1_ir_routine_proto_depIdxs = []int32{
	24, // 0: sqld.v1.ir.EnumType.name:type_name -> sqld.v1.ir.QualifiedName
	25, // 1: sqld.v1.ir.EnumType.meta:type_name -> sqld.v1.ir.Metadata
	26, // 2: sqld.v1.ir.DomainConstraint.check:type_name -> sqld.v1.ir.Expr
	24, // 3: sqld.v1.ir.DomainType.name:type_name -> sqld.v1.ir.QualifiedName
	27, // 4: sqld.v1.ir.DomainType.base_type:type_name -> sqld.v1.ir.TypeRef
	26, // 5: sqld.v1.ir.DomainType.default_expr:type_name -> sqld.v1.ir.Expr
	9,  // 6: sqld.v1.ir.DomainType.constraints:type_name -> sqld.v1.ir.DomainConstraint
	25, // 7: sqld.v1.ir.DomainType.meta:type_name -> sqld.v1.ir.Metadata
	27, // 8: sqld.v1.ir.CompositeField.type:type_name -> sqld.v1.ir.TypeRef
	24, // 9: sqld.v1.ir.CompositeType.name:type_name -> sqld.v1.ir.QualifiedName
	11, // 10: sqld.v1.ir.CompositeType.fields:type_name -> sqld.v1.ir.CompositeField
	25, // 11: sqld.v1.ir.CompositeType.meta:type_name -> sqld.v1.ir.Metadata
	24, // 12: sqld.v1.ir.RangeType.name:type_name -> sqld.v1.ir.QualifiedName
	27, // 13: sqld.v1.ir.RangeType.subtype:type_name -> sqld.v1.ir.TypeRef
	25, // 14: sqld.v1.ir.RangeType.meta:type_name -> sqld.v1.ir.Metadata
	24, // 15: sqld.v1.ir.View.name:type_name -> sqld.v1.ir.QualifiedName
	28, // 16: sqld.v1.ir.View.query:type_name -> sqld.v1.ir.SelectStmt
	0,  // 17: sqld.v1.ir.View.check_option:type_name -> sqld.v1.ir.CheckOption
	25, // 18: sqld.v1.ir.View.meta:type_name -> sqld.v1.ir.Metadata
	24, // 19: sqld.v1.ir.MaterializedView.name:type_name -> sqld.v1.ir.QualifiedName
	28, // 20: sqld.v1.ir.MaterializedView.query:type_name -> sqld.v1.ir.SelectStmt
	29, // 21: sqld.v1.ir.MaterializedView.indexes:type_name -> sqld.v1.ir.Index
	25, // 22: sqld.v1.ir.MaterializedView.meta:type_name -> sqld.v1.ir.Metadata
	27, // 23: sqld.v1.ir.Argument.type:type_name -> sqld.v1.ir.TypeRef
	1,  // 24: sqld.v1.ir.Argument.mode:type_name -> sqld.v1.ir.ArgMode
	26, // 25: sqld.v1.ir.Argument.default_value:type_name -> sqld.v1.ir.Expr
	27, // 26: sqld.v1.ir.SetofType.type:type_name -> sqld.v1.ir.TypeRef
	27, // 27: sqld.v1.ir.TableColumn.type:type_name -> sqld.v1.ir.TypeRef
	18, // 28: sqld.v1.ir.TableReturn.columns:type_name -> sqld.v1.ir.TableColumn
	27, // 29: sqld.v1.ir.ReturnType.scalar:type_name -> sqld.v1.ir.TypeRef
	17, // 30: sqld.v1.ir.ReturnType.setof:type_name -> sqld.v1.ir.SetofType
	19, // 31: sqld.v1.ir.ReturnType.table:type_name -> sqld.v1.ir.TableReturn
	24, // 32: sqld.v1.ir.Function.name:type_name -> sqld.v1.ir.QualifiedName
	16, // 33: sqld.v1.ir.Function.arguments:type_name -> sqld.v1.ir.Argument
	20, // 34: sqld.v1.ir.Function.returns:type_name -> sqld.v1.ir.ReturnType
	2,  // 35: sqld.v1.ir.Function.volatility:type_name -> sqld.v1.ir.Volatility
	4,  // 36: sqld.v1.ir.Function.null_input:type_name -> sqld.v1.ir.NullInputBehavior
	3,  // 37: sqld.v1.ir.Function.parallel:type_name -> sqld.v1.ir.ParallelSafety
	28, // 38: sqld.v1.ir.Function.sql_body:type_name -> sqld.v1.ir.SelectStmt
	25, // 39: sqld.v1.ir.Function.meta:type_name -> sqld.v1.ir.Metadata
	24, // 40: sqld.v1.ir.Procedure.name:type_name -> sqld.v1.ir.QualifiedName
	16, // 41: sqld.v1.ir.Procedure.arguments:type_name -> sqld.v1.ir.Argument
	28, // 42: sqld.v1.ir.Procedure.sql_body:type_name -> sqld.v1.ir.SelectStmt
	25, // 43: sqld.v1.ir.Procedure.meta:type_name -> sqld.v1.ir.Metadata
	30, // 44: sqld.v1.ir.Trigger.table:type_name -> sqld.v1.ir.ObjectRef
	5,  // 45: sqld.v1.ir.Trigger.timing:type_name -> sqld.v1.ir.TriggerTiming
	6,  // 46: sqld.v1.ir.Trigger.events:type_name -> sqld.v1.ir.TriggerEvent
	7,  // 47: sqld.v1.ir.Trigger.level:type_name -> sqld.v1.ir.TriggerLevel
	26, // 48: sqld.v1.ir.Trigger.when:type_name -> sqld.v1.ir.Expr
	30, // 49: sqld.v1.ir.Trigger.function:type_name -> sqld.v1.ir.ObjectRef
	25, // 50: sqld.v1.ir.Trigger.meta:type_name -> sqld.v1.ir.Metadata
	51, // [51:51] is the sub-list for method output_type
	51, // [51:51] is the sub-list for method input_type
	51, // [51:51] is the sub-list for extension type_name
	51, // [51:51] is the sub-list for extension extendee
	0,  // [0:51] is the sub-list for field type_name
}

func init() { file_sqld_v1_ir_routine_proto_init() }
func file_sqld_v1_ir_routine_proto_init() {
	if File_sqld_v1_ir_routine_proto != nil {
		return
	}
	file_sqld_v1_ir_common_proto_init()
	file_sqld_v1_ir_type_proto_init()
	file_sqld_v1_ir_expr_proto_init()
	file_sqld_v1_ir_schema_proto_init()
	file_sqld_v1_ir_routine_proto_msgTypes[12].OneofWrappers = []any{
		(*ReturnType_Scalar)(nil),
		(*ReturnType_Setof)(nil),
		(*ReturnType_Table)(nil),
		(*ReturnType_VoidValue)(nil),
		(*ReturnType_TriggerValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sqld_v1_ir_routine_proto_rawDesc), len(file_sqld_v1_ir_routine_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sqld_v1_ir_routine_proto_goTypes,
		DependencyIndexes: file_sqld_v1_ir_routine_proto_depIdxs,
		EnumInfos:         file_sqld_v1_ir_routine_proto_enumTypes,
		MessageInfos:      file_sqld_v1_ir_routine_proto_msgTypes,
	}.Build()
	File_sqld_v1_ir_routine_proto = out.File
	file_sqld_v1_ir_routine_proto_goTypes = nil
	file_sqld_v1_ir_routine_proto_depIdxs = nil
}
