// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: sqld/v1/ir/type.proto

package irv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TypeKind is the broad category of a type reference.
type TypeKind int32

const (
	TypeKind_TYPE_KIND_UNSPECIFIED  TypeKind = 0
	TypeKind_TYPE_KIND_SCALAR       TypeKind = 1 // built-in base type (int4, text, uuid, jsonb...)
	TypeKind_TYPE_KIND_ARRAY        TypeKind = 2 // element[] ; see `element` + `array_dimensions`
	TypeKind_TYPE_KIND_ENUM         TypeKind = 3 // user enum; see `udt`
	TypeKind_TYPE_KIND_DOMAIN       TypeKind = 4 // user domain; see `udt`
	TypeKind_TYPE_KIND_COMPOSITE    TypeKind = 5 // user composite/row type; see `udt`
	TypeKind_TYPE_KIND_RANGE        TypeKind = 6 // range type; see `udt`
	TypeKind_TYPE_KIND_PSEUDO       TypeKind = 7 // void, record, trigger, anyelement, ...
	TypeKind_TYPE_KIND_USER_DEFINED TypeKind = 8 // any other named user type; see `udt`
)

// Enum value maps for TypeKind.
var (
	TypeKind_name = map[int32]string{
		0: "TYPE_KIND_UNSPECIFIED",
		1: "TYPE_KIND_SCALAR",
		2: "TYPE_KIND_ARRAY",
		3: "TYPE_KIND_ENUM",
		4: "TYPE_KIND_DOMAIN",
		5: "TYPE_KIND_COMPOSITE",
		6: "TYPE_KIND_RANGE",
		7: "TYPE_KIND_PSEUDO",
		8: "TYPE_KIND_USER_DEFINED",
	}
	TypeKind_value = map[string]int32{
		"TYPE_KIND_UNSPECIFIED":  0,
		"TYPE_KIND_SCALAR":       1,
		"TYPE_KIND_ARRAY":        2,
		"TYPE_KIND_ENUM":         3,
		"TYPE_KIND_DOMAIN":       4,
		"TYPE_KIND_COMPOSITE":    5,
		"TYPE_KIND_RANGE":        6,
		"TYPE_KIND_PSEUDO":       7,
		"TYPE_KIND_USER_DEFINED": 8,
	}
)

func (x TypeKind) Enum() *TypeKind {
	p := new(TypeKind)
	*p = x
	return p
}

func (x TypeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_sqld_v1_ir_type_proto_enumTypes[0].Descriptor()
}

func (TypeKind) Type() protoreflect.EnumType {
	return &file_sqld_v1_ir_type_proto_enumTypes[0]
}

func (x TypeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypeKind.Descriptor instead.
func (TypeKind) EnumDescriptor() ([]byte, []int) {
	return file_sqld_v1_ir_type_proto_rawDescGZIP(), []int{0}
}

// NumericModifier covers numeric(p, s) precision/scale.
type NumericModifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Precision     uint32                 `protobuf:"varint,1,opt,name=precision,proto3" json:"precision,omitempty"`
	Scale         uint32                 `protobuf:"varint,2,opt,name=scale,proto3" json:"scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumericModifier) Reset() {
	*x = NumericModifier{}
	mi := &file_sqld_v1_ir_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumericModifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericModifier) ProtoMessage() {}

func (x *NumericModifier) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericModifier.ProtoReflect.Descriptor instead.
func (*NumericModifier) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_type_proto_rawDescGZIP(), []int{0}
}

func (x *NumericModifier) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *NumericModifier) GetScale() uint32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

// StringModifier covers varchar(n), char(n), bit(n), varbit(n) length.
type StringModifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        uint32                 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringModifier) Reset() {
	*x = StringModifier{}
	mi := &file_sqld_v1_ir_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringModifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringModifier) ProtoMessage() {}

func (x *StringModifier) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringModifier.ProtoReflect.Descriptor instead.
func (*StringModifier) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_type_proto_rawDescGZIP(), []int{1}
}

func (x *StringModifier) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

// DateTimeModifier covers timestamp/time [with time zone] and sub-second
// precision.
type DateTimeModifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WithTimezone  bool                   `protobuf:"varint,1,opt,name=with_timezone,json=withTimezone,proto3" json:"with_timezone,omitempty"`
	Precision     uint32                 `protobuf:"varint,2,opt,name=precision,proto3" json:"precision,omitempty"` // fractional seconds precision, when given
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateTimeModifier) Reset() {
	*x = DateTimeModifier{}
	mi := &file_sqld_v1_ir_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateTimeModifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateTimeModifier) ProtoMessage() {}

func (x *DateTimeModifier) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateTimeModifier.ProtoReflect.Descriptor instead.
func (*DateTimeModifier) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_type_proto_rawDescGZIP(), []int{2}
}

func (x *DateTimeModifier) GetWithTimezone() bool {
	if x != nil {
		return x.WithTimezone
	}
	return false
}

func (x *DateTimeModifier) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

// IntervalModifier covers interval field restriction and precision,
// e.g. INTERVAL DAY TO SECOND(3).
type IntervalModifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        string                 `protobuf:"bytes,1,opt,name=fields,proto3" json:"fields,omitempty"` // "YEAR", "DAY TO SECOND", ... ; empty = unrestricted
	Precision     uint32                 `protobuf:"varint,2,opt,name=precision,proto3" json:"precision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntervalModifier) Reset() {
	*x = IntervalModifier{}
	mi := &file_sqld_v1_ir_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntervalModifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntervalModifier) ProtoMessage() {}

func (x *IntervalModifier) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntervalModifier.ProtoReflect.Descriptor instead.
func (*IntervalModifier) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_type_proto_rawDescGZIP(), []int{3}
}

func (x *IntervalModifier) GetFields() string {
	if x != nil {
		return x.Fields
	}
	return ""
}

func (x *IntervalModifier) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

// TypeModifier holds the parameters of a parametrized type.
type TypeModifier struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Modifier:
	//
	//	*TypeModifier_Numeric
	//	*TypeModifier_Text
	//	*TypeModifier_DateTime
	//	*TypeModifier_Interval
	Modifier      isTypeModifier_Modifier `protobuf_oneof:"modifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeModifier) Reset() {
	*x = TypeModifier{}
	mi := &file_sqld_v1_ir_type_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeModifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeModifier) ProtoMessage() {}

func (x *TypeModifier) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_type_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeModifier.ProtoReflect.Descriptor instead.
func (*TypeModifier) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_type_proto_rawDescGZIP(), []int{4}
}

func (x *TypeModifier) GetModifier() isTypeModifier_Modifier {
	if x != nil {
		return x.Modifier
	}
	return nil
}

func (x *TypeModifier) GetNumeric() *NumericModifier {
	if x != nil {
		if x, ok := x.Modifier.(*TypeModifier_Numeric); ok {
			return x.Numeric
		}
	}
	return nil
}

func (x *TypeModifier) GetText() *StringModifier {
	if x != nil {
		if x, ok := x.Modifier.(*TypeModifier_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *TypeModifier) GetDateTime() *DateTimeModifier {
	if x != nil {
		if x, ok := x.Modifier.(*TypeModifier_DateTime); ok {
			return x.DateTime
		}
	}
	return nil
}

func (x *TypeModifier) GetInterval() *IntervalModifier {
	if x != nil {
		if x, ok := x.Modifier.(*TypeModifier_Interval); ok {
			return x.Interval
		}
	}
	return nil
}

type isTypeModifier_Modifier interface {
	isTypeModifier_Modifier()
}

type TypeModifier_Numeric struct {
	Numeric *NumericModifier `protobuf:"bytes,1,opt,name=numeric,proto3,oneof"`
}

type TypeModifier_Text struct {
	Text *StringModifier `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type TypeModifier_DateTime struct {
	DateTime *DateTimeModifier `protobuf:"bytes,3,opt,name=date_time,json=dateTime,proto3,oneof"`
}

type TypeModifier_Interval struct {
	Interval *IntervalModifier `protobuf:"bytes,4,opt,name=interval,proto3,oneof"`
}

func (*TypeModifier_Numeric) isTypeModifier_Modifier() {}

func (*TypeModifier_Text) isTypeModifier_Modifier() {}

func (*TypeModifier_DateTime) isTypeModifier_Modifier() {}

func (*TypeModifier_Interval) isTypeModifier_Modifier() {}

// TypeRef is a fully-resolved reference to a type at a use site (column,
// argument, cast target, ...). It is PG-faithful: `pg_name` holds the canonical
// PostgreSQL type name.
type TypeRef struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Kind     TypeKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=sqld.v1.ir.TypeKind" json:"kind,omitempty"`
	PgName   string                 `protobuf:"bytes,2,opt,name=pg_name,json=pgName,proto3" json:"pg_name,omitempty"` // "int4", "varchar", "jsonb", "_int4" (array), ...
	Modifier *TypeModifier          `protobuf:"bytes,3,opt,name=modifier,proto3" json:"modifier,omitempty"`           // present for parametrized types
	// For TYPE_KIND_ARRAY: the element type and number of array dimensions.
	Element         *TypeRef `protobuf:"bytes,4,opt,name=element,proto3" json:"element,omitempty"`
	ArrayDimensions uint32   `protobuf:"varint,5,opt,name=array_dimensions,json=arrayDimensions,proto3" json:"array_dimensions,omitempty"`
	// For ENUM / DOMAIN / COMPOSITE / RANGE / USER_DEFINED: the defining object.
	Udt           *ObjectRef `protobuf:"bytes,6,opt,name=udt,proto3" json:"udt,omitempty"`
	Meta          *Metadata  `protobuf:"bytes,15,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeRef) Reset() {
	*x = TypeRef{}
	mi := &file_sqld_v1_ir_type_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeRef) ProtoMessage() {}

func (x *TypeRef) ProtoReflect() protoreflect.Message {
	mi := &file_sqld_v1_ir_type_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeRef.ProtoReflect.Descriptor instead.
func (*TypeRef) Descriptor() ([]byte, []int) {
	return file_sqld_v1_ir_type_proto_rawDescGZIP(), []int{5}
}

func (x *TypeRef) GetKind() TypeKind {
	if x != nil {
		return x.Kind
	}
	return TypeKind_TYPE_KIND_UNSPECIFIED
}

func (x *TypeRef) GetPgName() string {
	if x != nil {
		return x.PgName
	}
	return ""
}

func (x *TypeRef) GetModifier() *TypeModifier {
	if x != nil {
		return x.Modifier
	}
	return nil
}

func (x *TypeRef) GetElement() *TypeRef {
	if x != nil {
		return x.Element
	}
	return nil
}

func (x *TypeRef) GetArrayDimensions() uint32 {
	if x != nil {
		return x.ArrayDimensions
	}
	return 0
}

func (x *TypeRef) GetUdt() *ObjectRef {
	if x != nil {
		return x.Udt
	}
	return nil
}

func (x *TypeRef) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_sqld_v1_ir_type_proto protoreflect.FileDescriptor

const file_sqld_v1_ir_type_proto_rawDesc = "" +
	"\n" +
	"\x15sqld/v1/ir/type.proto\x12\n" +
	"sqld.v1.ir\x1a\x17sqld/v1/ir/common.proto\"E\n" +
	"\x0fNumericModifier\x12\x1c\n" +
	"\tprecision\x18\x01 \x01(\rR\tprecision\x12\x14\n" +
	"\x05scale\x18\x02 \x01(\rR\x05scale\"(\n" +
	"\x0eStringModifier\x12\x16\n" +
	"\x06length\x18\x01 \x01(\rR\x06length\"U\n" +
	"\x10DateTimeModifier\x12#\n" +
	"\rwith_timezone\x18\x01 \x01(\bR\fwithTimezone\x12\x1c\n" +
	"\tprecision\x18\x02 \x01(\rR\tprecision\"H\n" +
	"\x10IntervalModifier\x12\x16\n" +
	"\x06fields\x18\x01 \x01(\tR\x06fields\x12\x1c\n" +
	"\tprecision\x18\x02 \x01(\rR\tprecision\"\xfe\x01\n" +
	"\fTypeModifier\x127\n" +
	"\anumeric\x18\x01 \x01(\v2\x1b.sqld.v1.ir.NumericModifierH\x00R\anumeric\x120\n" +
	"\x04text\x18\x02 \x01(\v2\x1a.sqld.v1.ir.StringModifierH\x00R\x04text\x12;\n" +
	"\tdate_time\x18\x03 \x01(\v2\x1c.sqld.v1.ir.DateTimeModifierH\x00R\bdateTime\x12:\n" +
	"\binterval\x18\x04 \x01(\v2\x1c.sqld.v1.ir.IntervalModifierH\x00R\bintervalB\n" +
	"\n" +
	"\bmodifier\"\xaf\x02\n" +
	"\aTypeRef\x12(\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x14.sqld.v1.ir.TypeKindR\x04kind\x12\x17\n" +
	"\apg_name\x18\x02 \x01(\tR\x06pgName\x124\n" +
	"\bmodifier\x18\x03 \x01(\v2\x18.sqld.v1.ir.TypeModifierR\bmodifier\x12-\n" +
	"\aelement\x18\x04 \x01(\v2\x13.sqld.v1.ir.TypeRefR\aelement\x12)\n" +
	"\x10array_dimensions\x18\x05 \x01(\rR\x0farrayDimensions\x12'\n" +
	"\x03udt\x18\x06 \x01(\v2\x15.sqld.v1.ir.ObjectRefR\x03udt\x12(\n" +
	"\x04meta\x18\x0f \x01(\v2\x14.sqld.v1.ir.MetadataR\x04meta*\xda\x01\n" +
	"\bTypeKind\x12\x19\n" +
	"\x15TYPE_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TYPE_KIND_SCALAR\x10\x01\x12\x13\n" +
	"\x0fTYPE_KIND_ARRAY\x10\x02\x12\x12\n" +
	"\x0eTYPE_KIND_ENUM\x10\x03\x12\x14\n" +
	"\x10TYPE_KIND_DOMAIN\x10\x04\x12\x17\n" +
	"\x13TYPE_KIND_COMPOSITE\x10\x05\x12\x13\n" +
	"\x0fTYPE_KIND_RANGE\x10\x06\x12\x14\n" +
	"\x10TYPE_KIND_PSEUDO\x10\a\x12\x1a\n" +
	"\x16TYPE_KIND_USER_DEFINED\x10\bB3Z1github.com/yaroher/sqld/pkg/proto/sqld/v1/ir;irv1b\x06proto3"

var (
	file_sqld_v1_ir_type_proto_rawDescOnce sync.Once
	file_sqld_v1_ir_type_proto_rawDescData []byte
)

func file_sqld_v1_ir_type_proto_rawDescGZIP() []byte {
	file_sqld_v1_ir_type_proto_rawDescOnce.Do(func() {
		file_sqld_v1_ir_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sqld_v1_ir_type_proto_rawDesc), len(file_sqld_v1_ir_type_proto_rawDesc)))
	})
	return file_sqld_v1_ir_type_proto_rawDescData
}

var file_sqld_v1_ir_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sqld_v1_ir_type_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sqld_v1_ir_type_proto_goTypes = []any{
	(TypeKind)(0),            // 0: sqld.v1.ir.TypeKind
	(*NumericModifier)(nil),  // 1: sqld.v1.ir.NumericModifier
	(*StringModifier)(nil),   // 2: sqld.v1.ir.StringModifier
	(*DateTimeModifier)(nil), // 3: sqld.v1.ir.DateTimeModifier
	(*IntervalModifier)(nil), // 4: sqld.v1.ir.IntervalModifier
	(*TypeModifier)(nil),     // 5: sqld.v1.ir.TypeModifier
	(*TypeRef)(nil),          // 6: sqld.v1.ir.TypeRef
	(*ObjectRef)(nil),        // 7: sqld.v1.ir.ObjectRef
	(*Metadata)(nil),         // 8: sqld.v1.ir.Metadata
}
var file_sqld_v1_ir_type_proto_depIdxs = []int32{
	1, // 0: sqld.v1.ir.TypeModifier.numeric:type_name -> sqld.v1.ir.NumericModifier
	2, // 1: sqld.v1.ir.TypeModifier.text:type_name -> sqld.v1.ir.StringModifier
	3, // 2: sqld.v1.ir.TypeModifier.date_time:type_name -> sqld.v1.ir.DateTimeModifier
	4, // 3: sqld.v1.ir.TypeModifier.interval:type_name -> sqld.v1.ir.IntervalModifier
	0, // 4: sqld.v1.ir.TypeRef.kind:type_name -> sqld.v1.ir.TypeKind
	5, // 5: sqld.v1.ir.TypeRef.modifier:type_name -> sqld.v1.ir.TypeModifier
	6, // 6: sqld.v1.ir.TypeRef.element:type_name -> sqld.v1.ir.TypeRef
	7, // 7: sqld.v1.ir.TypeRef.udt:type_name -> sqld.v1.ir.ObjectRef
	8, // 8: sqld.v1.ir.TypeRef.meta:type_name -> sqld.v1.ir.Metadata
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_sqld_v1_ir_type_proto_init() }
func file_sqld_v1_ir_type_proto_init() {
	if File_sqld_v1_ir_type_proto != nil {
		return
	}
	file_sqld_v1_ir_common_proto_init()
	file_sqld_v1_ir_type_proto_msgTypes[4].OneofWrappers = []any{
		(*TypeModifier_Numeric)(nil),
		(*TypeModifier_Text)(nil),
		(*TypeModifier_DateTime)(nil),
		(*TypeModifier_Interval)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sqld_v1_ir_type_proto_rawDesc), len(file_sqld_v1_ir_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sqld_v1_ir_type_proto_goTypes,
		DependencyIndexes: file_sqld_v1_ir_type_proto_depIdxs,
		EnumInfos:         file_sqld_v1_ir_type_proto_enumTypes,
		MessageInfos:      file_sqld_v1_ir_type_proto_msgTypes,
	}.Build()
	File_sqld_v1_ir_type_proto = out.File
	file_sqld_v1_ir_type_proto_goTypes = nil
	file_sqld_v1_ir_type_proto_depIdxs = nil
}
